### ISSUE TITLE
[java] (question) - Use different version of pmd-core and pmd-java

### ISSUE THREAD

**Issue by fflatorre** [pmd/pmd#1037]
I'm trying to upgrade pmd-core to leverage the caching benefits (version 6.2.0) but still keep using the existing rule set (version 5.5.2), however every attempt fails with exception like : 
```
java.lang.NoSuchMethodError: net.sourceforge.pmd.lang.java.rule.basic.AvoidUsingOctalValuesRule.definePropertyDescriptor(Lnet/sourceforge/pmd/PropertyDescriptor;)V

        at net.sourceforge.pmd.lang.java.rule.basic.AvoidUsingOctalValuesRule.<init>(AvoidUsingOctalValuesRule.java:23)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at net.sourceforge.pmd.rules.RuleBuilder.build(RuleBuilder.java:179)
        at net.sourceforge.pmd.rules.RuleFactory.buildRule(RuleFactory.java:189)
        at net.sourceforge.pmd.RuleSetFactory.parseSingleRuleNode(RuleSetFactory.java:562)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:461)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:367)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:214)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:209)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetReferenceNode(RuleSetFactory.java:500)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:459)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:367)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:214)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:209)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:170)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:154)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:119)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:277)
        at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:50)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:346)
        at java.util.Vector.forEach(Vector.java:1249)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
        at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:346)
        at java.util.Vector.forEach(Vector.java:1249)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:346)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:346)
        at org.apache.tools.ant.taskdefs.Parallel$TaskRunnable.run(Parallel.java:455)
        at java.lang.Thread.run(Thread.java:748)
```
Not sure if anything to do with [this commit](https://github.com/pmd/pmd/commit/6295a967831a3cec0298b1260d7bfb056ed5b22b)
Is it possible to run pmd-core against an older version of pmd-java ?
Thanks,
Francesco

**Affects PMD Version:** 
5.5.2,6.2.0
**Rule:**
NA
**Description:**
NA
**Code Sample demonstrating the issue:**

```
NA
```

**Running PMD through:** *[Ant]*

**Comment by fflatorre** [comment]
Hi @adangel , 

Thanks for the clarification.
Using version 6.2.0, along side the mentioned warning messages we started to get new violations (a lot more) so I suspect the rules _maybe are not_ compatible.
On top of that, the report is not built correctly so there is a bit of work to do.

Cheers,
Francesco

**Comment by jsotuyod** [comment]
@fflatorre rules are compatible, but we did many improvements since 5.5, so lots of false negatives have been fixed. If you were referencing whole rulesets you may also be getting new rules applied.

If you do find any false positives, please report it in a separate issue.
