### ISSUE TITLE
[apex] ClassCastException caused by Javadoc

### ISSUE THREAD

**Issue by danbrycefairsailcom** [pmd/pmd#1396]
**Affects PMD Version:** 6.8.0

**Rule:**
apex.rule.design.ExcessiveNodeCountRule
apex.rule.design.NcssMethodCountRule
apex.rule.design.NcssTypeCountRule

**Description:** ClassCastException occurs when running `pmd.bat` against Apex files containing Javadoc comments.

```
java.lang.ClassCastException: net.sourceforge.pmd.lang.apex.ast.ASTFormalComment cannot be cast to net.sourceforge.pmd.lang.apex.ast.ApexNode
	at net.sourceforge.pmd.lang.apex.rule.design.ExcessiveNodeCountRule.visit(ExcessiveNodeCountRule.java:42)
	at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:157)
	at net.sourceforge.pmd.lang.apex.ast.ASTMethod.jjtAccept(ASTMethod.java:22)
	at net.sourceforge.pmd.lang.apex.rule.design.ExcessiveNodeCountRule.visit(ExcessiveNodeCountRule.java:42)
	at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:162)
	at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visitAll(AbstractApexRule.java:134)
	at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:128)
	at net.sourceforge.pmd.lang.apex.rule.AbstractStatisticalApexRule.apply(AbstractStatisticalApexRule.java:31)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:336)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:499)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:184)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Code Sample demonstrating the issue:**

```
public class SomeClass {

    /**
     * Comment
     */
    public void doSomething() {
    	System.debug("hello world");
    }

}
```

**Running PMD through:** *CLI*

Windows 10
java version "1.8.0_181"

**Comment by rsoesemann** [comment]
@jeffhube can this be a problem introduced by you pull request #1314?

**Comment by JeffMTI** [comment]
Adding my details from the other Issue here for tracking:
CLI on
Ubuntu 18.04.1
Java 1.8.0_171

**Comment by jeffhube** [comment]
So the reason I brought up changing the visitor here is because it seems that the rules fail because while visit(ApexNode<?>, Object) used to be called for every node, that is not the case now, since ASTFormalComment is not an ApexNode<?>. One way to work around that is to implement visit(ASTFormalComment, Object) as I had for AbstractNcssCountRule, but I am thinking that we may be better off getting back to having a visit method that is called for every node, which would be visit(AbstractApexNodeBase, Object), and then AbstractNcssCountRule and ExcessiveNodeCountRule would override that instead of visit(ApexNode<?>, Object), and the override of visit(ASTFormalComment, Object) that I added would be removed.

The options I see for doing so would be:

1. Change all visit() methods in AbstractApexRule to delegate to visit(AbstractApexNodeBase, Object).  Replace all former usages of visit(ApexNode<?>, Object) with visit(AbstractApexNodeBase), since the former will no longer be invoked for every node. At this point we might as well remove visit(ApexNode<?>, Object) from AbstractApexRule and the visitor interface entirely.

2. Change only visit(ApexNode<?>, Object> to delegate to visit(AbstractApexNodeBase, Object). Then ApexNode<?> would still be called for every node other than ASTFormalComment, and AbstractApexNodeBase would be called for every node. Then update AbstractNcssCountRule and ExcessiveNodeCountRule to override visit for AbstractApexNodeBase instead of ApexNode<?>.

Regardless, feel free to just take my changes and integrate them as you see fit.

Thanks,
Jeff

**Comment by adangel** [comment]
Thanks for your suggestions.

Option 1 is almost possible as you described it: it would change the implementation of the visitor in AbstractApexRule. If we directly delegate to visit(AbstractApexNodeBase), we can reduce the stack size (in comparison to delegate to visit(ApexNode<?>) which delegates then to visit(AbstractApexNodeBase)).
Removing visit(ApexNode<?>) should not be done, but we can deprecate it and mark it for removal for PMD 7.0.0. Unless there is a usecase to visit only all nodes except for ASTFormalComments....

For you 2 option: I think, changing AbstractNcssCountRule and ExcessiveNodeCountRule should be changed to override visit(AbstractApexNodeBase) in any case...

> Regardless, feel free to just take my changes and integrate them as you see fit.
Will do, thanks again!
