### ISSUE TITLE
[java] Intermittent PMD failure : PMD processing errors while no violations reported

### ISSUE THREAD

**Issue by avivmu** [pmd/pmd#1460]
PMD Version: 6.8.0

Description: This is an intermittent bug not happening all the time, see attached log
Running PMD through: Maven

> [DEBUG] Executing PMD...
> Nov 13, 2018 12:32:32 PM net.sourceforge.pmd.cache.AbstractAnalysisCache checkValidity
> INFO: Analysis cache invalidated, rulesets changed.
> Nov 13, 2018 12:32:32 PM net.sourceforge.pmd.cache.AbstractAnalysisCache checkValidity
> INFO: Analysis cache invalidated, execution classpath changed.
> Nov 13, 2018 12:32:36 PM net.sourceforge.pmd.cache.FileAnalysisCache persist
> INFO: Analysis cache updated
> [DEBUG] PMD finished. Found 0 violations.
> [ERROR] PMD processing errors:
> [ERROR] /var/lib/jenkins/workspace/C-B4-Project-Feature-Tests/jdk/JDK8/label/integrationA/analytics/c-analytics-engine-dal-object/src/main/java/com/cb4/dal/object/dynamic/AbstractDataCell.java: Error while processing /var/lib/jenkins/workspace/C-B4-Project-Feature-Tests/jdk/JDK8/label/integrationA/analytics/c-analytics-engine-dal-object/src/main/java/com/cb4/dal/object/dynamic/AbstractDataCell.java
> net.sourceforge.pmd.PMDException: Error while processing /var/lib/jenkins/workspace/C-B4-Project-Feature-Tests/jdk/JDK8/label/integrationA/analytics/c-analytics-engine-dal-object/src/main/java/com/cb4/dal/object/dynamic/AbstractDataCell.java
>         at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:102)
>         at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
>         at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
>         at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
>         at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1827)
>         at java.util.HashMap$TreeNode.treeify(HashMap.java:1944)
>         at java.util.HashMap.treeifyBin(HashMap.java:771)
>         at java.util.HashMap.putVal(HashMap.java:643)
>         at java.util.HashMap.put(HashMap.java:611)
>         at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinition.forClass(JavaTypeDefinition.java:79)
>         at net.sourceforge.pmd.lang.java.ast.AbstractAnyTypeDeclaration.setQualifiedName(AbstractAnyTypeDeclaration.java:85)
>         at net.sourceforge.pmd.lang.java.qname.QualifiedNameResolver.visit(QualifiedNameResolver.java:212)
>         at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorReducedAdapter.visit(JavaParserVisitorReducedAdapter.java:16)
>         at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceDeclaration.jjtAccept(ASTClassOrInterfaceDeclaration.java:55)
>         at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
>         at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:11)
>         at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:206)
>         at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept(ASTTypeDeclaration.java:37)
>         at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
>         at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:11)
>         at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:181)
>         at net.sourceforge.pmd.lang.java.qname.QualifiedNameResolver.visit(QualifiedNameResolver.java:134)
>         at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:41)
>         at net.sourceforge.pmd.lang.java.qname.QualifiedNameResolver.initializeWith(QualifiedNameResolver.java:118)
>         at net.sourceforge.pmd.lang.java.AbstractJavaHandler$8.start(AbstractJavaHandler.java:140)
>         at net.sourceforge.pmd.SourceCodeProcessor.resolveQualifiedNames(SourceCodeProcessor.java:125)
> 
>

**Comment by jsotuyod** [comment]
@avivmu thanks for the report! Indeed, we have a concurrency error on

https://github.com/pmd/pmd/blob/1d652fc81cfe3d380b5a586f8ea3539fafa42136/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinition.java#L20

I'll change the `HashMap` to `ConcurrentHashMap` for 6.10.0 and it should work just fine.
