### ISSUE TITLE
[java] Possible Data Race in JavaTypeDefinitionSimple.getGenericType

### ISSUE THREAD

**Issue by rblasch** [pmd/pmd#1691]
I am seeing this issue with PMD 6.11.0, using Java 8. It happens _sometimes_ on our CI server, but I was unable to reproduce it consistently for now.

PMD is configured to use 8 threads on an 8 cores machine.

Here's the relevant part from a stack trace.

```
net.sourceforge.pmd.PMDException: Error while processing
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:102)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
    at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
    at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
    ...
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at java.util.ArrayList.add(ArrayList.java:463)
    at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.getGenericType(JavaTypeDefinitionSimple.java:138)
    at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.getGenericType(JavaTypeDefinitionSimple.java:107)
    at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.getGenericType(JavaTypeDefinitionSimple.java:97)
    at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.resolveTypeDefinition(JavaTypeDefinitionSimple.java:183)
    at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.resolveTypeDefinition(JavaTypeDefinitionSimple.java:177)
    at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.resolveTypeDefinition(JavaTypeDefinitionSimple.java:157)
    at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.getApplicableMethods(MethodTypeResolution.java:481)
    at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:387)
    at net.sourceforge.pmd.lang.java.ast.ASTName.jjtAccept(ASTName.java:35)
    ...
```

Maybe this is a data race in the lazy initialization of a `JavaTypeDefinitionSimple.genericArgs`?

**Comment by jsotuyod** [comment]
@rblasch thanks for the report. I confirm the generic types list in `JavaTypeDefinitionSimple` is subject to race conditions if 2 threads try to populate their members at the same time (which can happen as `JavaTypeDefinition` instances are created only once per class and memoized.

This can probably be fixed by simply synchronizing the list for the part of `getGenericType` that actually modifies the list:

https://github.com/pmd/pmd/blob/c26cbe1a279a97ba0a87c9fbbff09f4dcec18dc8/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java#L136-L151

The first part that reads the list is safe, as the list can grow, but never be shrank.

I wonder however if there is a scenario were this can lead to a dead-lock (ie: type definition 1 needs to use type definition 2 to resolve and viceversa, and having 2 threads start the resolution process from each of those 2 separately).

If there was, due to the recursive nature, we would end up resolving `Object.class` once we find the loop, but we need to make sure the locking is not a problem here.

**Comment by rblasch** [comment]
Not directly related to the data race, but this lazy initialization is fragile in another way too. Consider this example.

```java
        JavaTypeDefinition javaTypeDefinition = JavaTypeDefinition.forClass(ArrayList.class);
        System.out.println("Java type definition: " + javaTypeDefinition);
        System.out.println("    isGeneric: " + javaTypeDefinition.isGeneric());
        System.out.println("    getTypeParameterCount: " + javaTypeDefinition.getTypeParameterCount());
        System.out.println("    getGenericType(0): " + javaTypeDefinition.getGenericType(0));
        System.out.println("Java type definition: " + javaTypeDefinition);
        System.out.println("    isGeneric: " + javaTypeDefinition.isGeneric());
```

The output is as follows.

```
Java type definition: JavaTypeDefinition [clazz=class java.util.ArrayList, definitionType=EXACT, genericArgs=[], isGeneric=true]
    isGeneric: false
    getTypeParameterCount: 1
    getGenericType(0): JavaTypeDefinition [clazz=class java.lang.Object, definitionType=EXACT, genericArgs=[], isGeneric=false]

Java type definition: JavaTypeDefinition [clazz=class java.util.ArrayList, definitionType=EXACT, genericArgs=[JavaTypeDefinition [clazz=class java.lang.Object, definitionType=EXACT, isGeneric=false] ], isGeneric=true]
    isGeneric: true
```

Note that in the first "Java type definition" line, it says `isGeneric=true` but `genericArgs=[]`.
Also, calling `isGeneric` returns `false`.
Calling `getGenericType(0)` forces the lazy resolution, and returns the proper type.
Note how the `toString` and `isGeneric` change after this.

I don't really know the implementation, but would filling `genericArgs` with `null` values early alleviate both problems? Something like so in the `JavaTypeSimple` constructor?

```java
            // Generics will be lazily loaded
            this.genericArgs = new ArrayList<>(typeParameters.length);
            // boundGenerics would be empty if this is a raw type, hence the lazy loading
            Collections.addAll(this.genericArgs, boundGenerics);
            for (int i = this.genericArgs.size(); i < typeParameters.length; i++) {
                genericArgs.add(null);
            }
```

**Comment by jsotuyod** [comment]
@rblasch thanks for the insight.

The empty `genericArgs` in `toString` is not a problem, as it's a tool for debugging / understanding the internal state, and the actual contents of that string is not a "public API" (meaning, it's not documented / intended to be parsed in any way at runtime).

However, getting inconsistent results when calling `isGeneric()` is definitely a bug. The presetting would help on this case, but only in hiding the issue, as obviously `toString` and `isGeneric` use different logic to determine that flag (with `toString` being correct).

The race conditions would still happen with filling the list with nulls early, but only as inconsistent results (finding `Object.class` instead of the actual type being computed) instead of the current `ArrayIndexOutOfBoundsException`.
