### ISSUE TITLE
[pslql] ParseException when parsing ELSIF

### ISSUE THREAD

**Issue by fsapatin** [pmd/pmd#1731]
**Affects PMD Version:** 6.12.0

**Description:**
I’m trying to test PMD with PLSQL and I’m getting an error when parsing  <IF> <THEN> <ELSIF> <ELSE> <ENDIF>

When I use IF whitout ELSIF it works fine but when I use it i got an exception.

<details>
  <summary>Exception stacktrace</summary>
  <p>

```
net.sourceforge.pmd.PMDException: Error while parsing C:\sapatin\pmd-bin-6.12.0\update_planned_hrs.sql
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:99)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: net.sourceforge.pmd.lang.plsql.ast.ParseException: Encountered " <UNSIGNED_NUMERIC_LITERAL> "2 "" at line 15, column 11.
...
```

</p>
</details>

**Code Sample demonstrating the issue:**

```
CREATE OR REPLACE PACKAGE BODY update_planned_hrs
IS

FUNCTION existing_planned (p_emp_id IN NUMBER, p_project_id IN NUMBER) RETURN NUMBER

IS

existing_hours NUMBER(4);

BEGIN
   IF  1 = 1   THEN
    
     null;
     
   ELSIF 2 = 2  THEN
     null;
   ELSE
     null;
     
   END IF;


   RETURN (existing_hours);

   EXCEPTION
          WHEN OTHERS THEN NULL;

   END existing_planned;
   

END update_planned_hrs;
/
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Running from command line with JDK 11.
`pmd -d C:\pmd-bin-6.12.0\test -l plsql -R rulesets/plsql/TomKytesDespair.xml -f xml`

**Comment by adangel** [comment]
We have a choice conflict in the parser in IfStatement:

```
   [javacc] Warning: Choice conflict in (...)+ construct at line 2283, column 34.
   [javacc]          Expansion nested within construct and expansion following construct
   [javacc]          have common prefixes, one of which is: "ELSIF"
   [javacc]          Consider using a lookahead of 2 or more for nested expansion.
```
