### ISSUE TITLE
[CPD]Comments in JavaScript are being considered when using CPD

### ISSUE THREAD

**Issue by iccen8** [pmd/pmd#1756]
**Affects PMD Version:** 
6.13.0
[CPD]

**Description:**
Comments are counted as duplicated tokens in JS, while Java is not having this problem.

**Code Sample demonstrating the issue:**
Command I ran:
```
cpd.bat --minimum-tokens 50 --files . --language js --format xml --encoding UTF-8 > cpd_test.xml
```
Report I got:
```
   <duplication lines="13" tokens="123">
      <file end_line="13" line="1"
            path="C:\Users\iccen\Documents\test\src\core.js"/>
      <file end_line="13" line="1"
            path="C:\Users\iccen\Documents\test\src\element.js"/>
      <file end_line="13" line="1"
            path="C:\Users\iccen\Documents\test\src\lib\plugin.js"/>
      <file end_line="13" line="1"
            path="C:\Users\iccen\Documents\test\src\log\default.js"/>
      <codefragment><![CDATA[/*
Here are the duplicated file headers [snippet]...

headers...

headers...
*/

/**
 * Test core class]]></codefragment>
   </duplication>
```
```
   <duplication lines="1" tokens="67">
      <file end_line="108" line="108"
            path="C:\Users\iccen\Documents\test\src\element\node_view.js"/>
      <file end_line="108" line="108"
            path="C:\Users\iccen\Documents\test\src\element\node_view.js"/>
      <file end_line="110" line="110"
            path="C:\Users\iccen\Documents\test\src\element\node_view.js"/>
      <codefragment><![CDATA[/********************************************************************]]></codefragment>
   </duplication>
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by iccen8** [comment]
Just found out python's file header does have the same problem.
```
<codefragment><![CDATA["""
Here are the duplicated file headers [snippet]...

headers...

headers...
""" # noqa

from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):
   </duplication>
```

And its source code is:
```
# -*- coding: utf-8 -*-
"""
Here are the duplicated file headers [snippet]...

headers...

headers...
""" # noqa


from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):
```

**Comment by iccen8** [comment]
I just found out the argument I am using is incorrect: `--language js`
I am using `--language ecmascript` instead for javascript, and it turns out: 
```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file C:\Users\iccen\Documents\test\packages\cli\bin\test_js.js at line 1, column 1.  Encountered: "#" (35), after : ""
        at net.sourceforge.pmd.lang.ecmascript5.ast.Ecmascript5ParserTokenManager.getNextToken(Ecmascript5ParserTokenManager.java:5618)
        at net.sourceforge.pmd.lang.ecmascript5.Ecmascript5TokenManager.getNextToken(Ecmascript5TokenManager.java:31)
        at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:30)
        at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:37)
        at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
        at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```

Following is the source code:
```
#!/usr/bin/env node      //line 1

/* !
Here are the duplicated file headers [snippet]...

headers...

headers...
 */
```

**Comment by jsotuyod** [comment]
Strictly speaking, the shebang is a Unix cli feature. It's the shell that parses the file looking for it when used as an executable.

Loading the js in a browser, or importing the file from another python script would fail with equivalent syntax errors.

Nonetheless, I understand the need, and this sounds like something we could support a cross all languages at the source reader level...

I'll keep this open to track the request.

**Comment by iccen8** [comment]
And some unicodes are not supported either :/
```
pc_multi_proj_test_dupc/JAVA/matrix/matrix/matrix-android/matrix-io-canary/src/main/cpp/core/io_info_collector.cc at line 82, column 35.  Encountered: "\u03bc" (956), after : ""
        at net.sourceforge.pmd.lang.cpp.ast.CppParserTokenManager.getNextToken(CppParserTokenManager.java:1837)
        at net.sourceforge.pmd.lang.cpp.CppTokenManager.getNextToken(CppTokenManager.java:30)
        at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:30)
        at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:40)
        at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
        at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```

**Comment by iccen8** [comment]
Will special characters be supported some day?  I've encountered these errors couple times already when my testing code includes "utf-8" encoding characters such as "μ" and some Chinese characters.

**Comment by jsotuyod** [comment]
I'm moving the unicode discussion to a new issue (#1757) so we can follow it there.

**Comment by adangel** [comment]
> Hashbang comments were officially added to ECMAScript in the [2023 specification](https://tc39.es/ecma262/2023/#sec-hashbang) ([the original proposal](https://github.com/tc39/proposal-hashbang))

(by @aarongoldenthal at https://github.com/pmd/pmd/issues/4580#issuecomment-1567509014)
