### ISSUE TITLE
[cpp] Support unicode characters

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1757]
And some unicodes are not supported:

```
pc_multi_proj_test_dupc/JAVA/matrix/matrix/matrix-android/matrix-io-canary/src/main/cpp/core/io_info_collector.cc at line 82, column 35.  Encountered: "\u03bc" (956), after : ""
        at net.sourceforge.pmd.lang.cpp.ast.CppParserTokenManager.getNextToken(CppParserTokenManager.java:1837)
        at net.sourceforge.pmd.lang.cpp.CppTokenManager.getNextToken(CppTokenManager.java:30)
        at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:30)
        at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:40)
        at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
        at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```

_Originally posted by @iccen8 in https://github.com/pmd/pmd/issues/1756#issuecomment-479473944_

@iccen8 could you provide a failing code snippet?

**Comment by iccen8** [comment]
```
        if (info_map_.find(fd) == info_map_.end()) {
            //__android_log_print(ANDROID_LOG_DEBUG, kTag, "OnClose fd:%d not in info_map_", fd);
            return nullptr;
        }

        info_map_[fd]->total_cost_μs_ = GetSysTimeMicros() - info_map_[fd]->start_time_μs_;   ------line:82
        info_map_[fd]->file_size_ = GetFileSize(info_map_[fd]->path_.c_str());
        std::shared_ptr<IOInfo> info = info_map_[fd];
        info_map_.erase(fd);
```

**Comment by iccen8** [comment]
Python:
```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file C:\Users\iccen\Documents\TestOnly\test_unicode\.\py_test.py at line 23, column 16.  Encountered: "\u03bc" (956), after : ""
        at net.sourceforge.pmd.lang.python.ast.PythonParserTokenManager.getNextToken(PythonParserTokenManager.java:3763)
        at net.sourceforge.pmd.lang.python.PythonTokenManager.getNextToken(PythonTokenManager.java:31)
        at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:30)
        at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:40)
        at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
        at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```
Code snippet:
```
def check():
    total_cost_μs = []    ------line: 23
```

**Comment by iccen8** [comment]
JavaScript:
```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file C:\Users\iccen\Documents\TestOnly\test_unicode\.\index.js at line 29, column 45.  Encountered: "\u4f60" (20320), after : ""
        at net.sourceforge.pmd.lang.ecmascript5.ast.Ecmascript5ParserTokenManager.getNextToken(Ecmascript5ParserTokenManager.java:5618)
        at net.sourceforge.pmd.lang.ecmascript5.Ecmascript5TokenManager.getNextToken(Ecmascript5TokenManager.java:31)
        at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:30)
        at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:40)
        at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
        at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```
Code snippet:
```
import { Test, define } from 'test2'

define('element', class extends Test {
  a = 1

  data = {
    arr: ['item1', 'item2']
  }

  clickHandler = () => {
    console.log('clicked' + this.a)

    this.data.arr[0] = Math.random()
    this.data.arr[1] = Math.random()
    this.update()
  }

  install(){
    this.data.newMsg = this.props.msg + " new"
  }

  render() {
    const { msg } = this.props
    const { arr, newMsg } = this.data
    return (
      <view>
        <view>Hello, {msg}!</view>
        <view>Hello, {newMsg}</view>
        <button onClick={this.clickHandler}>你好</button>    ------line:29
        <view>{arr[0]}</view>
        <view>{arr[1]}</view>
      </view>
    )
  }
})
```

**Comment by iccen8** [comment]
The errors above are the problems I encountered so far. I've tested java, go, c# and php as well, and they ran well.

**Comment by fanlw0816** [comment]
I encountered the same problems and how can I avoid or ignore these problems so that CPD doesn't stop.
#1756

```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file ./django/contrib/gis/templates/gis/google/google-single.js at line 2, column 18.  Encountered: "#" (35), after : ""
	at net.sourceforge.pmd.lang.ecmascript5.ast.Ecmascript5ParserTokenManager.getNextToken(Ecmascript5ParserTokenManager.java:5618)
	at net.sourceforge.pmd.lang.ecmascript5.Ecmascript5TokenManager.getNextToken(Ecmascript5TokenManager.java:31)
	at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:30)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:40)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```


```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file ./ueditor/neditor.all.min.js at line 9, column 22346.  Encountered: "w" (119), after : "\\"
	at net.sourceforge.pmd.lang.ecmascript5.ast.Ecmascript5ParserTokenManager.getNextToken(Ecmascript5ParserTokenManager.java:5618)
	at net.sourceforge.pmd.lang.ecmascript5.Ecmascript5TokenManager.getNextToken(Ecmascript5TokenManager.java:31)
	at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:30)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:40)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```

```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file ./qs/test/parse.js at line 544, column 15.  Encountered: "\u770c" (30476), after : ""
	at net.sourceforge.pmd.lang.ecmascript5.ast.Ecmascript5ParserTokenManager.getNextToken(Ecmascript5ParserTokenManager.java:5618)
	at net.sourceforge.pmd.lang.ecmascript5.Ecmascript5TokenManager.getNextToken(Ecmascript5TokenManager.java:31)
	at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:30)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:40)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```
