### ISSUE TITLE
[core]CPD: Exception thrown java.lang.OutOfMemoryError:Java heap space

### ISSUE THREAD

**Issue by iccengan** [pmd/pmd#1818]
**Affects PMD Version:** 
6.13.0

**Rule:**
`cpd.bat --minimum-tokens 100 --files . --language cpp --format xml --encoding utf-8 --skip-lexical-errors> cpd_test.xml`

**Description:**
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
        at java.base/java.util.ArrayList.toArray(ArrayList.java:400)
        at java.base/java.util.ArrayList.<init>(ArrayList.java:179)
        at net.sourceforge.pmd.cpd.TokenEntry$State.<init>(TokenEntry.java:77)
        at net.sourceforge.pmd.cpd.CPD.addAndSkipLexicalErrors(CPD.java:148)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:135)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:133)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:113)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:86)
        at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```

My java version is 1.8.0_121. 
Referring to #1753, I've tried java 11.0.2 as well, but the same problem occurs.
Total file number of my project: 35600

Referring to #1417, I ran the following command:
```
$ java -XX:+PrintFlagsFinal -version \| grep HeapSize
uintx ErgoHeapSizeLimit                         = 0
         {product}
uintx HeapSizePerGCThread                       = 87241520
         {product}
uintx InitialHeapSize                          := 268435456
         {product}
uintx LargePageHeapSizeThreshold                = 134217728
         {product}
uintx MaxHeapSize                              := 4263510016
{product}
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
--
```
```
$ java -XX:+PrintFlagsFinal -version \| grep HeapSize
size_t ErgoHeapSizeLimit                        = 0
         {product} {default}
size_t HeapSizePerGCThread                      = 43620760
         {product} {default}
size_t InitialHeapSize                          = 268435456
         {product} {ergonomic}
size_t LargePageHeapSizeThreshold               = 134217728
         {product} {default}
size_t MaxHeapSize                              = 4263510016
         {product} {ergonomic}
uintx NonNMethodCodeHeapSize                   = 5835340
         {pd product} {ergonomic}
uintx NonProfiledCodeHeapSize                  = 122911450
         {pd product} {ergonomic}
uintx ProfiledCodeHeapSize                     = 122911450
         {pd product} {ergonomic}
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
--
```

**Comment by jsotuyod** [comment]
Since PMD 6.37.0 and later CPD no longer creates new copies of the token list as it processes heavily reducing the memory footprint.
This issue should no longer be reproducible, at the very least not with the same stacktrace.
