### ISSUE TITLE
[java] Regression in MethodReturnsInternalArray not handling enums

### ISSUE THREAD

**Issue by KroArtem** [pmd/pmd#1845]
**Affects PMD Version:** 
6.15
**Rule:**
[MethodReturnsInternalArray](https://pmd.github.io/pmd-6.15.0/pmd_rules_java_bestpractices.html#methodreturnsinternalarray)
**Description:**
It seems like https://github.com/pmd/pmd/pull/1799 breaks the rule for enums
**Code Sample demonstrating the issue:**

Consider I have the following enum:

```
package com.ourapp.constants.forms;

import java.util.Arrays;
public enum OptionConditionsMenu {
    REDIRECT(Constants.REDIRECT),

    CONTINUE_TO_NEXT_PAGE(Constants.REDIRECT, "Continue to next page"),
    GO_TO_PAGE(Constants.REDIRECT, "Go to page %d"),

    private String[] titles;

    OptionConditionsMenu(String... titles) {
        this.titles = Arrays.copyOf(titles, titles.length);
    }

    public String[] getTitles() {
        return titles.clone();
    }

    @Override
    public String toString() {
        return titles[0];
    }

    private static class Constants {
        static final String REDIRECT = "Redirect";
    }

}
```

I've reduced it a bit just not to be that big. When PMD checks this file, it shows the following warning:
```
May 26, 2019 8:30:59 PM net.sourceforge.pmd.RuleSet apply
WARNING: Exception applying rule MethodReturnsInternalArray on file /directory/com/ourapp/constants/forms/OptionConditionsMenu.java, continuing with next rule
java.lang.NullPointerException
	at net.sourceforge.pmd.lang.java.rule.bestpractices.AbstractSunSecureRule.isField(AbstractSunSecureRule.java:42)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.MethodReturnsInternalArrayRule.visit(MethodReturnsInternalArrayRule.java:52)
	at net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration.jjtAccept(ASTMethodDeclaration.java:33)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:130)
	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBodyDeclaration.jjtAccept(ASTClassOrInterfaceBodyDeclaration.java:43)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:135)
	at net.sourceforge.pmd.lang.java.ast.ASTEnumBody.jjtAccept(ASTEnumBody.java:22)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:260)
	at net.sourceforge.pmd.lang.java.ast.ASTEnumDeclaration.jjtAccept(ASTEnumDeclaration.java:23)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:280)
	at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept(ASTTypeDeclaration.java:37)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:255)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:39)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:27)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:336)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:499)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:184)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I believe the source of the problem is that in `MethodReturnsInternalArrayRule:49` there is this line of code:

```ASTClassOrInterfaceDeclaration td = method.getFirstParentOfType(ASTClassOrInterfaceDeclaration.class);```

This one becomes null as it's a enum and this check fails:
```            if (!isField(vn, td)) {```

**Running PMD through:** *[Other]*

**Comment by adangel** [comment]
Steps to fix this issue:
* [ ] Reproduce this in a test case (see [MethodReturnsInternalArray.xml](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MethodReturnsInternalArray.xml) and [MethodReturnsInternalArrayTest.java](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MethodReturnsInternalArrayTest.java))
* [ ] Fix this Nullpointer (in [AbstractSunSecureRule.java](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AbstractSunSecureRule.java))
* [ ] Verify if there are other users than MethodReturnsInternalArray that make use of the method `AbstractSunSecureRule.isField()` and check whether we have a similar problem there
* [ ] Verify if we have a similar problem with interfaces or annotations (like with enums) or with inner classes (annoations, interfaces, enums).
