### ISSUE TITLE
[java] Parser exception for parameterized constructor call

### ISSUE THREAD

**Issue by logesh14** [pmd/pmd#2119]
**Affects PMD Version:** 
So far tested in pmd versions greater than 6.11.0
**Rule:**
CloseResource
**Description:**
We have been using pmd for our codechecks. while instantiating a ArrayList object with specific syntax:

```java
jukebox(new <Long>ArrayList(test));
```
pmd throws parser exception and I hope it is syntactically right statement. But anyhow if i write the statement as:

```java
jukebox(new ArrayList<Long>(test));
```
parser generates tree without any error. 

Detailed Exception:

```
net.sourceforge.pmd.lang.java.ast.ParseException: Encountered " "<" "< "" at line 4, column 29.
Was expecting one of:
    <IDENTIFIER> ...
    "@" ...
    "@" ...
    "@" ...
    "@" ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    
	at net.sourceforge.pmd.lang.java.ast.JavaParser.generateParseException(JavaParser.java:11937)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.jj_consume_token(JavaParser.java:11821)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.AllocationExpression(JavaParser.java:4654)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.PrimaryPrefix(JavaParser.java:3918)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.PrimaryExpression(JavaParser.java:3731)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.PostfixExpression(JavaParser.java:3593)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.UnaryExpressionNotPlusMinus(JavaParser.java:3555)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.UnaryExpression(JavaParser.java:3408)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.MultiplicativeExpression(JavaParser.java:3302)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.AdditiveExpression(JavaParser.java:3249)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ShiftExpression(JavaParser.java:3192)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.RelationalExpression(JavaParser.java:3131)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.InstanceOfExpression(JavaParser.java:3095)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.EqualityExpression(JavaParser.java:3042)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.AndExpression(JavaParser.java:3002)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ExclusiveOrExpression(JavaParser.java:2962)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.InclusiveOrExpression(JavaParser.java:2922)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ConditionalAndExpression(JavaParser.java:2882)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ConditionalOrExpression(JavaParser.java:2842)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ConditionalExpression(JavaParser.java:2804)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Expression(JavaParser.java:2661)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ArgumentList(JavaParser.java:4561)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Arguments(JavaParser.java:4525)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.PrimarySuffix(JavaParser.java:4330)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.PrimaryExpression(JavaParser.java:3739)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.PostfixExpression(JavaParser.java:3593)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.StatementExpression(JavaParser.java:5171)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Statement(JavaParser.java:4820)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.BlockStatement(JavaParser.java:4974)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Block(JavaParser.java:4932)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.MethodDeclaration(JavaParser.java:1615)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBodyDeclaration(JavaParser.java:1239)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBody(JavaParser.java:1194)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceDeclaration(JavaParser.java:650)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.TypeDeclaration(JavaParser.java:539)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.CompilationUnit(JavaParser.java:276)
	at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:59)
	at net.sourceforge.pmd.util.fxdesigner.model.ASTManager.updateIfChanged(ASTManager.java:93)
	at net.sourceforge.pmd.util.fxdesigner.SourceEditorController.refreshAST(SourceEditorController.java:212)
	at net.sourceforge.pmd.util.fxdesigner.MainDesignerController.refreshAST(MainDesignerController.java:196)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)


```
**Code Sample demonstrating the issue:**

Error snippet:

```java
public class test {
	public static void main(String a[]){
		Vector<Long> test = null;
		jukebox(new <Long>ArrayList(test));
	}
	private static void jukebox(ArrayList<Long> arrayList) {

	}
}
```

Java Enivronment:
```
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)

```
Issue  also persists in java 1.8( tested in openjdk, zulu jdk and as well as SE).
 
Any help is appreciated!

**Running PMD through:** *[CLI | Designer]*

**Comment by adangel** [comment]
@logesh14 Thanks for reporting this. There are two points:

1. The parser error will be fixed with PMD 7. It is actually valid syntax and shouldn't crash PMD. However, it is very rarely used. Therefore we probably won't backport the fix (for PMD 7, there are more change to the parser planned)

2. You example is not apply to the problem...
Please note, that `new <Long>ArrayList(test)` is **not** the same as `new ArrayList<Long>(test)`. The two type arguments serve different purposes:
* The first is a type argument to the constructor. However, the constructor of ArrayList has no generic type. The generic type is on the class. This means, you are actually creating a raw array list: `new ArrayList(test)`. Eclipse even warns me:
    
    * ArrayList is a raw type. References to generic type ArrayList&lt;E&gt; should be parameterized
    * Type safety: The constructor ArrayList(Collection) belongs to the raw type ArrayList. References to generic type ArrayList&lt;E&gt; should be parameterized
    * Type safety: The expression of type ArrayList needs unchecked conversion to conform to ArrayList&lt;Long&gt;
    
    If I change it to `new <Long>ArrayList<Long>(test)`, then I get the warning "Unused type arguments for the non generic constructor ArrayList&lt;Long&gt;(Collection&lt;? extends Long&gt;) of type ArrayList&lt;Long&gt; it should not be parameterized with arguments &lt;Long&gt;"
* The second is the type argument for the class - since the whole class ArrayList is parameterized.


A example for a parameterized constructor would look like this:

```java
    public class Issue2119Test {
        private Long l;
        public <E extends Number> Issue2119Test(E data) {
            l = data.longValue(); 
        }
        public long get() {
            return l;
        }

        public static void main(String[] args) {
            Issue2119Test test = new <Long>Issue2119Test(1L);
            System.out.println(test.get());
        }
    }
```

Therefore I'm going to close this issue.

**Comment by adangel** [comment]
This will be fixed with PMD 7.
The grammar has been fixed on the branch "java-grammar": https://github.com/pmd/pmd/blob/c0d9538144f62d76710b0bcbb65084861264d468/pmd-java/etc/grammar/Java.jjt#L2816-L2831
