### ISSUE TITLE
[java] Ant: Facing issues while upgrading PMD 5.x to 6.x

### ISSUE THREAD

**Issue by SyedThoufich** [pmd/pmd#2122]
Hi Team,

I am trying to upgrade PMD to the latest version from verion 5.x to 6.19.0

I have added the related jars in the pmd classpath through ANT
below is my build.xml sample:

``` xml
<property name="pmd.dir" value="${thirdParty.dir}" />
	<path id="pmd.classpath">
		<fileset dir="${pmd.dir}">
			<include name="jaxen*.jar" />
			<include name="pmd*.jar" />
			<include name="asm*.jar" />
			<include name="jaxen*.jar" />
			<include name="pmd*.jar" />
			<include name="asm*.jar" />
			<include name="aopall*.jar" />
			<include name="cglib*.jar" />
			<include name="animal*.jar" />
			<include name="ant*.jar" />
			<include name="common*.jar" />
			<include name="fastparse*.jar" />
			<include name="gson*.jar" />
			<include name="javacc*.jar" />
			<include name="javax.inject*.jar" />
			<include name="jcommander*.jar" />
			<include name="jline*.jar" />
			<include name="jol*.jar" />
			<include name="error*.jar" />
			<include name="lenses*.jar" />
			<include name="logback*.jar" />
			<include name="parsers*.jar" />
			<include name="rhino*.jar" />
			<include name="saxon-9*.jar" />
			<include name="scala*.jar" />
			<include name="slf4j-api*.jar" />
			<include name="trees*.jar" />
			<include name="sourcecode*.jar" />
			<include name="snake*.jar" />
			<include name="stringtemp*.jar" />
		</fileset>
	</path>

	<target name="pmd">
		<taskdef name="pmd" classname="net.sourceforge.pmd.ant.PMDTask" classpathref="pmd.classpath" />
		<pmd shortFilenames="true" failOnRuleViolation="true" 
               maxRuleViolations="${pmd.MaxRuleViolations}" 
                  rulesetfiles="pmd_basic_rule_set.xml">
			<formatter type="xml" toFile="pmd_report.xml"/>
			<fileset dir="${src.dir}">
				<include name="**/*.java"/>
			</fileset>
		</pmd>
```

the PMD is Configured in TeamCity , when i run the build , i am getting below error:

```
[pmd] pmd
[pmd] Error instantiating a rule
[pmd] java.lang.ClassNotFoundException: net.sourceforge.pmd.lang.java.rule.unnecessary.UnnecessaryConversionTemporaryRule
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1323)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1076)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.sourceforge.pmd.util.ResourceLoader.loadRuleFromClassPath(ResourceLoader.java:139)
	at net.sourceforge.pmd.rules.RuleBuilder.build(RuleBuilder.java:193)
	at net.sourceforge.pmd.rules.RuleFactory.buildRule(RuleFactory.java:208)
	at net.sourceforge.pmd.RuleSetFactory.parseSingleRuleNode(RuleSetFactory.java:597)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:493)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:398)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:220)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:215)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:176)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:160)
	at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:116)
	at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:275)
	at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:50)
        ...
9)
[pmd] java.lang.RuntimeException: java.lang.ClassNotFoundException: net.sourceforge.pmd.lang.java.rule.unnecessary.UnnecessaryConversionTemporaryRule
```

What am i missing...can anyone help me in this!!

**Comment by jsotuyod** [comment]
@SyedThoufich I'd like to ask for the contents of `pmd_basic_rule_set.xml`...

In PMD 6.0.0 we reorganized rules into categories, deprecating the old "rulesets". As part of this, rule implementations were moved around (ie: `net.sourceforge.pmd.lang.java.rule.unnecessary.UnnecessaryConversionTemporaryRule` is now `net.sourceforge.pmd.lang.java.rule.errorprone.UnnecessaryConversionTemporaryRule`).

The change was made so that it would be transparent for proper usages while logging a deprecation warning as this behavior will be dropped in PMD 7 (ie: people using `rulesets/java/unnecessary.xml` as their rulesets, or with custom rulesets referencing the old names). However, I believe your ruleset is not **referencing** the existing rules, but you are actually **defining a rule yourself**.

That is, instead of having your ruleset look like this:

```xml
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

  <!-- Reference to existing PMD rule -->
  <rule ref="rulesets/java/unnecessary.xml/UnnecessaryConversionTemporary" />
</ruleset>
```

I believe you did this:

```xml
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

  <!-- DEFINITION of a new rule -->
  <rule name="UnnecessaryConversionTemporary"
          since="0.1"
          message="Avoid unnecessary temporaries when converting primitives to Strings"
          class="net.sourceforge.pmd.lang.java.rule.unnecessary.UnnecessaryConversionTemporaryRule">
        <description>
Avoid the use temporary objects when converting primitives to Strings. Use the static conversion methods
on the wrapper classes instead.
        </description>
        <priority>3</priority>
        <example>
<![CDATA[
public String convert(int x) {
    String foo = new Integer(x).toString(); // this wastes an object
    return Integer.toString(x);             // preferred approach
}
]]>
        </example>
    </rule>
</ruleset>
```

This approach is incorrect, I would recommend you check out the documentation on writing and referencing PMD rules: https://pmd.github.io/pmd-6.19.0/pmd_userdocs_making_rulesets.html#referencing-a-single-rule

**Comment by SyedThoufich** [comment]
@jsotuyod Thank you , it worked for me after  i corrected the way of referencing  Rules as u suggested above!!
