### ISSUE TITLE
[scala] CPD terminates with an exception when a small value is set for --minimum-tokens

### ISSUE THREAD

**Issue by yasuharu-sato** [pmd/pmd#2153]
**Affects PMD Version:** 
6.18.0, 6.20.0

**Rule:**

**Description:**
When targeting a scala file, if a small value is set for --minimum-tokens, CPD will exit with an exception.

**Code Sample demonstrating the issue:**

```
object Foo {
    void foo() {
        String[] array = null;
        array = {"abc", "def", "ghi"};
    }
}
```
I prepared another same file.

**Running PMD through:** *[CLI]*
```
pmd-bin-6.18.0/bin/run.sh cpd --minimum-tokens 20 --language scala --files scala/
```

**Comment by jsotuyod** [comment]
@yasuharu-sato thanks for the report. Would you please submit the exception stacktrace you are seeing?

**Comment by yasuharu-sato** [comment]
Sure

```
java.lang.IndexOutOfBoundsException: fromIndex = -1
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:505)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1137)
	at net.sourceforge.pmd.cpd.SourceCode$CodeLoader.getCodeSlice(SourceCode.java:45)
	at net.sourceforge.pmd.cpd.SourceCode.getSlice(SourceCode.java:198)
	at net.sourceforge.pmd.cpd.Mark.getSourceCodeSlice(Mark.java:41)
	at net.sourceforge.pmd.cpd.Match.getSourceCodeSlice(Match.java:77)
	at net.sourceforge.pmd.cpd.XMLRenderer.addCodeSnippet(XMLRenderer.java:129)
	at net.sourceforge.pmd.cpd.XMLRenderer.render(XMLRenderer.java:109)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:94)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```
