### ISSUE TITLE
Rule Message Attribute cannot have {}

### ISSUE THREAD

**Issue by numeralnathan** [pmd/pmd#2226]
**Affects PMD Version:** 

6.20.0

**Rule:**

Custom rule

```
   <rule name="IfStatementBracesIfNotFollowedByControl"
         language="java"
         message="Please add {} after if statements unless followed by break, continue, return or throw"
         class="net.sourceforge.pmd.lang.rule.XPathRule">
      <description>It is recommended to use braces on 'if ... else' statements and loop statements, even if they are optional.  This usually makes the code clearer, and helps prepare the future when you need to add another statement.</description>   
      <priority>3</priority>
      <properties>
         <property name="xpath">
            <value>
               <![CDATA[
                  //IfStatement/Statement/*
                  [
                     not(self::Block) and 
                     not(self::BreakStatement) and 
                     not(self::ContinueStatement) and 
                     not(self::ReturnStatement) and 
                     not(self::ThrowStatement)
                  ]
               ]]>
            </value>
         </property>
      </properties>
      <example>
         <![CDATA[
				public class MyClass
				{
				   private void myMethod(Object parent)
				   {
				      if (parent == null)
				         return(result);                                            // No violation
				
				      while (true)
				      {
				         if (parent == null)
				            break;                                                  // No violation
				
				         if (parent == null)
				            continue;                                               // No violation
				      }
				
				      if (parent == null)
				         throw new IllegalStateException();                         // No violation
				
				      if (parent == null)
				         parent = "";                                               // Violation.  Must be surrounded by {}.
				   }
				}         
	      ]]>
      </example>
   </rule>
```

**Description:**

The `{}` in message causes PMD to throw an exception.  If I remove the `{}`, then PMD works.  Here is the exception.

```
Jan 15, 2020 9:50:34 AM net.sourceforge.pmd.lang.rule.AbstractRuleChainVisitor visitAll
WARNING: Exception applying rule IfStatementBracesIfNotFollowedByControl on file ...\MyFile.java, continuing with next rule
java.lang.IllegalArgumentException: can't parse argument number:
        at java.text.MessageFormat.makeFormat(Unknown Source)
        at java.text.MessageFormat.applyPattern(Unknown Source)
        at java.text.MessageFormat.<init>(Unknown Source)
        at java.text.MessageFormat.format(Unknown Source)
        at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.cleanup(AbstractRuleViolationFactory.java:26)
        at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.addViolation(AbstractRuleViolationFactory.java:35)
        at net.sourceforge.pmd.lang.rule.AbstractRule.addViolation(AbstractRule.java:359)
        at net.sourceforge.pmd.lang.rule.XPathRule.evaluate(XPathRule.java:118)
        at net.sourceforge.pmd.lang.java.rule.JavaRuleChainVisitor.visit(JavaRuleChainVisitor.java:42)
        at net.sourceforge.pmd.lang.rule.AbstractRuleChainVisitor.visitAll(AbstractRuleChainVisitor.java:96)
        at net.sourceforge.pmd.RuleChain.apply(RuleChain.java:67)
        at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:140)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:194)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:89)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        ... 24 more
```

**Running PMD through:**

CLI

If I run through Eclipse then PMD does not mark any violations and I am not sure where to find the exception.

**Comment by oowekyala** [comment]
You should escape those characters by enclosing them in single quotes.

**Comment by oowekyala** [comment]
Closing this is favour of #2227. Displaying braces is supported but they must be escaped as [MessageFormat](https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html) explains. This ought to be documented, which is part of the new issue mentions.

> Within a String, a pair of single quotes can be used to quote any arbitrary characters except single quotes. For example, pattern string "'{0}'" represents string "{0}", not a FormatElement. A single quote itself must be represented by doubled single quotes '' throughout a String. For example, pattern string "'{''}'" is interpreted as a sequence of '{ (start of quoting and a left curly brace), '' (a single quote), and }' (a right curly brace and end of quoting), not '{' and '}' (quoted left and right curly braces): representing string "{'}", not "{}".
