### ISSUE TITLE
[java] Java 14: Unsupported class file major version 58

### ISSUE THREAD

**Issue by markkolich** [pmd/pmd#2341]
PMD version: 6.21.0

I'm attempting to compile & run my stack with Java 14 (GA's on 3/17/20).

PMD is integrated into my Maven build as part of the `maven-pmd-plugin`, which fails at build time with the following exception:

```
/Users/mark/workspace/foobar/foobar-common-test/src/test/java/com/foobar/common/test/servlet/StubServletOutputStream.java: PMDException: Error while processing /Users/mark/workspace/foobar/foobar-common-test/src/test/java/com/foobar/common/test/servlet/StubServletOutputStream.java
net.sourceforge.pmd.PMDException: Error while processing /Users/mark/workspace/foobar/foobar-common-test/src/test/java/com/foobar/common/test/servlet/StubServletOutputStream.java
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:113)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:89)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 58
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283)
	at net.sourceforge.pmd.lang.java.typeresolution.PMDASMClassLoader.getImportedClasses(PMDASMClassLoader.java:110)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.populateClassName(ClassTypeResolver.java:1618)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:210)
	at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:44)
	at net.sourceforge.pmd.lang.java.typeresolution.TypeResolutionFacade.initializeWith(TypeResolutionFacade.java:21)
	at net.sourceforge.pmd.lang.java.AbstractJavaHandler$5.start(AbstractJavaHandler.java:118)
	at net.sourceforge.pmd.SourceCodeProcessor.usesTypeResolution(SourceCodeProcessor.java:163)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:190)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
	... 10 more
```

If the stack trace is any hint, I'm almost 100% certain this is because the version of `org.ow2.asm:asm` consumed by PMD is not (yet) compatible with Java 14:

https://github.com/pmd/pmd/blob/4749833534d03a120d184945b1480cb0f8746b8d/pom.xml#L624-L628

I figured I would submit this issue anyways in the event you need something to track Java 14 support. In parallel, I can also ping the maintainers of `org.ow2.asm:asm` if you'd like me to open an issue with them as well:

https://github.com/llbit/ow2-asm

**Comment by adangel** [comment]
Thanks for the report. Java 14 will be supported with the next PMD version 6.22.0 to be released next week. Java 14 issue: #2159 

asm 7.3.1 is used by PMD 6.22.0 (the current snapshot/master) and supports java 14. So, no need to create a issue there.

The problem is, that you are using PMD 6.21.0, which does not support java 14 and uses asm 7.1: https://github.com/pmd/pmd/blob/a28e9e22e5d51d8f6710a1d71e73be218a7cc1b3/pom.xml#L623-L627

If you want to test java 14, you either need to wait for PMD 6.22.0 and upgrade then (see https://maven.apache.org/plugins/maven-pmd-plugin/examples/upgrading-PMD-at-runtime.html) or test now with 6.22.0-SNAPSHOT: The binary distribution (aka commandline) is here: https://sourceforge.net/projects/pmd/files/pmd/6.22.0-SNAPSHOT/
If you want to use it via maven, you'll need to add the snapshot repository:

```xml
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```

Then you can simply use PMD `<version>6.22.0-SNAPSHOT</version>`.

```

**Comment by Guigzai** [comment]
Hi,

In my case, PMD is launched by org.sonarsource.scanner.maven.

How can I use PMD > 6.22.0.

I  try to use plugin dependency :
                        <dependency>
                          <groupId>net.sourceforge.pmd</groupId>
                          <artifactId>pmd-java</artifactId>
                          <version>6.26.0</version>
                        </dependency>
But not working :
[INFO] Sensor PmdSensor [pmd]
[INFO] Execute PMD 6.10.0
...
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 58

Thanks for help

**Comment by anydoby** [comment]
Maybe a bit late, but this works for me

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>3.13.0</version>
                <dependencies>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-core</artifactId>
                        <version>6.29.0</version>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-java</artifactId>
                        <version>6.29.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```
