### ISSUE TITLE
[java] Ivy does not resolve saxon classes

### ISSUE THREAD

**Issue by triskaj** [pmd/pmd#2489]
**Affects PMD Version:** 

6.23.0

**Description:**

When I use PMD in Ant and use Ivy to resolve classes, it does not resolve saxon classes, which are then missing on classpath during execution of PMD.

**Exception Stacktrace:**

```
test/build.xml:8: java.lang.NoClassDefFoundError: net/sf/saxon/trans/XPathException
        at net.sourceforge.pmd.lang.rule.XPathRule.initXPathRuleQuery(XPathRule.java:197)
        at net.sourceforge.pmd.lang.rule.XPathRule.getRuleChainVisits(XPathRule.java:217)
        at net.sourceforge.pmd.lang.rule.AbstractRule.isRuleChain(AbstractRule.java:310)
        at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.isRuleChain(AbstractDelegateRule.java:311)
        at net.sourceforge.pmd.lang.rule.AbstractRuleChainVisitor.initialize(AbstractRuleChainVisitor.java:158)
        at net.sourceforge.pmd.lang.rule.AbstractRuleChainVisitor.visitAll(AbstractRuleChainVisitor.java:63)
        at net.sourceforge.pmd.RuleChain.apply(RuleChain.java:67)
        at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:140)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:194)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:89)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
        at net.sourceforge.pmd.processor.MonoThreadProcessor.runAnalysis(MonoThreadProcessor.java:29)
        at net.sourceforge.pmd.processor.AbstractPMDProcessor.processFiles(AbstractPMDProcessor.java:122)
        at net.sourceforge.pmd.PMD.processFiles(PMD.java:310)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:196)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:281)
        at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:50)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
        at org.apache.tools.ant.Main.runBuild(Main.java:830)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.lang.ClassNotFoundException: net.sf.saxon.trans.XPathException
        at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1383)
        at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1338)
        at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1093)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 36 more
```

**Code Sample demonstrating the issue:**

[test.zip](https://github.com/pmd/pmd/files/4644081/test.zip)

**Steps to reproduce:**

1. `ant pmd`

**Running PMD through:** *Ant* with *Ivy*

**java version:**
```
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

**OS:**
```
ProductName:    Mac OS X
ProductVersion: 10.15.4
```

**Comment by oowekyala** [comment]
Did you get this to work?

It should actually be pulling both these dependencies: https://github.com/pmd/pmd/blob/0488c853e3c43936e3149a426287fd8683655d5b/pom.xml#L682-L692

but somehow pulls only the one with dom classifier. When I add add a dependency on the jar one explicitly in `ivy.xml` it works on my machine:
```xml
    <dependency org="net.sourceforge.saxon" name="saxon" rev="9.1.0.8" />
```

**Comment by oowekyala** [comment]
Closing, I'm assuming this is fixed
