### ISSUE TITLE
[C#] language parser error with backslashes in strings

### ISSUE THREAD

**Issue by mayerj** [pmd/pmd#2619]
Affects PMD Version: At least CPD 6.25.0

Description:

The following program triggers a parser failure:

`using System;

namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args)
		{
			TimeSpan duration = TimeSpan.FromMilliseconds(32342341);

			Console.WriteLine($@"{duration:hh\\:mm\\:ss\\.fff}");
		}
	}
}
`

**Exception Stacktrace:**
`
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file C:\repositories\ConsoleApp1\ConsoleApp1\Program.cs at line 11, column 63.  Encountered: token recognition error at: '\\'
        at net.sourceforge.pmd.cpd.AntlrTokenizer.tokenize(AntlrTokenizer.java:44)
        at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:144)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:139)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:108)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:70)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:80)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:65)
        at net.sourceforge.pmd.cpd.GUI.go(GUI.java:684)
        at net.sourceforge.pmd.cpd.GUI.access$500(GUI.java:71)
        at net.sourceforge.pmd.cpd.GUI$GoListener$1.run(GUI.java:248)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: LexerNoViableAltException('\')
        at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:312)
        at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:233)
        at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:117)
        at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
        at net.sourceforge.pmd.lang.antlr.AntlrTokenManager.getNextTokenFromAnyChannel(AntlrTokenManager.java:47)
        at net.sourceforge.pmd.lang.antlr.AntlrTokenManager.getNextToken(AntlrTokenManager.java:38)
        at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:45)
        at net.sourceforge.pmd.cpd.AntlrTokenizer.tokenize(AntlrTokenizer.java:39)
        ... 10 more
`
**Code Sample demonstrating the issue:**

```
See above.
```

**Steps to reproduce:**

Run CPD on the snippet

**Running PMD through:** CLI

**Comment by gustavebbers** [comment]
Issue still exists with C# in PMD 6.53.0
