### ISSUE TITLE
[java] java.lang.NoClassDefFoundError: com/sun/mail/util/FolderClosedIOException when using UnusedImportsRule

### ISSUE THREAD

**Issue by yuridolzhenko** [pmd/pmd#2751]
**Affects PMD Version:** 

6.26.0

**Description:**

With UnusedImports in a rule set exception is being thrown.

**Exception Stacktrace:**

```
java.lang.NoClassDefFoundError: com/sun/mail/util/FolderClosedIOException
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
	at java.base/java.lang.Class.getMethods(Class.java:1904)
	at net.sourceforge.pmd.lang.java.ast.internal.ImportWrapper.<init>(ImportWrapper.java:44)
	at net.sourceforge.pmd.lang.java.ast.internal.ImportWrapper.<init>(ImportWrapper.java:33)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit(UnusedImportsRule.java:131)
	at net.sourceforge.pmd.lang.java.ast.ASTImportDeclaration.jjtAccept(ASTImportDeclaration.java:143)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:219)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:391)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit(UnusedImportsRule.java:57)
	at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:44)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:162)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:156)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:336)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:575)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:148)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:194)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:89)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.MonoThreadProcessor.runAnalysis(MonoThreadProcessor.java:29)
	at net.sourceforge.pmd.processor.AbstractPMDProcessor.processFiles(AbstractPMDProcessor.java:122)
	at net.sourceforge.pmd.PMD.processFiles(PMD.java:309)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultCollector.generateReport(PMDResultCollector.java:118)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultCollector.getResults(PMDResultCollector.java:75)
	at com.intellij.plugins.bodhi.pmd.PMDInvoker$1.run(PMDInvoker.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:274)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.sun.mail.util.FolderClosedIOException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.sourceforge.pmd.util.ClasspathClassLoader.loadClass(ClasspathClassLoader.java:123)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 47 more
```

**Running PMD through:** *Maven|Intellij IDEA*

**Comment by oowekyala** [comment]
This has been fixed by #2685, which will be part of PMD 6.27.0

See also #2663
