### ISSUE TITLE
[java] [6.27.0] Exception applying rule CloseResource on file ... java.lang.NullPointerException

### ISSUE THREAD

**Issue by boris-petrov** [pmd/pmd#2755]
**Affects PMD Version:** 

6.27.0

**Description:**

Rule: [CloseResource](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#closeresource)

Upgrading from 6.25.0 (because 6.26.0 also had a problem) and running PMD leads to:

**Exception Stacktrace:**

```
Exception applying rule CloseResource on file /home/boris/project/src/File.java, continuing with next rule
java.lang.NullPointerException
        at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.isResourceTypeOrSubtype(CloseResourceRule.java:336)
        at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.getResourceVariables(CloseResourceRule.java:178)
        at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.checkForResources(CloseResourceRule.java:159)
        at net.sourceforge.pmd.lang.java.rule.errorprone.CloseResourceRule.visit(CloseResourceRule.java:153)
        at net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration.jjtAccept(ASTMethodDeclaration.java:37)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:267)
...

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle

**Comment by shilko2013** [comment]
It is reproduced while using "var" feature

**Comment by adangel** [comment]
Code snippet to reproduce:

```java
import java.io.*;

public class Foo {
    public int bar() {
        var inputStream = getInputStreamFromSomewhere();
        if (inputStream != null) {
            try (InputStreamReader reader = new InputStreamReader(inputStream, "UTF-8")) {
                char c = reader.read();
                return c;
            }
        }
        return -1;
    }
}
```

**Comment by christianhujer** [comment]
I observed the same issue. And I can confirm that it is related to the `var` keyword. I had the following unit test (simplified for the context):

```
    @Test
    void testInvalid() {
        final var exception = assertThrows(IllegalArgumentException.class, () -> { throw new IllegalArgumentException(); });
        assertEquals("Expected message", exception.getMessage());
    }
```

And PMD would throw the mentioned NPE. Replacing `var` with `Throwable` solved the problem. That's of course not a solution, just a workaround. Code that already makes use of `var` a lot needs a fix to PMD.

Links
* Project: https://github.com/nelkinda/gameoflife-java (clone, set your JDK to 13 or newer, and run `./gradlew build`)
* Source Code: https://github.com/nelkinda/gameoflife-java/blob/master/src/test/java/com/nelkinda/training/gameoflife/ParserTest.java
