### ISSUE TITLE
[c++] Lexical error with gpdgui

### ISSUE THREAD

**Issue by Sebanisu** [pmd/pmd#2815]
**Affects PMD Version:** 
6.28.0

**Description:**

I ran the PMD duplicate code detector on my source directory. Using  C++ as language. This was on Windows 10.

**Exception Stacktrace:**

```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file D:\dev\OpenVIII_CPP_WIP\src\open_viii\graphics\background\LayerID.hpp at line 21, column 56.  Encountered: Lexical error at line 21, column 56.  Encountered: "\r" (13), after : "\'1110 };" (in lexical state 0)
        at net.sourceforge.pmd.lang.ast.TokenMgrError.withFileName(TokenMgrError.java:124)
        at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:44)
        at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:144)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:139)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:108)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:70)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:80)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:65)
        at net.sourceforge.pmd.cpd.GUI.go(GUI.java:684)
        at net.sourceforge.pmd.cpd.GUI.access$500(GUI.java:71)
        at net.sourceforge.pmd.cpd.GUI$GoListener$1.run(GUI.java:248)
        at java.lang.Thread.run(Unknown Source)
```

**Code Sample demonstrating the issue:**

[https://github.com/Sebanisu/OpenVIII_CPP_WIP/blob/master/src/open_viii/graphics/background/LayerID.hpp](LayerID.hpp)

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1. Ran cpdgui.bat
2. Browse to D:\dev\OpenVIII_CPP_WIP\src
3. Set Language to C++
4. Click GO!

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

OS Name:                   Microsoft Windows 10 Home
Version 1903
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

**Comment by LiGaOg** [comment]
please assign this issue to me

**Comment by UncleOwen** [comment]
Cannot reproduce using pmd 7.23.0. Closing as not reproduceable.

Feel free to reopen with more information if I missed something.
