### ISSUE TITLE
[ci] Improve GH Actions scripts

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#2967]
This affects at least the following repos: pmd, pmd-designer, build-tools, pmd-regression-tester, pmd-eclipse-plugin
I migrated them in the last month from travis to gh actions and you can see some evolution over the time...
The goal is, that we have a common way for our build/deploy/release scripts, that are shared and reused by all our repos.
Additionally, I don't want to create the next vendor lock-in, so the scripts should be able to be used without github actions as well.

For sharing the scripts, I have something in mind, which I did for the pmd-eclipse-plugin: See function "fetch_ci_scripts" in https://github.com/pmd/pmd-eclipse-plugin/blob/master/.ci/build.sh
The scripts are downloaded from build-tools repo and then executed. We could even version the scripts by downloading the scripts using a specific tag. Alternatively instead of downloading, we could also use git submodules.

Sharing the scripts would allow us to automate the release for pmd-regression-tester as well (currently, the releases need to be created manually on github).

Integration with GH Actions should look always similar: one main build.yaml which calls our own build.sh. All workflows should also work on forked repos without breaking (they might do less, e.g. only build but not deploy)

Suggested task list:
* [x] Generalize and move all scripts to build-tools. There are a lot more script in pmd repo, that should be moved.
    * [x] e.g. check-environment.sh
    * [x] add locale check (see also #2970 ) and explicitly set locale to `C.UTF-8` at the beginning of the script, using en_US.UTF-8 
* [x] Use the same approach for sharing secrets. The (gpg) encrypted environment variables could be stored in build-tools as well, also the other secrets like ssh-key and gpg release signing key. For the encrypted files, "gpg --armor" would look nicer than the binary files.
    * [x] build-tools
    * [x] pmd-eclipse-plugin
      * bug with github-releases-api.bash fixed in https://github.com/pmd/build-tools/commit/9c4752240f183ce16aa24cb9105226f7f614270c
    * [x] pmd-bluej 
    * [x] pmd-designer (https://github.com/pmd/pmd-designer/pull/47)
    * [x] pmd-regression-tester (https://github.com/pmd/pmd-regression-tester/pull/87)
       * For pmd-regression-tester, consider to add "target/repositories" as cache directory :heavy_check_mark: 
    * [x] pmd #3220
       * [x] use zulu jdk7 instead of oracle... 
       * [x] for the main pmd repo, where we use kotlin/dokka, there is a workaround needed to fetch dependencies until https://github.com/Kotlin/dokka/pull/1644 is released. Currently (2021-02-11) the latest version 1.4.20 doesn't include this fix. 
         * Update 2021-04-15: Dokka 1.4.30 (https://github.com/Kotlin/dokka/releases/tag/v1.4.30) contains the fix
       * [x] There is one fix, that can be removed probably: for the dokka generated apidocs of pmd-lang-test, there was special handling, which is not needed anymore (see function "pmd_code_fixPmdLangTestStyle" in pmd-code-api.sh). This can probably be removed.
       * [x] Remove old docker build
* [x] There are still some references to travis, e.g. in the PR template
* [x]  synchronization to sourceforge could be done in a separate job. This job would do the following:
  * :heavy_check_mark: git repo sync -> from github to sourceforge, on push.
  * :x: releases sync -> from pmd-code.org to sourceforge, on releases
  * :x: baseline sync -> from pmd-code.org to sourceforge, on push
  * :x: doc archive sync -> from pmd-code.org to sourceforge, on releases
  * :x: snapshot doc sync? on push
  * These could be done later if needed
* [x] Have a correct and similar build badge on each repo (e.g. currently pmd repo uses the name "Pushes", which should be changed to "Build")
* [x] Log output should be reduced (e.g. while running maven_dependencies), see also #3067 - obsolete, since maven_dependencies is not needed anymore
* [x] Maybe remove travis_wait script. This is probably not needed anymore.
* [x] Make sure, the we support forked workflows: https://github.community/t/stop-github-actions-running-on-a-fork/17965/2
   "if: github.owner == pmd" or "github.repository_owner == 'pmd'"
    * works :heavy_check_mark: , e.g. https://github.com/adangel/build-tools/actions
* [x] move the docker config to build-tools
  * this is basically the environment for testing the scripts and could be used to run the scripts somewhere else (e.g. not on github, if needed)
  * set the correct locale, e.g. en_US.UTF-8, see http://jaredmarkell.com/docker-and-locales/
* [x] And most important: create a documentation, that describes the solution
  * BUILDING.md, do-release.sh devdocs/development.md, releasing.md
  * describe the needed environment variables, see also below. Preliminary doc is at: https://github.com/pmd/build-tools#private-envasc
  * describe how to test the scripts or run them locally using docker
  * describe integration of danger
* [x] Figure out, whether we need the jobs for sonar and coveralls (both might have a different github integration anyway)
  * https://sonarcloud.io/dashboard?id=net.sourceforge.pmd%3Apmd
    -> Yes, needed. We use "CI-based analysis method" with Github Actions, see https://sonarcloud.io/documentation
  * https://coveralls.io/github/pmd/pmd
    -> Yes, needed: We don't use the [Coveralls Github Actions](https://github.com/marketplace/actions/coveralls-github-action) but the [coveralls-maven-plugin](https://github.com/trautonen/coveralls-maven-plugin). In any case, we need to run tests with coverage recording.

**Comment by adangel** [comment]
Ok, it turns out that the workaround for dokka (maven_dependencies_resolve) doesn't play well for a new version. pmd-test depends on pmd-core, but pmd-core is not there yet, and I guess, since we are replacing the pmd-core artifact (shading...), it's not in the current reactor for dependency:resolve.... We probably can build pmd-core separately first - that should be no problem, since dokka is only involved at pmd-lang-test.

**Comment by adangel** [comment]
That didn't work:

```
bundler: failed to load command: .ci/render_release_notes.rb (.ci/render_release_notes.rb)
Bundler::GemNotFound: Could not find public_suffix-4.0.6 in any of the sources
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
  /home/pmd-ci/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
[INFO   ] Updating github release 35185806
[SUCCESS] Updated release with id=35185806
```
