### ISSUE TITLE
Encountered: Lexical error at line 47, column 30.  Encountered: "(" (40), after : "(void (^ _Nonnull)" (in lexical state 1)

### ISSUE THREAD

**Issue by songxing10000** [pmd/pmd#3232]
**Exception Stacktrace:**

```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file /Users/dfpo/hilifeCollege/hilifeElite/shiku_im/study/video/SJBaseVideoPlayer/SJBaseVideoPlayer/Tool/SJPrompt.m at line 47, column 30.  Encountered: Lexical error at line 47, column 30.  Encountered: "(" (40), after : "(void (^ _Nonnull)" (in lexical state 1)
	at net.sourceforge.pmd.lang.ast.TokenMgrError.withFileName(TokenMgrError.java:124)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:44)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:144)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:139)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:108)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:70)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:80)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:65)
	at net.sourceforge.pmd.cpd.GUI.go(GUI.java:712)
	at net.sourceforge.pmd.cpd.GUI.access$500(GUI.java:71)
	at net.sourceforge.pmd.cpd.GUI$GoListener$1.run(GUI.java:266)
	at java.base/java.lang.Thread.run(Thread.java:832)
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file /Users/dfpo/hilifeCollege/hilifeElite/shiku_im/study/video/SJBaseVideoPlayer/SJBaseVideoPlayer/Tool/SJPrompt.m at line 47, column 30.  Encountered: Lexical error at line 47, column 30.  Encountered: "(" (40), after : "(void (^ _Nonnull)" (in lexical state 1)
	at net.sourceforge.pmd.lang.ast.TokenMgrError.withFileName(TokenMgrError.java:124)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:44)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:144)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:139)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:108)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:70)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:80)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:65)
	at net.sourceforge.pmd.cpd.GUI.go(GUI.java:712)
	at net.sourceforge.pmd.cpd.GUI.access$500(GUI.java:71)
	at net.sourceforge.pmd.cpd.GUI$GoListener$1.run(GUI.java:266)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Code**

```
- (void (^)(void (^ _Nonnull)(SJPromptConfig * _Nonnull)))update {
    __weak typeof(self) _self = self;
    return ^void(void(^block)(SJPromptConfig *config)) {
        __strong typeof(_self) self = _self;
        if ( !self ) return;
        if ( block ) block(self.config);
        self.promptLabel.font = self.config.font;
        self.promptLabel.textColor = self.config.fontColor;
        self.backgroundView.backgroundColor = self.config.backgroundColor;
        self.backgroundView.layer.cornerRadius = self.config.cornerRadius;
        [self.promptLabel mas_updateConstraints:^(MASConstraintMaker *make) {
            make.edges.mas_offset(self.config.insets);
        }];
    };
}

```

**Comment by oowekyala** [comment]
Thanks for the report. What language is this?

**Comment by adangel** [comment]
Judging from the filename extension (`SJPrompt.m`) it might be ObjectiveC....

**Comment by songxing10000** [comment]
> Thanks for the report. What language is this?

Yes, the language is `Objectivec`, Apple keywords such as _Nonnull, nullable are some of the new feature keywords
