### ISSUE TITLE
[java] NullPointerException applying rule GuardLogStatement

### ISSUE THREAD

**Issue by breizh31** [pmd/pmd#3340]
Java analysis with PMD 6.34.0 (and 6.35.0)

```java
2021-06-15 01:18:26 [INFO]  WARNING: Exception applying rule GuardLogStatement on file /tmp/file.java, continuing with next rule
2021-06-15 01:18:26 [INFO]  java.lang.NullPointerException
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.bestpractices.GuardLogStatementRule.hasArgumentWithMethodCall(GuardLogStatementRule.java:137)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.bestpractices.GuardLogStatementRule.visit(GuardLogStatementRule.java:123)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTStatementExpression.jjtAccept(ASTStatementExpression.java:25)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:657)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTStatement.jjtAccept(ASTStatement.java:25)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:672)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTBlockStatement.jjtAccept(ASTBlockStatement.java:25)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:667)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTBlock.jjtAccept(ASTBlock.java:27)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:657)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTStatement.jjtAccept(ASTStatement.java:25)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:717)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTForStatement.jjtAccept(ASTForStatement.java:39)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:657)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTStatement.jjtAccept(ASTStatement.java:25)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:672)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTBlockStatement.jjtAccept(ASTBlockStatement.java:25)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:667)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTBlock.jjtAccept(ASTBlock.java:27)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:447)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration.jjtAccept(ASTMethodDeclaration.java:37)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:267)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBodyDeclaration.jjtAccept(ASTClassOrInterfaceBodyDeclaration.java:44)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:262)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBody.jjtAccept(ASTClassOrInterfaceBody.java:35)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:232)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.bestpractices.GuardLogStatementRule.visit(GuardLogStatementRule.java:101)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceDeclaration.jjtAccept(ASTClassOrInterfaceDeclaration.java:56)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:417)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept(ASTTypeDeclaration.java:39)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:220)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:392)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.bestpractices.GuardLogStatementRule.visit(GuardLogStatementRule.java:93)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:44)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:163)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:157)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:336)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:659)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:163)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:200)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:113)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:95)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:57)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:85)
2021-06-15 01:18:26 [INFO]  	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:29)
2021-06-15 01:18:26 [INFO]  	at java.util.concurrent.FutureTask.run(Unknown Source)
2021-06-15 01:18:26 [INFO]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2021-06-15 01:18:26 [INFO]  	at java.util.concurrent.FutureTask.run(Unknown Source)
2021-06-15 01:18:26 [INFO]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2021-06-15 01:18:26 [INFO]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2021-06-15 01:18:26 [INFO]  	at java.lang.Thread.run(Unknown Source)
```

Surely due to this awful code line:
`if (LOGGER.isDebugEnabled()) LOGGER.debug("Extracting mail address of [" + userName + "]...");`

Thanks,

François

**Comment by oowekyala** [comment]
I can't reproduce your problem with the line of code you provided. Could you give a complete minimal reproducible example? That is, a valid java class and contents

**Comment by breizh31** [comment]
I took a few minutes to write the UT:
`    <test-code>
        <description>NullPointerException applying rule GuardLogStatement (#3340)</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
package com.infotel.aro.moteur.eventalert;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


public class AlertsChangeZoneByUserHandler
{
    protected void extractMailAddressesFromLdap()
    {
        final EventAlertLdapReader ldapReader = new EventAlertLdapReader();
        for (final Object allUser : allUsers) {

            final String userName = (String) allUser;
            if (LOGGER.isDebugEnabled()) LOGGER.debug("Extracting mail address of [" + userName + "]...");
            String mail = null;
            try {
                mail = ldapReader.getMailForUser(userName);
            } catch (final Exception exc) {
                LOGGER.warn("Ldap exception while retrieving mail for userName [" + userName + "]");
                LOGGER.error("Exception message [" + exc.getMessage() + " ] ", exc);
            }
            if (AroStringUtils.isStringEmpty(mail)) LOGGER.warn("Mail cannot be found for userName [" + userName + "]");
            mailByUserName.put(userName, mail);
        }
    }
}
        ]]></code>
    </test-code>
</test-data>
`

**Comment by adangel** [comment]
@breizh31 your code sample still doesn't produce the NPE. This code reports three violations though, which are valid (twice LOGGER.warn, once LOGGER.error).

**Comment by adangel** [comment]
I can reproduce the NPE with the following line `LOGGER.debug();`
Do you have a log statement without any arguments?

**Comment by breizh31** [comment]
@adangel, sorry for misleading you. You are right, there is a own public method debug() which is called in the class.

The right test is:
`   <test-code>
        <description>NullPointerException applying rule GuardLogStatement (#3340)</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
package com.aro.moteur.eventalert;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class AlertsChangeZoneByUserHandler
{
    public void buildMessages()
    {
		for (final AlertMailUserChangeZone alertMail : alertMails) {
            alertMail.debug();
            try {
                if (LOGGER.isInfoEnabled()) {
                    LOGGER.info("Building alert mail.");
                }
                alertMail.buildTextAlerts(migrationAlertsByUser, endOfLifeAlertsByUser);
                alertMail.buildMail(templateMail);
                alertMail.saveMail(savedMailsDirectory, sender);
            } catch (final ArcsysException | IOException exc) {
                LOGGER.warn("Alert mail cannot be generated - Exception message [" + exc.getMessage(), exc);
            }
        }
    }
}
        ]]></code>
    </test-code>`
