### ISSUE TITLE
[core] NPE when specifying report file in current directory in PMD CLI

### ISSUE THREAD

**Issue by poojasix** [pmd/pmd#3377]
**Affects PMD Version:**  - 6.36.0

**Description:**

While executing pmd.bat command for apex files it throws null pointer exception.

```
C:\Users\0025AQ744\Downloads\pmd-bin-6.36.0 (1)\pmd-bin-6.36.0\bin>pmd.bat -d "C:\DemoProject\GT\NorthStar\force-app\main\default\classes" -f html -R category/apex/codestyle.xml -r codestyle_36.html
Jul 02, 2021 5:02:45 PM net.sourceforge.pmd.PMD doPMD
SEVERE: Exception during processing
java.lang.NullPointerException
        at java.nio.file.Files.provider(Unknown Source)
        at java.nio.file.Files.createDirectory(Unknown Source)
        at java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
        at java.nio.file.Files.createDirectories(Unknown Source)
        at net.sourceforge.pmd.util.IOUtil.createWriter(IOUtil.java:80)
        at net.sourceforge.pmd.renderers.AbstractRenderer.setReportFile(AbstractRenderer.java:124)
        at net.sourceforge.pmd.PMD.doPMD(PMD.java:240)
        at net.sourceforge.pmd.PMD.runPmd(PMD.java:574)
        at net.sourceforge.pmd.PMD.runPmd(PMD.java:546)
        at net.sourceforge.pmd.PMD.main(PMD.java:502)


```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

open cmd and run pmd command --> pmd.bat -d "path to class files folder" -f html -R "category/apex/design.xml" -r report.html

this is not reproducible in 6.34.0

**Running PMD through:** *[CLI *

Java - 1.8

**Comment by adangel** [comment]
Thanks for the report. This probably happens only when the report file is given with a relative path, like in your example: "-r codestyle_36.html".

We probably need to add a call to `.toAbsolutePath()`, before we try to create the parent directory to ensure the directory exists, where the report will be written to...
See also #2639
