### ISSUE TITLE
parsing error on code accepted by javac

### ISSUE THREAD

**Issue by cbfiddle** [pmd/pmd#3699]
```java
public class PMDExample
{
    public class Foo{}

    private static void test(PMDExample. @NotNull Foo foo) {}
}
```

The problem is the annotation. I would never write this, but an IDEA refactoring did. Same usage.

```xml
<error filename="/Volumes/L/P/hack/JavaAnalysis/src/com/cbfiddle/app/javaAnalysis/PMDExample.java" msg="PMDException: Error while parsing /Volumes/L/P/hack/JavaAnalysis/src/com/cbfiddle/app/javaAnalysis/PMDExample.java">
<![CDATA[net.sourceforge.pmd.PMDException: Error while parsing /Volumes/L/P/hack/JavaAnalysis/src/com/cbfiddle/app/javaAnalysis/PMDExample.java
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:124)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:100)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:62)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:85)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.sourceforge.pmd.lang.java.ast.ParseException: Encountered " "." ". "" at line 47, column 40.
Was expecting one of:
    "this" ...
    <IDENTIFIER> ...
    "@" ...
    "|" ...
    "..." ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    
	at net.sourceforge.pmd.lang.java.ast.JavaParser.generateParseException(JavaParser.java:13532)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.jj_consume_token(JavaParser.java:13416)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.VariableDeclaratorId(JavaParser.java:1974)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.FormalParameter(JavaParser.java:2328)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.FormalParameters(JavaParser.java:2229)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.MethodDeclarator(JavaParser.java:2173)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.MethodDeclaration(JavaParser.java:2118)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBodyDeclaration(JavaParser.java:1811)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBody(JavaParser.java:1764)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceDeclaration(JavaParser.java:905)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.TypeDeclaration(JavaParser.java:807)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.CompilationUnit(JavaParser.java:527)
	at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:62)
	at net.sourceforge.pmd.lang.AbstractParser.doParse(AbstractParser.java:44)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:136)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:200)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:118)
	... 10 more
]]>
</error>
```

**Comment by cbfiddle** [comment]
I can't tell if that weirdness means the paste got garbled.

```
Caused by: net.sourceforge.pmd.lang.java.ast.ParseException: Encountered " "." ". "" at line 47, column 40.
Was expecting one of:
    "this" ...
    <IDENTIFIER> ...
    "@" ...
    "|" ...
    "..." ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...

```

**Comment by jsotuyod** [comment]
@cbfiddle please, refer to [github docs on quoting code / markup](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). The XML is processed and won't show otherwise.

**Comment by jsotuyod** [comment]
@cbfiddle the code you provided is not legal Java code… in particular, intersecting an annotation in between a fully qualified name is not legal:

`PMDExample. @NotNull Foo`

The valid code would be `@NotNull PMDExample.Foo` which is properly parsed by PMD.

**Comment by cbfiddle** [comment]
The JLS disagrees:

ClassType:
{Annotation <https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-Annotation>} Identifier <https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-Identifier> [TypeArguments <https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-TypeArguments>] 
ClassOrInterfaceType <https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-ClassOrInterfaceType> . {Annotation <https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-Annotation>} Identifier <https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-Identifier> [TypeArguments <https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-TypeArguments>]

**Comment by jsotuyod** [comment]
@cbfiddle my bad, I should have assumed you were using `org.jetbrains.annotations.NotNull` instead of JSR-305… that in fact has `TYPE_USE` support and can be used that way.

This cumbersome syntax is already supported for PMD 7, but unfortunately won't be backported to PMD 6.x. Supporting this in PMD 7 required extensive modifications to the AST (which in PMD 7 is not backwards compatible).
