### ISSUE TITLE
[plsql] Parsing exception CURSOR statement with parenthesis groupings

### ISSUE THREAD

**Issue by hgodinez89** [pmd/pmd#3706]
**Affects PMD Version:** 

This error was testing in the following versions:

- 6.41.0
- 6.40.0
- 6.39.0

**Description:**

Trying to analyze pl/sql code that has CURSOR statement with parenthesis groupings, PMD raises an exception error that indicates "Error while parsing".

_Note:_ The purpose of parenthesis groupings is only for the purpose of making the code more readable.

**Exception Stacktrace:**

```
net.sourceforge.pmd.PMDException: Error while parsing C:\testfolder\example_procedure.prc
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:124)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:100)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:62)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:85)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: net.sourceforge.pmd.lang.plsql.ast.ParseException: Encountered "  "USER_OBJECTS "" at line 5, column 16.
Was expecting one of:
    "(" ...
    "SELECT" ...
    "WITH" ...
    "WITH" ...
    "SELECT" ...
    "(" ...
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.generateParseException(PLSQLParser.java)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.jj_consume_token(PLSQLParser.java)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Subquery(PLSQLParser.java:10774)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.QueryTableExpression(PLSQLParser.java:22715)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.TableReferenceInJoin(PLSQLParser.java:23219)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.JoinClause(PLSQLParser.java:23341)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.FromClauseEntry(PLSQLParser.java:21545)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.FromClause(PLSQLParser.java:21447)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.RestOfStatement(PLSQLParser.java:10603)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.SelectStatement(PLSQLParser.java:28448)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.CursorUnit(PLSQLParser.java:38877)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.CursorSpecification(PLSQLParser.java:38919)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.DeclarativeUnit(PLSQLParser.java:2728)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.DeclarativeSection(PLSQLParser.java:3154)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.ProgramUnit(PLSQLParser.java:6446)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Global(PLSQLParser.java:879)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Input(PLSQLParser.java:153)
	at net.sourceforge.pmd.lang.plsql.PLSQLParser.parse(PLSQLParser.java:61)
	at net.sourceforge.pmd.lang.AbstractParser.doParse(AbstractParser.java:44)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:136)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:200)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:118)
	... 10 more
```

**Code Sample demonstrating the issue:**

```
CREATE OR REPLACE PROCEDURE EXAMPLE_PROCEDURE IS
   --
   CURSOR c_example IS
      SELECT a.owner, u.object_name, p.aggregate
        FROM ((USER_OBJECTS u INNER JOIN ALL_OBJECTS a ON
               u.object_name = a.object_name AND u.object_type = a.object_type AND u.object_id = a.object_id)
               INNER JOIN ALL_PROCEDURES p ON
               p.owner = a.owner AND p.object_name = a.object_name AND p.object_type = a.object_type)
       WHERE a.owner = USER;
   --
BEGIN
   --
   FOR l_object IN c_example LOOP
      --
      DBMS_OUTPUT.Put_Line(l_object.owner);
      DBMS_OUTPUT.Put_Line(l_object.object_name);
      DBMS_OUTPUT.Put_Line(l_object.aggregate);
      --
   END LOOP;
   --
END EXAMPLE_PROCEDURE;
```

_Note:_ By removing all the parentheses in the example `c_example`  cursor, you will not have parsing problems.

**Steps to reproduce:**

1.  Put the code above ("Code Sample demonstrating the issue" section) in example_procedure.prc
2.  Execute PMD analyzer from CLI.
3. See the error showed in the "Exception Stacktrace" section.

**Running PMD through:** *[CLI]*

**Comment by LiGaOg** [comment]
Please assign this issue to me

**Comment by LiGaOg** [comment]
**The main problem in this issue is as follows:**

* Firstly, consider this code:

  ```plsql
  CREATE OR REPLACE PROCEDURE EXAMPLE_PROCEDURE IS
     CURSOR c_example IS
        SELECT a.owner, u.object_name, p.aggregate
          FROM ((USER_OBJECTS u INNER JOIN ALL_OBJECTS a ON
                 u.object_name = a.object_name AND u.object_type = a.object_type AND u.object_id = a.object_id)
                 INNER JOIN ALL_PROCEDURES p ON
                 p.owner = a.owner AND p.object_name = a.object_name AND p.object_type = a.object_type)
         WHERE a.owner = USER;
  ```

  The related BNF for parsing this code is:

  ```java
  // FromClause -> <FROM> FromClauseEntry() ("," FromClauseEntry())*
  void FromClauseEntry() #void :
  {}
  {
   (
       LOOKAHEAD([ SchemaName() "." ] TableName() [<IDENTIFIER>]
                 (<PARTITION>|<NATURAL>|<OUTER>|<INNER>|<JOIN>|<LEFT>|<RIGHT>|<CROSS>|<FULL>)) JoinClause()
   |
       LOOKAHEAD(<IDENTIFIER> "(", {isKeyword("XMLTABLE")}) XMLTable() [ LOOKAHEAD(2) TableAlias() ]
   |
       LOOKAHEAD(3) (TableReference() (JoinClausePart())*) #JoinClause(>1)
   |
       "(" JoinClause() ")"
   )
  }
  ```

  Here, the parser will parse the following part as the `JoinClause` choosing the fourth production `"(" JoinClause() ")"`

  ```plsql
  (USER_OBJECTS u INNER JOIN ALL_OBJECTS a ON
                 u.object_name = a.object_name AND u.object_type = a.object_type AND u.object_id = a.object_id)
                 INNER JOIN ALL_PROCEDURES p ON
                 p.owner = a.owner AND p.object_name = a.object_name AND p.object_type = a.object_type
  ```

  This `JoinClause()` is consists of two tables:

  ```plsql 
  --First table
  (USER_OBJECTS u INNER JOIN ALL_OBJECTS a ON
                 u.object_name = a.object_name AND u.object_type = a.object_type AND u.object_id = a.object_id)
  --Second table
  ALL_PROCEDURES p
  --This two tables are operands of INNER JOIN operation
  ```

  And the parser will choose the following BNF to parse it:

  ```java
  ASTJoinClause JoinClause() :
  {}
  {
      TableReferenceInJoin()
      (JoinClausePart())+
      { return jjtThis; }
  }
  ```

  Here in `TableReferenceInJoin()`, the parser will call `QueryTableExpression()`：

  ```java
  void QueryTableExpression() #void :
  {}
  {
    (
      LOOKAHEAD(2) [ LOOKAHEAD(2) SchemaName() "." ] TableName()
    |
      TableCollectionExpression()
    |
      [ <LATERAL> ] "(" Subquery() [ SubqueryRestrictionClause() ] ")"
    )
  }
  ```

  Here the parser will choose the third production, becase the "(" matches the first part of the JoinClause.

  However, in `Subquery()`：

  ```java
  void Subquery() #void :
  {}
  {
    (
      QueryBlock() (LOOKAHEAD(2) ( SubqueryOperation() ) Subquery() )*
      | "(" Subquery() ")"
    )
    [ LOOKAHEAD(2) OrderByClause() ]
    [ LOOKAHEAD(2) RowLimitingClause() ]
  }
  ```

  It only supports something like：`SELECT * FROM SOMETABLE TABLEALIAS` instead of `SOMETABLE TABLEALIAS`. So the parsing exception occurs.

  The following code will also report the parsing exception, the reason is the same as  above:

  ```plsql
  CREATE OR REPLACE PROCEDURE EXAMPLE_PROCEDURE IS
     CURSOR c_example IS
        SELECT a.owner, u.object_name, p.aggregate
          FROM USER_OBJECTS u INNER JOIN ALL_OBJECTS a ON
                 u.object_name = a.object_name AND u.object_type = a.object_type AND u.object_id = a.object_id)
                 -- Add parenthesis here
                 INNER JOIN (ALL_PROCEDURES p) ON
                 p.owner = a.owner AND p.object_name = a.object_name AND p.object_type = a.object_type
         WHERE a.owner = USER;
  ```

  To fix this issue, I edit the `QueryTableExpression()`

  ```java
  void QueryTableExpression() #void :
  {}
  {
    (
      LOOKAHEAD(2) [ LOOKAHEAD(2) SchemaName() "." ] TableName()
    |
      TableCollectionExpression()
    |
      // Add this production to parse "(ALL_PROCEDURES p)"
      LOOKAHEAD(5) "(" [ LOOKAHEAD(2) SchemaName() "." ] TableName() [TableAlias()] ")"
    |  
      // Add LOOKAHEAD(3) to resolve conficts between the following two productions
      LOOKAHEAD(3) [ <LATERAL> ] "(" Subquery() [ SubqueryRestrictionClause() ] ")"
      // Add this production to parse "(TABLE_A INNER JOIN TABLE_B)" like the bug code listed at the beginning
    | 
      LOOKAHEAD(3) "(" JoinClause() ")"
    )
  }
  
  ```
