### ISSUE TITLE
[core] Anything changes in the way pmd reads rulesets from files?

### ISSUE THREAD

**Issue by rtfpessoa** [pmd/pmd#371]
At Codacy we started experiencing problems with the new PMD 5.6.0 here:

```
java.io.IOException: Stream closed
	at java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:67)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:121)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at net.sourceforge.pmd.util.ResourceLoader$1.read(ResourceLoader.java:109)
	at java.io.InputStream.read(InputStream.java:170)
	at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:462)
	at net.sourceforge.pmd.RuleSetFactoryCompatibility.filterRuleSetFile(RuleSetFactoryCompatibility.java:94)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:283)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:211)
	at net.sourceforge.pmd.RuleSetFactory.createRule(RuleSetFactory.java:258)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleReferenceNode(RuleSetFactory.java:588)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:358)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:306)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:211)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:206)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:167)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:151)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:68)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Couldn't find the class Stream closed
	at net.sourceforge.pmd.RuleSetFactory.classNotFoundProblem(RuleSetFactory.java:332)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:324)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:211)
	at net.sourceforge.pmd.RuleSetFactory.createRule(RuleSetFactory.java:258)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleReferenceNode(RuleSetFactory.java:588)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:358)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:306)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:211)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:206)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:167)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:151)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:68)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Description:**
Apparently it is failing to find the rule class? But we have no idea what is the class.
Did anything change here in the 5.6.0 release? Before I think we would get a message saying what was the rule in question.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Other: Codacy (https://github.com/codacy/codacy-pmdjava)

Is it possible to get a better message? Did we make any mistake invoking PMD?

**Comment by adangel** [comment]
I think, it's this problem: #364 
Should be fixed with 5.6.1 and released in the next days.

**Comment by rtfpessoa** [comment]
Ahh sorry. That might be it. Thanks for the quick response. 

Since 5.6.1 is already 100% complete. When should we expect the release?

**Comment by adangel** [comment]
I'll release it after I've finished https://github.com/pmd/pmd-eclipse-plugin/issues/22 and https://issues.apache.org/jira/browse/MPMD-234

**Comment by adangel** [comment]
PMD 5.6.1 is just released, which should fix this issue.
