### ISSUE TITLE
[java]Parse exception - Pattern Matching in Switch is only supported with JDK 17 Preview.

### ISSUE THREAD

**Issue by k3nda** [pmd/pmd#3772]
**Affects PMD Version:** 

maven-pmd-plugin: 3.15.0
pmd-java: 6.42.0
pmd-core: 6.42.0

**Description:**

When I run `mvn pmd:pmd` I see processing error in console log:
```
[WARNING] /home/medel/Documents/earthbanc/backend/src/main/java/io/earthbanc/backend/command/aggregate/customer/control/CustomerConverter.java: PMDException: Error while parsing /home/medel/Documents/earthbanc/backend/src/main/java/io/earthbanc/backend/command/aggregate/customer/control/CustomerConverter.java
```
And then in result xml file `pmd.xml` is exception (see below)

**Exception Stacktrace:**

```
<error filename="/home/medel/Documents/earthbanc/backend/src/main/java/io/earthbanc/backend/command/aggregate/customer/control/CustomerConverter.java" msg="PMDException: Error while parsing /home/medel/Documents/earthbanc/backend/src/main/java/io/earthbanc/backend/command/aggregate/customer/control/CustomerConverter.java">
<![CDATA[net.sourceforge.pmd.PMDException: Error while parsing /home/medel/Documents/earthbanc/backend/src/main/java/io/earthbanc/backend/command/aggregate/customer/control/CustomerConverter.java
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:124)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:100)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:62)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:85)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.sourceforge.pmd.lang.java.ast.ParseException: Line 33, Column 51: Pattern Matching in Switch is only supported with JDK 17 Preview.
	at net.sourceforge.pmd.lang.java.ast.JavaParser.throwParseException(JavaParser.java:30)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.checkForPatternMatchingInSwitch(JavaParser.java:277)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.CaseLabelElement(JavaParser.java:6197)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.SwitchLabel(JavaParser.java:6136)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.SwitchBlock(JavaParser.java:5932)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.SwitchStatement(JavaParser.java:5904)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Statement(JavaParser.java:5478)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.BlockStatement(JavaParser.java:5671)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Block(JavaParser.java:5588)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Statement(JavaParser.java:5465)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ForStatement(JavaParser.java:6418)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Statement(JavaParser.java:5490)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.BlockStatement(JavaParser.java:5671)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Block(JavaParser.java:5588)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.MethodDeclaration(JavaParser.java:2130)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBodyDeclaration(JavaParser.java:1811)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBody(JavaParser.java:1764)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceDeclaration(JavaParser.java:905)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.TypeDeclaration(JavaParser.java:807)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.CompilationUnit(JavaParser.java:527)
	at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:62)
	at net.sourceforge.pmd.lang.AbstractParser.doParse(AbstractParser.java:44)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:136)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:200)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:118)
	... 10 more
]]>
</error>
```

**Code Sample demonstrating the issue:**
Whatever code with switch pattern matching. I can use some dummy from https://www.baeldung.com/java-switch-pattern-matching
```
static double getDoubleUsingSwitch(Object o) {
    return switch (o) {
        case Integer i -> i.doubleValue();
        case Float f -> f.doubleValue();
        case String s -> Double.parseDouble(s);
        default -> 0d;
    };
}
```

**Steps to reproduce:**

1. Paste code above to some of your java class
2. Run `mvn pmd:pmd`
3. Error in console appears and exception in `target/pmd.xml`

**Running PMD through:** *Maven*

Some parts of my `pom.xml` which may help:
```
</project>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
   </build>
          <pluginManagement>
              <plugins>
                  <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-pmd-plugin</artifactId>
                      <version>3.15.0</version>
                      <dependencies>
                          <dependency>
                              <groupId>net.sourceforge.pmd</groupId>
                              <artifactId>pmd-java</artifactId>
                              <version>6.42.0</version>
                          </dependency>
                          <dependency>
                              <groupId>net.sourceforge.pmd</groupId>
                              <artifactId>pmd-core</artifactId>
                              <version>6.42.0</version>
                          </dependency>
                      </dependencies>
                  </plugin>
              </plugins>
          </pluginManagement>
        <plugins>  
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <compilerArgs>--enable-preview</compilerArgs>
                </configuration>
            </plugin>  
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <configuration>
                    <failOnViolation>true</failOnViolation>
                    <printFailingErrors>true</printFailingErrors>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by k3nda** [comment]
Ah thanks. It is working. Would be nice if this is somewhere in docs because I was not able to find it anywhere :disappointed:

**Comment by oowekyala** [comment]
Indeed. There is a line of doc [here](https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#additional-java-runtime-options) but it's somewhat outdated and does not concern the maven plugin. We should mention this in https://pmd.github.io/latest/pmd_userdocs_tools_maven.html but maybe there's another more obvious place. Can you tell me where's the first place you looked for the info?

**Comment by adangel** [comment]
Maybe here? https://maven.apache.org/plugins/maven-pmd-plugin/pmd-mojo.html#targetJdk
That would require a change in the maven-pmd-plugin, though...

**Comment by adangel** [comment]
Which is also on github: https://github.com/apache/maven-pmd-plugin/blob/aafb6d1049dec95f6d55274cc38f79228e4e9d38/src/main/java/org/apache/maven/plugins/pmd/PmdReport.java#L71-L86
