### ISSUE TITLE
[core] NPE in RuleSet.hashCode

### ISSUE THREAD

**Issue by pandaadb** [pmd/pmd#380]
Hello,

I have recently installed PMD with a ruleset that can be loaded. When trying to use "check code" I receive an NPE: 

```
ava.lang.NullPointerException
        at net.sourceforge.pmd.RuleSet.hashCode(RuleSet.java:542)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.containsKey(HashMap.java:595)
        at net.sourceforge.pmd.lang.rule.AbstractRuleChainVisitor.add(AbstractRuleChainVisitor.java:46)
        at net.sourceforge.pmd.RuleChain.add(RuleChain.java:49)
        at net.sourceforge.pmd.RuleChain.add(RuleChain.java:34)
        at net.sourceforge.pmd.RuleSets.addRuleSet(RuleSets.java:61)
        at net.sourceforge.pmd.RuleSets.<init>(RuleSets.java:48)
        at net.sourceforge.pmd.eclipse.runtime.cmd.BaseVisitor$1.createRuleSets(BaseVisitor.java:304)
        at net.sourceforge.pmd.RulesetsFactoryUtils.getRuleSets(RulesetsFactoryUtils.java:36)
        at net.sourceforge.pmd.processor.AbstractPMDProcessor.createRuleSets(AbstractPMDProcessor.java:63)
        at net.sourceforge.pmd.processor.AbstractPMDProcessor.processFiles(AbstractPMDProcessor.java:68)
        at net.sourceforge.pmd.eclipse.runtime.cmd.BaseVisitor.reviewResource(BaseVisitor.java:351)
        at net.sourceforge.pmd.eclipse.runtime.cmd.ResourceVisitor.visit(ResourceVisitor.java:29)
        at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
        at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
        at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
        at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
        at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
        at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
        at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
        at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.processResource(ReviewCodeCmd.java:424)
        at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.processResources(ReviewCodeCmd.java:373)
        at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.execute(ReviewCodeCmd.java:191)
        at net.sourceforge.pmd.eclipse.runtime.cmd.JobCommandProcessor$1.run(JobCommandProcessor.java:90)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

I checked out the code and I suspect that somehow the name or the rules are null in the hashcode() implementation of the Rule. 

I am not sure if this is to do with my rules, the plugin or the core code. It appears to be an issue in the core code, and I thought I would post it simply because an NPE is likely not planned to happen on that call :) 

I am using: 

PMD: 5.6.1
Eclipse Neon.3 
Plugin version: 4.0.13.v20170429-1921 
Ubuntu 16.04.2 LTS

Please let me know if there is more info I can provide

**Comment by pandaadb** [comment]
This reproduces when I use any rule. Might be a plugin issue?

**Comment by pandaadb** [comment]
I have tested with 5.6.1 via command line and that seems to work nicely. I am not sure if this is still the right place for this bug/error to be reported. Feel free to change/reassign or tell me where else to put this :) I apologise for the inconvenience

**Comment by ryan-gustafson** [comment]
I checked the code for Ruleset.hashCode(), and it is not null safe.  It could be improved to use the Java 7 `Objects.hashCode(Object)` method which is null safe.

I'm not sure what was going on in the Eclipse scenario to trigger this problem.

**Comment by MCMicS** [comment]
Have the same issue after updateing to latest PMD eclipse plugin (4.0.13 and PMD 5.6.1)

**Comment by pandaadb** [comment]
Is this the right place then? Is there a different place I should raise the eclipse plugin bug against?

**Comment by MCMicS** [comment]
I think its the right place because the hasCode method is not nullsafe. But the reason is unknown that the name is null. My ruleset(XML) has a name.

**Comment by jsotuyod** [comment]
Definitely a bug. Thanks for the report.

Ruleset names shouldn't be null, this is probably a bug on the plugin side, combined with some missing checks on PMD itself.

We can probably change it to allow null names with little effort for backwards compatibility, since as far as I recall, the nonnull assumption was mostly based on usage than a hard requirement.

**Comment by adangel** [comment]
Yes, that's that's definitely a plugin issue -> I've created an issue there: https://github.com/pmd/pmd-eclipse-plugin/issues/23

Before changing the hashCode calculation, I'd rather fix the underlaying issue in the plugin....

**Comment by ryan-gustafson** [comment]
It would be nice if we didn't cover up visibility to such problems.  Perhaps they could be made more apparent by adding basic validations when `RuleSetBuilder.build()` or the `RuleSet` constructor is called?  This could change the NPE for (let's just say) a well worded `IllegalArgumentException` about `"name"` being required.

Alternatively, if unnamed/anonymous RuleSets are to be allowed, I'd think some analysis is warranted to ensure it would work in practice.  For example, would the RuleSet serialize to valid XML w.r.t. the schema?  Any other potential _gotchas_?

I much prefer the former if possible, it's a simpler design.

**Comment by adangel** [comment]
According to the [schema](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/resources/ruleset_2_0_0.xsd#L16), the name is required. Description is required, too.

I think, it's a good idea, to raise the problem as early as possible: At the place, where either "null" is set as the ruleset name or when the ruleset is built, and not, when the unrelated hashCode is executed.

I'll try to suggest a PR the next days...
