### ISSUE TITLE
[core] SARIF renderer depends on platform default encoding

### ISSUE THREAD

**Issue by ewantempero** [pmd/pmd#3881]
**Affects PMD Version:** 

PMD version 6.44.0

**Description:**

java.nio.charset.UnmappableCharacterException when rule ```LawOfDemeter``` violated and SARIF format output written to file.

The message in the exception (This should be unreachable) suggests this is a fault.

I've only seen this with ```LawOfDemeter``` (the other few rules I've tried don't have a problem)

The problem only seems to occur when using <tt>-r</tt> and SARIF format.

There is no problem if output is sent to stdout (i.e. not using the <tt>-r</tt> flag)

There is no problem Using a format different to SARIF.

**Exception Stacktrace:**

```
  CLI_prompt> /opt/pmd/pmd-bin-6.44.0/bin/run.sh pmd --no-cache -f sarif -R unmappable.xml -r pmd-report.sarif --debug -d tmp
Mar 30, 2022 7:30:04 AM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
FINER: Adding file /home/ewan/workspace/KalahStandardStarter/tmp/B.java (lang: java 18) 
Mar 30, 2022 7:30:04 AM net.sourceforge.pmd.RuleSetFactory parseRuleSetNode
WARNING: RuleSet description is missing. Future versions of PMD will require it.
Mar 30, 2022 7:30:04 AM net.sourceforge.pmd.RuleSetLoader printRulesInDebug
FINE: Rules loaded from unmappable.xml:
Mar 30, 2022 7:30:04 AM net.sourceforge.pmd.RuleSetLoader printRulesInDebug
FINE: - LawOfDemeter (Java)
Mar 30, 2022 7:30:04 AM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
FINER: Using Java version 'java 18'
Mar 30, 2022 7:30:04 AM net.sourceforge.pmd.processor.PmdRunnable call
FINE: Processing /home/ewan/workspace/KalahStandardStarter/tmp/B.java
Mar 30, 2022 7:30:04 AM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
SEVERE: Exception during processing: java.nio.charset.UnmappableCharacterException: Input length = 1
Exception in thread "main" java.lang.AssertionError: This should be unreachable: exhaustive
        at net.sourceforge.pmd.internal.util.AssertionUtil.shouldNotReachHere(AssertionUtil.java:54)
        at net.sourceforge.pmd.util.log.MessageReporter$Level.toJutilLevel(MessageReporter.java:85)
        at net.sourceforge.pmd.util.log.internal.SimpleMessageReporter.isLoggableImpl(SimpleMessageReporter.java:29)
        at net.sourceforge.pmd.util.log.internal.MessageReporterBase.isLoggable(MessageReporterBase.java:36)
        at net.sourceforge.pmd.util.log.internal.MessageReporterBase.logEx(MessageReporterBase.java:53)
        at net.sourceforge.pmd.util.log.internal.SimpleMessageReporter.logEx(SimpleMessageReporter.java:18)
        at net.sourceforge.pmd.util.log.internal.MessageReporterBase.errorEx(MessageReporterBase.java:112)
        at net.sourceforge.pmd.util.log.internal.SimpleMessageReporter.errorEx(SimpleMessageReporter.java:18)
        at net.sourceforge.pmd.util.log.internal.MessageReporterBase.errorEx(MessageReporterBase.java:107)
        at net.sourceforge.pmd.PMD.doPMD(PMD.java:258)
        at net.sourceforge.pmd.PMD.runPmd(PMD.java:503)
        at net.sourceforge.pmd.PMD.runPmd(PMD.java:470)
        at net.sourceforge.pmd.PMD.main(PMD.java:416)
```

**Code Sample demonstrating the issue:**
```
  class B  {
    public void m() {
        a.b.c();
    }
  }
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1. Java source file is in directory ```tmp```
2. Ruleset is in file ```unmappable.xml``` containing
```
<?xml version="1.0"?>

<ruleset name="MyRules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

    <rule ref="category/java/design.xml/LawOfDemeter"/>
</ruleset>
```
3. Command line is
```
  CLI_prompt> /opt/pmd/pmd-bin-6.44.0/bin/run.sh pmd --no-cache -f sarif -R unmappable.xml -r pmd-report.sarif --debug -d tmp
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

CLI

**Other**

```
CLI_prompt> java -version
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)
CLI_prompt> uname -a
Linux machinename 5.13.0-30-generic #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by oowekyala** [comment]
I can't reproduce the UnmappableCharacterException, but I'll submit a PR for the AssertionError

**Comment by adangel** [comment]
I found a way to reproduce it - it depends on the default platform encoding:

with `export LANG=en_US.ISO-8859-1` the UnmappableCharacterException occurs.

It does not occur with UTF-8 (`export LANG=en_US.UTF-8`).

I'll add a stacktrace soon....

**Comment by adangel** [comment]
```
Apr 01, 2022 11:04:25 AM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
SEVERE: Exception during processing: java.nio.charset.UnmappableCharacterException: Input length = 1
Apr 01, 2022 11:04:25 AM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
FINE: java.lang.IllegalStateException: java.nio.charset.UnmappableCharacterException: Input length = 1
        at net.sourceforge.pmd.renderers.AbstractRenderer.flush(AbstractRenderer.java:109)
        at net.sourceforge.pmd.PmdAnalysis.finishRenderers(PmdAnalysis.java:275)
        at net.sourceforge.pmd.PmdAnalysis.performAnalysisAndCollectReport(PmdAnalysis.java:238)
        at net.sourceforge.pmd.PMD.doPMD(PMD.java:250)
        at net.sourceforge.pmd.PMD.runPmd(PMD.java:503)
        at net.sourceforge.pmd.PMD.runPmd(PMD.java:470)
        at net.sourceforge.pmd.PMD.main(PMD.java:416)
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:275)
        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:306)
        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
        at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:208)
        at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
        at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:256)
        at net.sourceforge.pmd.renderers.AbstractRenderer.flush(AbstractRenderer.java:107)
        ... 6 more
```

**Comment by adangel** [comment]
In the rule description for [LawOfDemeter](https://pmd.github.io/latest/pmd_rules_java_design.html#lawofdemeter) we use a long-dash character:

```
...IEEE, 6(5):38–48, 1989.;...
                ^ this one
```

This character doesn't exist in ASCII or ISO-8859-1 (and probably in many other charsets). It's [U+2013](https://util.unicode.org/UnicodeJsps/character.jsp?a=2013) in unicode.

Currently, when we create the writer for the renderers/reports, we use the default platform encoding. But at least for SARIF, this is probably not correct:

> A SARIF log file SHALL be encoded in UTF-8 [[RFC3629](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#RFC3629)].

[3 File Format](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317419)

For SARIF, we must ensure to output UTF-8 encoded data.

**Comment by adangel** [comment]
Update: I shortly couldn't reproduce it anymore. But I was using java18, and there UTF-8 is used regardless of the environment as a default encoding -> UTF-8 by Default ([JEP 400](https://openjdk.java.net/jeps/400))
