### ISSUE TITLE
[matlab] Lexical error when a comment starts with '#' after `...`

### ISSUE THREAD

**Issue by ThePositiveApe** [pmd/pmd#4098]
**Affects PMD Version:** 6.48.0

**Description:**

I get a 'Lexical error' when using CPD on valid MATLAB code when a comment starts with `#` after a line continuation. For example:
```matlab
x = 2 ... #Some comment
  + 2;
```
Full error message:
Lexical error at line 99, column 50.  Encountered: "#" (35), after : "" (in lexical state 0)

**Exception Stacktrace:**

```
Encountered: Lexical error at line 99, column 50.  Encountered: "#" (35), after : "" (in lexical state 0)
        at net.sourceforge.pmd.lang.ast.TokenMgrError.withFileName(TokenMgrError.java:124)
        at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:44)
        at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:154)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:148)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:117)
        at net.sourceforge.pmd.cpd.CPD.add(CPD.java:79)
        at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:90)
        at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:74)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:162)
        at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:142)
        at net.sourceforge.pmd.cpd.CPD.runCpd(CPD.java:225)
        at net.sourceforge.pmd.cpd.CPD.main(CPD.java:196)
```

**Code Sample demonstrating the issue:**

```matlab
    allLinesThisScope   = unique(allLineNrs(allLineNrs > allScopes(iScope).FirstLine ...
        & allLineNrs > lineNrsSorted(iScope) ... #126, comment
        & allLineNrs < allScopes(iScope).LastLine));
```

**Steps to reproduce:**

Command used:
`cpd.bat --minimum-tokens 100 --files <myfolder> --language matlab --debug`

**Running PMD through:** *CLI*

Windows OS

**Comment by aarongoldenthal** [comment]
The same error occurs with JavaScript files, which is unfortunately the case for the shebang in Node.js `bin` files.

**Comment by jsotuyod** [comment]
@aarongoldenthal Shebangs are a different matter. The shebang is not part of the js language, it's something the shell actually parses and removes before feeding the code to the actual binary. Any js environment (ie: a browser) will show some kind of parsing error upon a shebang.

This issue relates to a Matlab specific syntax, which is fully supported by Matlab itself.

**Comment by aarongoldenthal** [comment]
I'm happy to open a different issue for it, but there are JavaScript runtimes like Node.js that provide for a package with executable JavaScript files, and these do need a shebang. So, other parsers for code analysis, e.g. any compatible with ESLint, do accept it for JavaScript targeting Node.js. And there are rules to check that it is included in any executable file.

PMD CPD, however, fails as noted above.

**Comment by dtlhlbs** [comment]
I'm also getting this error on the `#endif` in C++ include guards:

```cpp
#ifndef ANIMAL
#define ANIMAL

class Animal {
    // Code
};

#endif <--- EOF error is here
```

`[main] ERROR net.sourceforge.pmd.cli - Skipping file: Lexical error in file '<redacted>' at line 8, column 7: <EOF> after : "" (in lexical state PREPROCESSOR_OUTPUT)`

If I add a return after `#endif` the lexical error disappears, but this means changing all my source files.

Also Windows OS, using `cpd.bat --language cpp`
