### ISSUE TITLE
[java][doc] AvoidAssertAsIdentifier and AvoidEnumAsIdentifier - clarify use case

### ISSUE THREAD

**Issue by Belle-PL** [pmd/pmd#4164]
**Affects PMD Version:6.50.0** 

**Description:**

Hi, it is obvious that this rule [AvoidAssertAsIdentifier](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#avoidassertasidentifier) can detect the variable which is named **assert**, but when I run PMD on the code example below, it is crashed unexpectedly. Besides, this case is also shown in the [document](https://pmd.sourceforge.io/pmd-6.50.0/pmd_rules_java_errorprone.html#avoidassertasidentifier).
 
**Exception Stacktrace:**
```
net.sourceforge.pmd.PMDException: Error while parsing /path/to/src/code
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:124)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:100)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:62)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:89)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:30)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: net.sourceforge.pmd.lang.java.ast.ParseException: Line 3, Column 23: Can't use 'assert' as a variable name when running in JDK 1.4 mode!
	at net.sourceforge.pmd.lang.java.ast.JavaParser.throwParseException(JavaParser.java:30)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.checkForBadAssertUsage(JavaParser.java:35)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.VariableDeclaratorId(JavaParser.java:1999)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.VariableDeclarator(JavaParser.java:1921)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.LocalVariableDeclaration(JavaParser.java:5882)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.BlockStatement(JavaParser.java:5798)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.Block(JavaParser.java:5718)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.MethodDeclaration(JavaParser.java:2148)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBodyDeclaration(JavaParser.java:1829)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceBody(JavaParser.java:1782)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.ClassOrInterfaceDeclaration(JavaParser.java:923)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.TypeDeclaration(JavaParser.java:825)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.CompilationUnit(JavaParser.java:545)
	at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:62)
	at net.sourceforge.pmd.lang.AbstractParser.doParse(AbstractParser.java:45)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:136)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:200)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:118)
	... 10 more

```

**Code Sample demonstrating the issue:**

```java
public class C {
    void bar() {
        String assert = "hi";
    }
}
```

**Steps to reproduce:**
Directly run PMD to test this file.

**Running PMD through:** *[Maven]*

**Comment by Belle-PL** [comment]
It seems that the rule [AvoidEnumAsIdentifier](https://pmd.sourceforge.io/pmd-6.50.0/pmd_rules_java_errorprone.html#avoidenumasidentifier) has similar problem. The code example is below:

```java
public class A {
    void bar() {
        String enum = "hi";
    }
}
```
PMD was crashed and did not generate a valid report when analyzed this code example.

**Comment by jsotuyod** [comment]
@Belle-PL this is down to how you are running PMD. You'll see, PMD **requires** that analyzed code be valid. The above code is only valid in Java up to version 1.3 for the assert example, Java 1.5 for the enum one. Any newer Java versions would fail to parse / compile that code. The rules were merely intended to help people using those versions to prepare to upgrade.

By default PMD uses the latest supported Java version, so in PMD 6.50.0 the code is being parsed as Java 19 unless told otherwise. Under Java 19 the code is invalid, and the parse error occurs.

To have PMD parse the code as a different version, you need to set it explicitly (ie: in the CLI this can be done by using the options `-language java -version 1.3`
