### ISSUE TITLE
Lexical header in C-header file from Linux

### ISSUE THREAD

**Issue by stevenKlusener** [pmd/pmd#4217]
Language: C
PMD Version: 6.51.0

Description:

When running CPD (with --language c) PMD raises a lexical error.

The input file can be retrieved from:
  https://github.com/torvalds/linux/blob/master/arch/arc/include/asm/entry-arcv2.h

**Exception Stacktrace:**
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file .../linux/arch/arc/include/asm/entry-arcv2.h at line 184, column 37.  Encountered: Lexical error at line 184, column 37.  Encountered: "\n" (10), after : "\'t really matter" (in lexical state 0)
	at net.sourceforge.pmd.lang.ast.TokenMgrError.withFileName(TokenMgrError.java:124)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:44)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:154)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:148)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:117)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:79)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:90)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:74)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:162)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:142)
	at net.sourceforge.pmd.cpd.CPD.runCpd(CPD.java:225)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:196)

```
# Copy-paste the stack trace here
```

The tokenizer fails on the single quote in the following fragment (see _doesn't really matter_):

`.macro __RESTORE_REGFILE_SOFT

	LD2	gp, fp, PT_r26		; gp (r26), fp (r27)

	ld	r12, [sp, PT_r12]
	ld	r30, [sp, PT_r30]

	; Restore SP (into AUX_USER_SP) only if returning to U mode
	;  - for K mode, it will be implicitly restored as stack is unwound
	;  - Z flag set on K is inverse of what hardware does on interrupt entry
	;    but that doesn't really matter
	bz	1f
	ld	r10, [sp, PT_sp]	; SP (pt_regs->sp)
	sr	r10, [AUX_USER_SP]
1:
`
The tokenizer fails on the single quote in the following fragment (see _doesn't really matter_):

```C
.macro __RESTORE_REGFILE_SOFT

	LD2	gp, fp, PT_r26		; gp (r26), fp (r27)

	ld	r12, [sp, PT_r12]
	ld	r30, [sp, PT_r30]

	; Restore SP (into AUX_USER_SP) only if returning to U mode
	;  - for K mode, it will be implicitly restored as stack is unwound
	;  - Z flag set on K is inverse of what hardware does on interrupt entry
	;    but that doesn't really matter
	bz	1f
	ld	r10, [sp, PT_sp]	; SP (pt_regs->sp)
	sr	r10, [AUX_USER_SP]
1:
```

**Steps to reproduce:**
1. Clone the repo 'https://github.com/torvalds/linux/' to your machine, say into ~/tmp/linux
2.  Run CPD from the command line: .../pmd-bin-6.51.0/bin/run.sh cpd --minimum-tokens 100 --files ~/tmp/linux --language c

**Comment by UncleOwen** [comment]
```none
$ ~/pmd-bin-7.16.0/bin/pmd cpd --minimum-tokens 100 --dir=linux/arch/arc/include/asm --language=cpp
[ERROR] Skipping file: Lexical error in file 'linux/arch/arc/include/asm/entry-arcv2.h' at line 199, column 1: "\n" (10), after : "\'t really matter" (in lexical state DEFAULT)
[ERROR] Skipping file: Lexical error in file 'linux/arch/arc/include/asm/entry-compact.h' at line 48, column 11: "a" (97), after : "\\" (in lexical state DEFAULT)
[ERROR] Skipping file: Lexical error in file 'linux/arch/arc/include/asm/entry.h' at line 67, column 7: "o" (111), after : "\\" (in lexical state DEFAULT)
[ERROR] Skipping file: Lexical error in file 'linux/arch/arc/include/asm/irqflags-compact.h' at line 186, column 6: "s" (115), after : "\\" (in lexical state DEFAULT)
[ERROR] Skipping file: Lexical error in file 'linux/arch/arc/include/asm/linkage.h' at line 19, column 7: "e" (101), after : "\\" (in lexical state DEFAULT)
[ERROR] Skipping file: Lexical error in file 'linux/arch/arc/include/asm/mmu-arcv2.h' at line 98, column 6: "r" (114), after : "\\" (in lexical state DEFAULT)
```
