### ISSUE TITLE
[core] Can't analyze sources in zip files

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4248]
**Affects PMD Version:** since 6.44.0

**Description:**

When specifying a zip file to analyze, PMD fails with the following exception:

**Exception Stacktrace:**

```
FINE: java.nio.file.ProviderNotFoundException: Provider "zip" not found
	at java.base/java.nio.file.FileSystems.getFileSystem(FileSystems.java:238)
	at net.sourceforge.pmd.lang.document.FileCollector.addZipFile(FileCollector.java:319)
	at net.sourceforge.pmd.internal.util.FileCollectionUtil.addRoot(FileCollectionUtil.java:132)
	at net.sourceforge.pmd.internal.util.FileCollectionUtil.collectFiles(FileCollectionUtil.java:97)
	at net.sourceforge.pmd.internal.util.FileCollectionUtil.collectFiles(FileCollectionUtil.java:70)
	at net.sourceforge.pmd.PmdAnalysis.create(PmdAnalysis.java:113)
	at net.sourceforge.pmd.PMD.doPMD(PMD.java:247)
	at net.sourceforge.pmd.PMD.runPmd(PMD.java:505)
	at net.sourceforge.pmd.PMD.runPmd(PMD.java:472)
	at net.sourceforge.pmd.PMD.main(PMD.java:418)
```

**Code Sample demonstrating the issue:**

```shell
$ ~/PMD/binaries/pmd-bin-6.51.0/bin/run.sh pmd -d target/maven-pmd-plugin-it-Smoke-1.0-SNAPSHOT-sources.jar -R rulesets/java/quickstart.xml -f text
Nov 24, 2022 9:53:36 AM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
SEVERE: Cannot open zip file target/maven-pmd-plugin-it-Smoke-1.0-SNAPSHOT-sources.jar: Provider "zip" not found
Nov 24, 2022 9:53:37 AM net.sourceforge.pmd.PMD encourageToUseIncrementalAnalysis
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.51.0/pmd_userdocs_incremental_analysis.html
```

**Running PMD through:** *[CLI]*

Note: found in https://github.com/pmd/pmd/pull/4214#issuecomment-1326164746

**Comment by jsotuyod** [comment]
As per [this docs](https://docs.oracle.com/javase/7/docs/technotes/guides/io/fsp/zipfilesystemprovider.html) it seems that:

1. the scheme should not be `zip`, but `jar`
2. we may need to call `FileSystems.newFileSystem(zipUri, null)` instead of `FileSystems.getFileSystem(zipUri)`
