### ISSUE TITLE
[core] A crash upon PMD initialization

### ISSUE THREAD

**Issue by LynnBroe** [pmd/pmd#4267]
**Affects PMD Version:6.50.0** 

**Description:**

I run PMD to detect the following code example, and it crashed.

**Exception Stacktrace:**

```
Exception in thread "main" java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.Class[] com.beust.jcommander.Parameter.validateValueWith() (Found data of type class java.lang.Class[class net.sourceforge.pmd.cli.PMDParameters$RulePriorityValidator])
	at java.base/sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:57)
	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:86)
	at com.sun.proxy.$Proxy1.validateValueWith(Unknown Source)
	at com.beust.jcommander.WrappedParameter.validateValueWith(WrappedParameter.java:64)
	at com.beust.jcommander.ParameterDescription.validateValueParameter(ParameterDescription.java:350)
	at com.beust.jcommander.ParameterDescription.validateDefaultValues(ParameterDescription.java:164)
	at com.beust.jcommander.ParameterDescription.init(ParameterDescription.java:157)
	at com.beust.jcommander.ParameterDescription.<init>(ParameterDescription.java:65)
	at com.beust.jcommander.JCommander.addDescription(JCommander.java:631)
	at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:601)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:252)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:238)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:230)
	at net.sourceforge.pmd.cli.PmdParametersParseResult.extractParameters(PmdParametersParseResult.java:104)
	at net.sourceforge.pmd.PMD.runPmd(PMD.java:452)
	at net.sourceforge.pmd.PMD.main(PMD.java:418)
	at /class/path/of/my/code
```

**Code Sample demonstrating the issue:**

```java
@org.junit.jupiter.api.Test
void foo() {
    synchronized (this) {}
}
```

**Steps to reproduce:**
Directly use PMD to detect the code example.

**Running PMD through:** *[Maven]*

**Comment by jsotuyod** [comment]
@LynnBroe thanks for the report. This has nothing to do with the actual code being analyzed, it's on PMD's startup, as it parses the CLI parameters… now, this is a little curious:

- you claim to be running PMD through Maven, not the CLI, so CLI arg parsing shouldn't happen…
- you claim to be running PMD through Maven, yet your edited stacktrace claims to include your own custom code…

Can we validate the report is accurate? I'd guess you are not using Maven, but invoking PMD from within your own code, and if that's the case, this is an issue on your codebase. More probably than not, you are using a different version of `com.beust.jcommander` than the one PMD uses, and the binary incompatibility is triggering this exception.

**Comment by rfevang** [comment]
I see this error when running PMD in Bazel, if my jcommander version is newer than 1.64 (1.69 is broken, version in between are not in maven central). I don't know whether the issue is in jcommander or pmd.

**Comment by jsotuyod** [comment]
This is down to how the host tool integrates PMD. An incorrect classpath (ie: including non-compatible dependencies) is going to break and is outside our control.

Having said that, PMD 7 no longer uses jCommander, favoring PicoCli instead, and the CLI code is split away under a separate module that integrators can (and probably should) leave out integrating directly through `PmdAnalysis` (programatically) or the Ant task (ie: Gradle, Maven).
