### ISSUE TITLE
[plsql] Parsing exception COMPOUND TRIGGER with EXCEPTION handler

### ISSUE THREAD

**Issue by hgodinez89** [pmd/pmd#4270]
**Affects PMD Version:** 

This error was testing in the following versions:
- 6.52.0
- 6.51.0
- 7.0.0 (see comments below)

**Description:**

Trying to analyze pl/sql code in a Compound Trigger PMD raises an exception error that indicates "Error while parsing".

**Exception Stacktrace:**

```
net.sourceforge.pmd.PMDException: Error while parsing C:\testfolder\example_trigger.sql
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:124)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:100)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:62)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:85)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: net.sourceforge.pmd.lang.plsql.ast.ParseException: Encountered "  "l_number_one "" at line 5, column 4.
Was expecting:
    "BEGIN" ...
    
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.generateParseException(PLSQLParser.java)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.jj_consume_token(PLSQLParser.java)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.TriggerTimingPointSection(PLSQLParser.java:53993)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.CompoundTriggerBlock(PLSQLParser.java:54808)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.TriggerUnit(PLSQLParser.java:53919)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Input(PLSQLParser.java:143)
	at net.sourceforge.pmd.lang.plsql.PLSQLParser.parse(PLSQLParser.java:61)
	at net.sourceforge.pmd.lang.AbstractParser.doParse(AbstractParser.java:44)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:136)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:200)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:118)
	... 10 more
```

**Code Sample demonstrating the issue:**

```sql
--
-- CREATE TABLE ONLY FOR INSTALLATION PURPOSES IN A DATABASE
CREATE TABLE TEST_TABLE
(
  COL_ONE    VARCHAR2(10),
  COL_TWO    VARCHAR2(10),
  COL_THREE  VARCHAR2(10)
);
--
-- TRIGGER EXAMPLE
CREATE OR REPLACE TRIGGER EXAMPLE_TRIGGER
   FOR INSERT ON TEST_TABLE
   COMPOUND TRIGGER
   --
   l_number_one NUMBER(2) := ROUND(DBMS_RANDOM.Value(1, 10));
   l_number_two NUMBER(2) := ROUND(DBMS_RANDOM.Value(1, 10));
   --
   BEFORE EACH ROW IS
      --
      l_tot_numbers NUMBER(2);
      --
   BEGIN
      --
      l_tot_numbers := l_number_one + l_number_two;
      --
      :NEW.col_one   := l_number_one;
      :NEW.col_two   := l_number_two;
      :NEW.col_three := l_tot_numbers;
      --
   EXCEPTION
      WHEN OTHERS THEN
         RAISE_APPLICATION_ERROR(-20001, 'ERROR AT EXAMPLE_TRIGGER - BEFORE EACH ROW' || CHR(10) || SQLERRM);
   END BEFORE EACH ROW;
   --
   --
   AFTER STATEMENT IS
   BEGIN
      --
      DBMS_OUTPUT.Put_Line('This is just an example!');
      --
   EXCEPTION
      WHEN OTHERS THEN
         RAISE_APPLICATION_ERROR(-20002, 'ERROR AT EXAMPLE_TRIGGER - AFTER STATEMENT' || CHR(10) || SQLERRM);
   END AFTER STATEMENT;
   --
END EXAMPLE_TRIGGER;
```

**Steps to reproduce:**

1. Put the code above _("Code Sample demonstrating the issue" section)_ in example_trigger.sql
2. Execute PMD analyzer from CLI.
3. See the error showed in the _"Exception Stacktrace" section_.

**Running PMD through:** *[CLI]*

**Comment by adangel** [comment]
The issue is still reproducible under PMD 7.0.0.
However with a different stack trace, as COMPOUND TRIGGERS are generally supported (https://github.com/pmd/pmd/blob/7da809b462347a9891881e28d74f8ea8fa1925fc/pmd-plsql/etc/grammar/PLSQL.jjt#L4564)

The stacktrace now is this:

```
net.sourceforge.pmd.lang.ast.ParseException: Parse exception in file '/home/andreas/PMD/source/pmd/pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/CompoundTrigger.pls' at line 20, column 7: Encountered <IDENTIFIER: "l_tot_numbers">.
Was expecting:
    "BEGIN" ...

	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParserImpl.generateParseException(PLSQLParserImpl.java)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParserImpl.jj_consume_token(PLSQLParserImpl.java)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParserImpl.TriggerTimingPointSection(PLSQLParserImpl.java:54317)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParserImpl.CompoundTriggerBlock(PLSQLParserImpl.java:55130)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParserImpl.TriggerUnit(PLSQLParserImpl.java:54243)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParserImpl.Input(PLSQLParserImpl.java:120)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.parseImpl(PLSQLParser.java:25)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.parseImpl(PLSQLParser.java:14)
	at net.sourceforge.pmd.lang.ast.impl.javacc.JjtreeParserAdapter.parse(JjtreeParserAdapter.java:36)
	at net.sourceforge.pmd.lang.test.ast.BaseParsingHelper.parseImpl(BaseParsingHelper.kt:160)
	at net.sourceforge.pmd.lang.test.ast.BaseParsingHelper.doParse(BaseParsingHelper.kt:146)
	at net.sourceforge.pmd.lang.test.ast.BaseParsingHelper.parse(BaseParsingHelper.kt:135)
	at net.sourceforge.pmd.lang.test.ast.BaseParsingHelper.parse$default(BaseParsingHelper.kt:125)
	at net.sourceforge.pmd.lang.test.ast.BaseTreeDumpTest$doTest$1.invoke(BaseTreeDumpTest.kt:37)
	at net.sourceforge.pmd.lang.test.ast.BaseTreeDumpTest$doTest$1.invoke(BaseTreeDumpTest.kt:35)
	at net.sourceforge.pmd.lang.test.BaseTextComparisonTest.doTest$pmd_lang_test(BaseTextComparisonTest.kt:46)
	at net.sourceforge.pmd.lang.test.ast.BaseTreeDumpTest.doTest(BaseTreeDumpTest.kt:35)
	at net.sourceforge.pmd.lang.test.ast.BaseTreeDumpTest.doTest$default(BaseTreeDumpTest.kt:34)
	at net.sourceforge.pmd.lang.test.ast.BaseTreeDumpTest.doTest(BaseTreeDumpTest.kt)
	at net.sourceforge.pmd.lang.plsql.ast.PlsqlTreeDumpTest.parseCompoundTrigger(PlsqlTreeDumpTest.java:47)
```

This is failing at:

```sql
BEFORE EACH ROW IS
      --
      l_tot_numbers NUMBER(2); -- expected BEGIN, not a declaration...
      --
   BEGIN
```

In our grammar: https://github.com/pmd/pmd/blob/7da809b462347a9891881e28d74f8ea8fa1925fc/pmd-plsql/etc/grammar/PLSQL.jjt#L4543-L4560

There is nothing in between `IS` and `BEGIN` allowed. This is also, what is officially documented: [compound_trigger_block](https://docs.oracle.com/en/database/oracle/oracle-database/23/lnpls/CREATE-TRIGGER-statement.html#GUID-AF9E33F1-64D1-4382-A6A4-EC33C36F237B__CJACFCDJ)
For timing_point_section, there is nothing allowed between `IS` and `BEGIN`.

So, this looks like invalid PLSQL to me.

However, when I remove this line, parsing fails on `EXCEPTION` - which is indeed not supported by our grammar, but is valid PLSQL (see tps_body).

Are there any PLSQL experts that can confirm, that the code snippet is invalid syntax?
