### ISSUE TITLE
[java] StackOverflowError parsing complex infix operation

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#4358]
**Affects PMD Version:** 

PMD 7.0.0-SNAPSHOT

**Description:**

When transversing the AST for [this file](https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLongConcatenatedString.java) PMD fails with a StackOverflowError.

Since InFixOperations are parsed as recursive tail descent structure, a new node is created per concat. Notice the parser itself succeeds, but transversing fails

**Exception Stacktrace:**

```
java.lang.StackOverflowError
	at net.sourceforge.pmd.lang.ast.internal.StreamImpl.children(StreamImpl.java:78)
	at net.sourceforge.pmd.lang.ast.Node.children(Node.java:536)
	at net.sourceforge.pmd.lang.ast.impl.GenericNode.children(GenericNode.java:64)
	at net.sourceforge.pmd.lang.ast.AstVisitorBase.visitChildren(AstVisitorBase.java:29)
	at net.sourceforge.pmd.lang.ast.AstVisitorBase.visitNode(AstVisitorBase.java:37)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitor.visitJavaNode(JavaVisitor.java:6)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visitExpression(JavaVisitorBase.java:132)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visit(JavaVisitorBase.java:153)
	at net.sourceforge.pmd.lang.java.ast.ASTInfixExpression.acceptVisitor(ASTInfixExpression.java:51)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.acceptVisitor(AbstractJavaNode.java:38)
	at net.sourceforge.pmd.lang.ast.AstVisitorBase.visitChildren(AstVisitorBase.java:30)

	at net.sourceforge.pmd.lang.ast.AstVisitorBase.visitNode(AstVisitorBase.java:37)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitor.visitJavaNode(JavaVisitor.java:6)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visitExpression(JavaVisitorBase.java:132)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visit(JavaVisitorBase.java:153)
	at net.sourceforge.pmd.lang.java.ast.ASTInfixExpression.acceptVisitor(ASTInfixExpression.java:51)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.acceptVisitor(AbstractJavaNode.java:38)
	at net.sourceforge.pmd.lang.ast.AstVisitorBase.visitChildren(AstVisitorBase.java:30)

this blocks repeats 
```

**Code Sample demonstrating the issue:**

See [this file](https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLongConcatenatedString.java)

**Comment by jsotuyod** [comment]
On a preliminary review, the methods repeated tend to have a well defined intent / are needed to force the compiler to pick the right method.

Having said, that, there are some methods that are solely there for quality of life improvements. For instance:
`net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visitExpression(JavaVisitorBase.java:132)`, which is not a standard `visit` method, but allows for a catch-all method for all expression types. This is one of the 7 calls in the stack per AST depth level, but has only 1 user: `ClassFanOutVisitor`. Others, such as `visitPrimaryExpr` or `visitNamedExpr` are never used. `visitLiteral` has 2 overrides, but is not subject to the same recursion issues due to the language's natuve.

**Comment by oowekyala** [comment]
I think this problem will always occur given a sufficiently nested expression and the nature of our visitors today. If we remove some of those visit methods (which I agree could be an option, they're never used), we will still have the issue if we make a bigger string concatenation.

For now I've ignored it, as that kind of expression basically only occurs in generated code, or, like here, in code purposefully written to stress the compiler front-end.

Ages ago I built a new visitor type that doesn't use the call stack as much to fix this. This visitor type doesn't have this issue but we would need to make _all_ our visitors use it. For instance here the issue shows up in the symbol table resolver (I think). If we fix this visitor, the error will then show up in some other processing passes. Once they're all fixed, rules that use recursive descent will start to fail. It's unclear to me whether it's worth implementing this solution at all. 

FWIW here is my old attempt: https://github.com/pmd/pmd/compare/master...oowekyala:pmd:stackoverflows

**Comment by ron190** [comment]
Hi, issue seems to reproduce randomly, and retrying the job can make the analysis pass.
- Run#1: https://github.com/ron190/jsql-injection/actions/runs/9555292737/job/26338220453
```java
 constituent[48]: file:/usr/share/maven/lib/plexus-component-annotations-2.1.0.jar
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
	at net.sourceforge.pmd.lang.java.ast.JavaVisitor.visitJavaNode(JavaVisitor.java:6)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visitExpression(JavaVisitorBase.java:132)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visit(JavaVisitorBase.java:153)
	at net.sourceforge.pmd.lang.java.ast.ASTInfixExpression.acceptVisitor(ASTInfixExpression.java:45)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.acceptVisitor(AbstractJavaNode.java:38)
	at net.sourceforge.pmd.lang.java.ast.AstDisambiguationPass$DisambigVisitor.visitChildren(AstDisambiguationPass.java:92)
	at net.sourceforge.pmd.lang.java.ast.AstDisambiguationPass$DisambigVisitor.visitChildren(AstDisambiguationPass.java:80)
	at net.sourceforge.pmd.lang.ast.AstVisitorBase.visitNode(AstVisitorBase.java:38)
        ...
	at net.sourceforge.pmd.lang.java.ast.JavaVisitor.visitJavaNode(JavaVisitor.java:6)
```
- Run#2: https://github.com/ron190/jsql-injection/actions/runs/9535827841/job/26282052324
```java
constituent[48]: file:/usr/share/maven/lib/maven-resolver-impl-1.9.20.jar
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
	at net.sourceforge.pmd.lang.java.ast.JavaVisitor.visitJavaNode(JavaVisitor.java:6)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visitExpression(JavaVisitorBase.java:132)
	at net.sourceforge.pmd.lang.java.ast.JavaVisitorBase.visit(JavaVisitorBase.java:153)
	at net.sourceforge.pmd.lang.java.ast.ASTInfixExpression.acceptVisitor(ASTInfixExpression.java:45)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.acceptVisitor(AbstractJavaNode.java:38)
	at net.sourceforge.pmd.lang.java.ast.AstDisambiguationPass$DisambigVisitor.visitChildren(AstDisambiguationPass.java:92)
	at net.sourceforge.pmd.lang.java.ast.AstDisambiguationPass$DisambigVisitor.visitChildren(AstDisambiguationPass.java:80)
	at net.sourceforge.pmd.lang.ast.AstVisitorBase.visitNode(AstVisitorBase.java:38)
        ...
	at net.sourceforge.pmd.lang.java.ast.JavaVisitor.visitJavaNode(JavaVisitor.java:6)
```
