### ISSUE TITLE
[java] Type resolution fails with NPE when the scope is not a type declaration

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#4359]
**Affects PMD Version:** 

PMD 7.0.0-SNAPSHOT

**Description:**

When performing type resolution, if a symbol is unresolved, PMD will try to look it as a local member, but in doing so, assumes that the current context is a type declaration. This unfortunately isn't always true, and when that happens, an NPE occurs.

https://github.com/pmd/pmd/blob/596cc2694d04bd2132aa05058551e01069c453cd/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/ast/LazyTypeResolver.java#L569-L576

Notice the `node.getEnclosingtType()` call.

**Exception Stacktrace:**

```
org.apache.commons.lang3.exception.ContextedRuntimeException: java.lang.NullPointerException
Exception Context:
	[1:Resolving type of=!debug only! [FieldAccess:1:116]javax.xml.bind.annotation.XmlNsForm.QUALIFIED]
---------------------------------
	at net.sourceforge.pmd.internal.util.AssertionUtil.contexted(AssertionUtil.java:231)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.getTypeMirror(AbstractJavaTypeNode.java:54)
	at net.sourceforge.pmd.lang.java.ast.ASTFieldAccess.getTypeMirror(ASTFieldAccess.java:24)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.getTypeMirror(AbstractJavaTypeNode.java:39)
	at net.sourceforge.pmd.lang.java.ast.ASTFieldAccess.getTypeMirror(ASTFieldAccess.java:24)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.forceTypeResolution(AbstractJavaTypeNode.java:29)
	at net.sourceforge.pmd.lang.java.ast.ASTFieldAccess.getSignature(ASTFieldAccess.java:66)
	at net.sourceforge.pmd.lang.java.ast.ASTFieldAccess.getSignature(ASTFieldAccess.java:24)
	at net.sourceforge.pmd.lang.java.ast.ASTAssignableExpr$ASTNamedReferenceExpr.getReferencedSym(ASTAssignableExpr.java:84)
	at net.sourceforge.pmd.lang.java.ast.ASTFieldAccess.getReferencedSym(ASTFieldAccess.java:72)
	at net.sourceforge.pmd.lang.java.ast.ASTFieldAccess.getReferencedSym(ASTFieldAccess.java:24)
	at net.sourceforge.pmd.lang.java.ast.InternalApiBridge.lambda$usageResolution$1(InternalApiBridge.java:105)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at net.sourceforge.pmd.lang.ast.internal.IteratorBasedNStream.forEach(IteratorBasedNStream.java:102)
	at net.sourceforge.pmd.lang.java.ast.InternalApiBridge.usageResolution(InternalApiBridge.java:104)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.lambda$process$5(JavaAstProcessor.java:181)
	at net.sourceforge.pmd.benchmark.TimeTracker.bench(TimeTracker.java:163)
	at net.sourceforge.pmd.lang.java.internal.JavaAstProcessor.process(JavaAstProcessor.java:181)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.parseImpl(JavaParser.java:52)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.parseImpl(JavaParser.java:21)
	at net.sourceforge.pmd.lang.ast.impl.javacc.JjtreeParserAdapter.parse(JjtreeParserAdapter.java:36)
	at net.sourceforge.pmd.processor.PmdRunnable.parse(PmdRunnable.java:119)
	at net.sourceforge.pmd.processor.PmdRunnable.processSource(PmdRunnable.java:144)
	at net.sourceforge.pmd.processor.PmdRunnable.run(PmdRunnable.java:87)
	at net.sourceforge.pmd.processor.MonoThreadProcessor.processFiles(MonoThreadProcessor.java:28)
	at net.sourceforge.pmd.PmdAnalysis.performAnalysisImpl(PmdAnalysis.java:309)
	at net.sourceforge.pmd.PmdAnalysis.performAnalysisImpl(PmdAnalysis.java:274)
	at net.sourceforge.pmd.PmdAnalysis.performAnalysis(PmdAnalysis.java:254)
	at net.sourceforge.pmd.PmdAnalysis.runAndReturnStats(PmdAnalysis.java:417)
	at net.sourceforge.pmd.cli.commands.internal.PmdCommand.execute(PmdCommand.java:337)
	at net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand.call(AbstractPmdSubcommand.java:35)
	at net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand.call(AbstractPmdSubcommand.java:20)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at net.sourceforge.pmd.cli.PmdCli.main(PmdCli.java:18)
Caused by: java.lang.NullPointerException
	at net.sourceforge.pmd.lang.java.types.ast.LazyTypeResolver.visit(LazyTypeResolver.java:576)
	at net.sourceforge.pmd.lang.java.types.ast.LazyTypeResolver.visit(LazyTypeResolver.java:95)
	at net.sourceforge.pmd.lang.java.ast.ASTFieldAccess.acceptVisitor(ASTFieldAccess.java:81)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.getTypeMirror(AbstractJavaTypeNode.java:51)
	... 39 more
```

**Code Sample demonstrating the issue:**

A `package-info.java` file with:

```java
@javax.xml.bind.annotation.XmlSchema(attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package foo;
```

Even though `javax.xml.bind.annotation.XmlNsForm.QUALIFIED` is a FQCN, if the class is not in the auxclasspath, the error triggers.

**Comment by oowekyala** [comment]
Fixed for PMD 7.0.0 via d31b8f6
