### ISSUE TITLE
严重: An error occurred while executing cpd.

### ISSUE THREAD

**Issue by KillWilde** [pmd/pmd#4394]
NSString * regex = @"^([\\[\\]\{\\}\\*\\'#%+=_|~<>•.,?!-/:;()$&@\\s]|\\w){4,15}$"; 

 Encountered: Lexical error at line 162, column 36.  Encountered: "{" (123), after : "\"^([\\\\[\\\\]\\" (in lexical state 0)
	at net.sourceforge.pmd.lang.ast.TokenMgrError.withFileName(TokenMgrError.java:124)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:44)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:145)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:140)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:109)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:72)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:82)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:67)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:162)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:142)
	at net.sourceforge.pmd.cpd.CPD.runCpd(CPD.java:207)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:185)
2月 16, 2023 1:19:00 下午 net.sourceforge.pmd.cpd.CPD runCpd
严重: An error occurred while executing cpd.

**Comment by adangel** [comment]
Thanks for reporting.
NSString sounds like swift? Can you confirm, that you are checking swift sources?

**Comment by KillWilde** [comment]
I'm using objectc sources发自我的 iPhone在 2023年2月16日，16:36，Andreas Dangel ***@***.***> 写道：﻿
Thanks for reporting.
NSString sounds like swift? Can you confirm, that you are checking swift sources?
