### ISSUE TITLE
WARNING: Exception applying rule CyclomaticComplexity on file C:\application\standardtext.sql, continuing with next rule java.util.EmptyStackException

### ISSUE THREAD

**Issue by Rajashekarg12** [pmd/pmd#4480]
WARNING: Exception applying rule CyclomaticComplexity on file C:\application\standard.sql, continuing with next rule
java.util.EmptyStackException
        at java.util.Stack.peek(Stack.java:102)
        at net.sourceforge.pmd.lang.plsql.rule.design.CyclomaticComplexityRule.visit(CyclomaticComplexityRule.java:136)
        at net.sourceforge.pmd.lang.plsql.ast.ASTExceptionHandler.jjtAccept(ASTExceptionHandler.java:22)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:327)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:354)
        at net.sourceforge.pmd.lang.plsql.ast.ASTBlock.jjtAccept(ASTBlock.java:22)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:327)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:507)
        at net.sourceforge.pmd.lang.plsql.ast.ASTUnlabelledStatement.jjtAccept(ASTUnlabelledStatement.java:22)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:327)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:512)
        at net.sourceforge.pmd.lang.plsql.ast.ASTStatement.jjtAccept(ASTStatement.java:22)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:327)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:354)
        at net.sourceforge.pmd.lang.plsql.ast.ASTBlock.jjtAccept(ASTBlock.java:22)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:327)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:349)
        at net.sourceforge.pmd.lang.plsql.ast.ASTGlobal.jjtAccept(ASTGlobal.java:22)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:327)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visit(AbstractPLSQLRule.java:334)
        at net.sourceforge.pmd.lang.plsql.rule.design.CyclomaticComplexityRule.visit(CyclomaticComplexityRule.java:102)
        at net.sourceforge.pmd.lang.plsql.ast.ASTInput.jjtAccept(ASTInput.java:27)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.visitAll(AbstractPLSQLRule.java:261)
        at net.sourceforge.pmd.lang.plsql.rule.AbstractPLSQLRule.apply(AbstractPLSQLRule.java:254)
        at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:336)
        at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:670)
        at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:163)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:209)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:118)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:100)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:62)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:89)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by adangel** [comment]
Thanks for the report. Is it possible to share the file `C:\application\standard.sql`, so that we can reproduce the problem?
