### ISSUE TITLE
[HTML] Colon not supported in Attributes

### ISSUE THREAD

**Issue by DougMidgley** [pmd/pmd#4626]
**Affects PMD Version:** 
PMD 7.0.0-rc3

**Description:**
When building xpath rules, I have the need to be able to filter for attributes in HTML elements with contain colons (ie. if:true=xyz).
Example of xpath which supports this can be found here https://stackoverflow.com/questions/10894696/how-to-retrieve-value-of-an-attribute-which-contains-colon-in-the-attribute-name
It seems that colon is breaking something, without it, no issues.

when trying in designer with HTML xpath

`//@*[name()='v:click']`

the following does not correctly work.

Validating using http://xpather.com/ correctly works for this

**Exception Stacktrace:**

![image](https://github.com/pmd/pmd/assets/22379388/296310e9-6410-4ff4-a359-280a9a6fadf1)
Show the error in Designer.

**Code Sample demonstrating the issue:**

```
<input class="anniucssC" type="button" value="当页累计" v:click="doThisPageTtl()"/>
<input class="anniucssC" type="button" value="全部累计" v:click="doAllTtl()"/>
<input class="anniucssC" type="button" value="选择累计" v:click="doChoiceTtl()"/>
<input class="anniucssC" type="button" value="打印" v-click="showLayer('shadow123','question12
3');"/>
```

**Steps to reproduce:**

1. open designer
2. copy code example
3. copy xpath rule
4. see error
5. replicate on xpather and no error occurs

**Running PMD through:** Designer

**Comment by adangel** [comment]
Thanks for the report.

<details>
  <summary>the full stacktrace</summary>

```
net.sourceforge.pmd.util.fxdesigner.model.XPathEvaluationException: net.sourceforge.pmd.lang.rule.xpath.PmdXPathException: net.sf.saxon.trans.XPathException: XPath rule expression returned a non-node (class net.sourceforge.pmd.lang.rule.xpath.internal.AstAttributeNode): net.sourceforge.pmd.lang.rule.xpath.internal.AstAttributeNode@853f53e7
Exception Context:
	[1:Kind=Unknown error]
	[2:Phase=EVALUATION]
	[3:Expression=//@*[name()='v:click']]
	[4:Version=3.1]
	[5:Location in expr=null]
---------------------------------
	at net.sourceforge.pmd.util.fxdesigner.model.XPathEvaluator.evaluateQuery(XPathEvaluator.java:103)
	at net.sourceforge.pmd.util.fxdesigner.app.XPathUpdateSubscriber.lambda$init$1(XPathUpdateSubscriber.java:59)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.MappedStream.lambda$observeInputs$0(MappedStream.java:25)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.FilterStream.lambda$observeInputs$0(FilterStream.java:20)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.HookStream.lambda$observeInputs$0(HookStream.java:29)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at net.sourceforge.pmd.util.fxdesigner.util.reactfx.DistinctBetweenStream.lambda$observeInputs$1(DistinctBetweenStream.java:48)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.EventSource.push(EventSource.java:18)
	at net.sourceforge.pmd.util.fxdesigner.app.MessageChannel.pushEvent(MessageChannel.java:92)
	at net.sourceforge.pmd.util.fxdesigner.XPathRuleEditorController.lambda$beforeParentInit$6(XPathRuleEditorController.java:167)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.MappedStream.lambda$observeInputs$0(MappedStream.java:25)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.SuccessionReducingStream.handleTimeout(SuccessionReducingStream.java:73)
	at org.reactfx.util.FxTimer.lambda$restart$0(FxTimer.java:89)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.animation.Timeline.doPlayTo(Timeline.java:172)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.animation.Animation.doTimePulse(Animation.java:1189)
	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:207)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.animation.Animation$1.timePulse(Animation.java:206)
	at com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:571)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: net.sourceforge.pmd.lang.rule.xpath.PmdXPathException: net.sf.saxon.trans.XPathException: XPath rule expression returned a non-node (class net.sourceforge.pmd.lang.rule.xpath.internal.AstAttributeNode): net.sourceforge.pmd.lang.rule.xpath.internal.AstAttributeNode@853f53e7
Exception Context:
	[1:Kind=Unknown error]
	[2:Phase=EVALUATION]
	[3:Expression=//@*[name()='v:click']]
	[4:Version=3.1]
	[5:Location in expr=null]
---------------------------------
	at net.sourceforge.pmd.lang.rule.xpath.internal.SaxonXPathRuleQuery.wrapException(SaxonXPathRuleQuery.java:149)
	at net.sourceforge.pmd.lang.rule.xpath.internal.SaxonXPathRuleQuery.evaluate(SaxonXPathRuleQuery.java:142)
	at net.sourceforge.pmd.util.fxdesigner.model.XPathEvaluator.evaluateQuery(XPathEvaluator.java:100)
	... 62 more
Caused by: net.sf.saxon.trans.XPathException: XPath rule expression returned a non-node (class net.sourceforge.pmd.lang.rule.xpath.internal.AstAttributeNode): net.sourceforge.pmd.lang.rule.xpath.internal.AstAttributeNode@853f53e7
	at net.sourceforge.pmd.lang.rule.xpath.internal.SaxonXPathRuleQuery.evaluate(SaxonXPathRuleQuery.java:132)
	... 63 more
```

</details>


The important message here is: "XPath rule expression returned a non-node (class net.sourceforge.pmd.lang.rule.xpath.internal.AstAttributeNode)"

The nodes of the PMD AST of an HTML document are the elements - your XPath expression is searching for attributes. On these nodes, violations can be reported. These nodes are also displayed on the right in the designer. As you can see, there are no attributes in the tree. That means, you need to phrase your query a bit different - instead of searching attributes, you need to search elements with certain constraints (such as specific attributes).

The following XPath expression will find any **elements** that have an attribute with the name "v:click":

```
//*[@*[name()='v:click']]
```

I'm closing this issue as won't fix, as PMD works as expected.

Feel free to comment further, if the above XPath expression doesn't work for you.

**Comment by DougMidgley** [comment]
@adangel  - Super! works a charm! appreciate the support here!
