### ISSUE TITLE
[ant] Language java is not supported. Available languages: []

### ISSUE THREAD

**Issue by ZhuTingyu** [pmd/pmd#4658]
Java version "17.0.2" 
ant version 1.10.14 
pmd version：7.0.0
build.xml：
```
<project name="MyProject" default="cpd">
  <taskdef name="cpd" classname="net.sourceforge.pmd.ant.CPDTask">
    <classpath>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-java-7.0.0-rc3.jar"/>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-cli-7.0.0-rc3.jar"/>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-java-7.0.0-rc3.jar"/>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-core-7.0.0-rc3.jar"/>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-ant-7.0.0-rc3.jar"/>
    </classpath>
  </taskdef>
  <target name="cpd">
    <cpd minimumTokenCount="100" encoding="UTF-8" ignoreIdentifiers="true"
            ignoreLiterals="true" ignoreAnnotations="true"
            outputFile="/Users/quietzhu/Desktop/tool/output.text">
      <fileset dir="/Users/quietzhu/AndroidStudioProjects/recruitment_android">
          <include name="*.java"/>
      </fileset>
    </cpd>
  </target>
</project>
```

execute ant report an error：Language java is not supported. Available languages: []

**Comment by ZhuTingyu** [comment]
build.xml
<project name="MyProject" default="cpd">
  <taskdef name="cpd" classname="net.sourceforge.pmd.ant.CPDTask">
    <classpath>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-java-7.0.0-rc3.jar"/>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-cli-7.0.0-rc3.jar"/>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-java-7.0.0-rc3.jar"/>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-core-7.0.0-rc3.jar"/>
      <pathelement location="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib/pmd-ant-7.0.0-rc3.jar"/>
    </classpath>
  </taskdef>
  <target name="cpd">
    <cpd minimumTokenCount="100" encoding="UTF-8" ignoreIdentifiers="true"
            ignoreLiterals="true" ignoreAnnotations="true"
            outputFile="/Users/quietzhu/Desktop/tool/output.text">
      <fileset dir="/Users/quietzhu/AndroidStudioProjects/recruitment_android">
          <include name="*.java"/>
      </fileset>
    </cpd>
  </target>
</project>

**Comment by adangel** [comment]
Thanks for the report. It seems, your classpath is not complete. Please use the approach, that is documented for [PMDTask](https://docs.pmd-code.org/latest/pmd_userdocs_tools_ant.html#installation) for the CPDTask as well (which lacks this part):

```xml
<taskdef name="cpd" classname="net.sourceforge.pmd.ant.CPDTask">
    <classpath>
        <fileset dir="/Users/quietzhu/Desktop/tool/pmd-bin-7.0.0-rc3/lib">
            <include name="*.jar"/>
        </fileset>
    </classpath>
  </taskdef>
```

That will also add the dependencies and transitive dependencies that each pmd-jar requires.

I'll try to improve the error message in such case.

For reference, the complete output with incomplete classpath is:
```
Buildfile: /home/andreas/PMD/source/pmd-it/issue-4658-ant-java-not-supported/build.xml

cpd:
      [cpd] Ignoring language for PMD: java.util.ServiceConfigurationError: net.sourceforge.pmd.cpd.Language: Provider net.sourceforge.pmd.cpd.JavaLanguage could not be instantiated

BUILD FAILED
/home/andreas/PMD/source/pmd-it/issue-4658-ant-java-not-supported/build.xml:23: Language java is not supported. Available languages: []

Total time: 0 seconds
```

Debug output doesn't provide more info, why we get the ServiceConfigurationError (e.g. no root cause)

**Comment by adangel** [comment]
It turns out, with the current 7.0.0-SNAPSHOT, the error is displayed a bit different:

```
Buildfile: /home/andreas/PMD/source/pmd-it/issue-4658-ant-java-not-supported/build.xml

cpd:

BUILD FAILED
/home/andreas/PMD/source/pmd-it/issue-4658-ant-java-not-supported/build.xml:33: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at net.sourceforge.pmd.lang.LanguageRegistry.<clinit>(LanguageRegistry.java:39)
	at net.sourceforge.pmd.ant.CPDTask.validateFields(CPDTask.java:188)
	at net.sourceforge.pmd.ant.CPDTask.execute(CPDTask.java:87)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1383)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1338)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1093)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 18 more

Total time: 0 seconds
```

This should give already a hint for a incomplete classpath (ClassNotFoundException...)

If I add slf4j-api and slf4j-simple, then we even get a proper message, which class is missing when trying to instantiate the language java:

```
Buildfile: /home/andreas/PMD/source/pmd-it/issue-4658-ant-java-not-supported/build.xml

cpd:
      [cpd] [main] WARN net.sourceforge.pmd.lang.LanguageRegistry - Cannot load PMD language, ignored
      [cpd] java.util.ServiceConfigurationError: net.sourceforge.pmd.lang.Language: Provider net.sourceforge.pmd.lang.java.JavaLanguageModule could not be instantiated
      [cpd] 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
      [cpd] 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
      [cpd] 	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
      [cpd] 	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
      [cpd] 	at net.sourceforge.pmd.lang.LanguageRegistry.loadLanguages(LanguageRegistry.java:139)
      [cpd] 	at net.sourceforge.pmd.lang.LanguageRegistry.<clinit>(LanguageRegistry.java:42)
      [cpd] 	at net.sourceforge.pmd.ant.CPDTask.validateFields(CPDTask.java:188)
      [cpd] 	at net.sourceforge.pmd.ant.CPDTask.execute(CPDTask.java:87)
      [cpd] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [cpd] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
      [cpd] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
      [cpd] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
      [cpd] 	at org.apache.tools.ant.Task.perform(Task.java:350)
      [cpd] 	at org.apache.tools.ant.Target.execute(Target.java:449)
      [cpd] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
      [cpd] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
      [cpd] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
      [cpd] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [cpd] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
      [cpd] 	at org.apache.tools.ant.Main.runBuild(Main.java:830)
      [cpd] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
      [cpd] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
      [cpd] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
      [cpd] Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
      [cpd] 	at net.sourceforge.pmd.lang.LanguageModuleBase$LanguageMetadata.name(LanguageModuleBase.java:250)
      [cpd] 	at net.sourceforge.pmd.lang.java.JavaLanguageModule.<init>(JavaLanguageModule.java:26)
      [cpd] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
      [cpd] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
      [cpd] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
      [cpd] 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
      [cpd] 	... 21 more
      [cpd] Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
      [cpd] 	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1383)
      [cpd] 	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1338)
      [cpd] 	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1093)
      [cpd] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
      [cpd] 	... 27 more

BUILD FAILED
/home/andreas/PMD/source/pmd-it/issue-4658-ant-java-not-supported/build.xml:31: Language java is not supported. Available languages: 

Total time: 0 seconds
```

I'm going to improve the documentation a bit for CPD and that's it - won't change any code here.
