### ISSUE TITLE
net.sourceforge.pmd.PMDException: Error while processing 

### ISSUE THREAD

**Issue by lovina37** [pmd/pmd#4671]
**Affects PMD Version:** 
6.55.0

**Build.gradle file**
    pmd {
        toolVersion = "$versionPmd"
        ruleSets = []
        ruleSetFiles = rootProject.files("config/pmd/rules.xml")
        ignoreFailures = true
    }

Make sure, to test with the latest PMD version.

**Description:**

**Exception Stacktrace:**

```
net.sourceforge.pmd.PMDException: Error while processing /Users/lovina37/***.java
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:128)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:100)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:62)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:89)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:30)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.(ClassVisitor.java:70)
	at org.objectweb.asm.ClassVisitor.(ClassVisitor.java:57)
	at net.sourceforge.pmd.lang.java.typeresolution.visitors.PMDASMVisitor.(PMDASMVisitor.java:44)
	at net.sourceforge.pmd.lang.java.typeresolution.PMDASMClassLoader.getImportedClasses(PMDASMClassLoader.java:119)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.populateClassName(ClassTypeResolver.java:1643)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:216)
	at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:44)
	at net.sourceforge.pmd.lang.java.typeresolution.TypeResolutionFacade.initializeWith(TypeResolutionFacade.java:21)
	at net.sourceforge.pmd.lang.java.AbstractJavaHandler$5.start(AbstractJavaHandler.java:121)
	at net.sourceforge.pmd.SourceCodeProcessor.usesTypeResolution(SourceCodeProcessor.java:178)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:205)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:118)
	... 10 more
```

**Code Sample demonstrating the issue:**

```java

```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  ... (e.g. if you're using maven: `mvn clean verify`)
2.  ...

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by jsotuyod** [comment]
@lovina37 are you using JDK21 by any chance?

Java 21 is not supported in PMD 6, but it is included in the recent PMD 7 RCs.

**Comment by jsotuyod** [comment]
I'm closing this as stale. Not only did the reporter never provided feedback, but PMD 7 is no longer using `PMDASMClassLoader` to load classes from the auxclasspath.
