### ISSUE TITLE
Not supporting JDK21

### ISSUE THREAD

**Issue by eant60** [pmd/pmd#4682]
I think the current release of PMD is not working with newly-released JDK 21.

====================
doing PMD 7.0.0-rc3 on source using ruleset custom_pmd/ruleset.xml
====================
[main] INFO net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand - Log level is at INFO
[PmdThread 1] ERROR net.sourceforge.pmd.lang.java.symbols.internal.asm.ParseLock - java.lang.IllegalArgumentException: Unsupported class file major version 65
java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)

**Comment by adangel** [comment]
Yes, currently it's not supported, but it's in the works: #4638

**Comment by adangel** [comment]
Duplicate of #4583

**Comment by mirmak4** [comment]
Hello, @adangel any news on this topic ?

**Comment by jsotuyod** [comment]
@mirmak4 current PMD 7 RCs already support JDK21. Support was included in #4638
