### ISSUE TITLE
[doc] Multivalued properties do not accept | as a separator

### ISSUE THREAD

**Issue by ben-manes** [pmd/pmd#4704]
**Affects PMD Version:** 
7.0.0-rc4

**Description:**
After upgrading from 7.0.0-rc3, the analysis logs exceptions. This appears to only be noise as it does not fail the run.

**Exception Stacktrace:**

```console
Exception applying rule LooseCoupling on file /home/runner/work/caffeine/caffeine/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/Feature.java, continuing with next rule
org.apache.commons.lang3.exception.ContextedRuntimeException: java.lang.IllegalArgumentException: Not a Java binary name 'java.util.Properties         |java.util.concurrent.ConcurrentHashMap         |com.google.common.collect.ImmutableMap         |com.google.common.collect.ImmutableSet         |com.google.common.collect.ImmutableList         |com.github.benmanes.caffeine.cache.BoundedLocalCache         |com.github.benmanes.caffeine.cache.UnboundedLocalCache'
Exception Context:
	[1:Rule applied on node=!debug only! [ClassOrInterfaceType:52:24]ImmutableSet<Feature>]
---------------------------------
	at net.sourceforge.pmd.util.AssertionUtil.contexted(AssertionUtil.java:232)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.applyOnIndex(RuleApplicator.java:77)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.apply(RuleApplicator.java:55)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:158)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.processSource(PmdRunnable.java:140)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.run(PmdRunnable.java:80)
	at java.base@20.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base@20.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base@20.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@20.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@20.0.2/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalArgumentException: Not a Java binary name 'java.util.Properties         |java.util.concurrent.ConcurrentHashMap         |com.google.common.collect.ImmutableMap         |com.google.common.collect.ImmutableSet         |com.google.common.collect.ImmutableList         |com.github.benmanes.caffeine.cache.BoundedLocalCache         |com.github.benmanes.caffeine.cache.UnboundedLocalCache'
	at net.sourceforge.pmd.util.AssertionUtil.assertValidJavaBinaryName(AssertionUtil.java:55)
	at net.sourceforge.pmd.lang.java.types.TypeTestUtil.isA(TypeTestUtil.java:116)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.LooseCouplingRule.isAllowedType(LooseCouplingRule.java:72)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.LooseCouplingRule.visit(LooseCouplingRule.java:49)
	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceType.acceptVisitor(ASTClassOrInterfaceType.java:159)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.acceptVisitor(AbstractJavaNode.java:38)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:24)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:232)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.applyOnIndex(RuleApplicator.java:75)
	... 9 more
```
https://github.com/ben-manes/caffeine/actions/runs/6389804412/job/17341828673?pr=1229#step:5:284

**Code Sample demonstrating the issue:**

Project's [rulesSets.xml](https://github.com/ben-manes/caffeine/blob/94a58c4e6b05761efbd5753342dd7a7f95a72df2/gradle/config/pmd/rulesSets.xml#L21-L33).

**Steps to reproduce:**
Check out the PR commit and run the script,
```sh
.github/scripts/analyze.sh
```

**Running PMD through:** *Gradle*

**Comment by jsotuyod** [comment]
@ben-manes it should be a comma-separated string.

I'm unsure about the extra whitespace though… I don't remember if it was trimmed

**Comment by adangel** [comment]
It's mentioned in this section: https://docs.pmd-code.org/latest/pmd_userdocs_migrating_to_pmd7.html#im-using-only-built-in-rules
