### ISSUE TITLE
[apex] New Parser - parsing errors and rule differences

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4722]
**Affects PMD Version:** 

Branch `experimental-apex-parser`

Part of #3766

**Description:**

Collection of parser bugs and rule differences, that need to be investigated.

* ✅ Errors:
  * Parse exception: Couldn't parse the source - there is not root node - Syntax Error??
    * https://github.com/SalesforceLabs/Schedul-o-matic-9000/blob/6b1229ba43b38931fbbab5924bc9b9611d19a786/force-app/main/default/classes/Dao.cls
    * https://github.com/SalesforceLabs/Schedul-o-matic-9000/blob/6b1229ba43b38931fbbab5924bc9b9611d19a786/force-app/main/default/classes/Dao_Test.cls
  * Unhelpful parse exception message - just "Couldn't parse the source - there is not root node - Syntax Error??". Ideally, we would output here something like "at x:y, expect z, but found x". Note, that these two files explicitly contain syntax errors
    * https://github.com/nawforce/apex-link/blob/v2.3.0/samples/synthetic/sfdx-ns-test/force-app/main/default/classes/SingleError.cls
    * https://github.com/nawforce/apex-link/blob/v2.3.0/samples/synthetic/sfdx-ns-test/force-app/main/default/classes/DoubleError.cls
  * Fixed by https://github.com/google/summit-ast/pull/45
* ✅ Errors while executing rules
  * AvoidNonExistentAnnotationsRule
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_QueryFactory.cls
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SecurityUtils.cls
    * ➡️ Caused by the fact, that experimental parser doesn't generate a synthetic modifiers list node for enum values - and that's correct. Enum values can't have modifiers like "public", "static", or "final" - these are implicit.

<details><summary>Stacktrace 1</summary>
<pre>
org.apache.commons.lang3.exception.ContextedRuntimeException: java.lang.NullPointerException
Exception Context:
	[1:Rule applied on node=ApexFile]
---------------------------------
	at net.sourceforge.pmd.util.AssertionUtil.contexted(AssertionUtil.java:232)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.applyOnIndex(RuleApplicator.java:77)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.apply(RuleApplicator.java:55)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:158)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.processSource(PmdRunnable.java:140)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.run(PmdRunnable.java:80)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidNonExistentAnnotationsRule.checkForNonExistentAnnotation(AvoidNonExistentAnnotationsRule.java:62)
	at net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidNonExistentAnnotationsRule.visit(AvoidNonExistentAnnotationsRule.java:58)
	at net.sourceforge.pmd.lang.apex.ast.ASTField.acceptApexVisitor(ASTField.java:42)
	at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.acceptVisitor(AbstractApexNode.java:127)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitNode(ApexParserVisitor.java:17)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visit(ApexParserVisitor.java:24)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitApexNode(ApexParserVisitor.java:29)
	at net.sourceforge.pmd.lang.apex.ast.ApexVisitor.visit(ApexVisitor.java:352)
	at net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidNonExistentAnnotationsRule.visit(AvoidNonExistentAnnotationsRule.java:42)
	at net.sourceforge.pmd.lang.apex.ast.ASTUserEnum.acceptApexVisitor(ASTUserEnum.java:18)
	at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.acceptVisitor(AbstractApexNode.java:127)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitNode(ApexParserVisitor.java:17)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visit(ApexParserVisitor.java:24)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitApexNode(ApexParserVisitor.java:29)
	at net.sourceforge.pmd.lang.apex.ast.ApexVisitor.visit(ApexVisitor.java:344)
	at net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidNonExistentAnnotationsRule.visit(AvoidNonExistentAnnotationsRule.java:30)
	at net.sourceforge.pmd.lang.apex.ast.ASTUserClass.acceptApexVisitor(ASTUserClass.java:21)
	at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.acceptVisitor(AbstractApexNode.java:127)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitNode(ApexParserVisitor.java:17)
	at net.sourceforge.pmd.lang.apex.ast.ApexVisitor.visit(ApexVisitor.java:20)
	at net.sourceforge.pmd.lang.apex.ast.ASTApexFile.acceptApexVisitor(ASTApexFile.java:61)
	at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.acceptVisitor(AbstractApexNode.java:127)
	at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:17)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:232)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.applyOnIndex(RuleApplicator.java:75)
	... 9 more
</pre>
</details>

<details><summary>Stacktrace 2</summary>
<pre>
org.apache.commons.lang3.exception.ContextedRuntimeException: java.lang.NullPointerException
Exception Context:
	[1:Rule applied on node=ApexFile]
---------------------------------
	at net.sourceforge.pmd.util.AssertionUtil.contexted(AssertionUtil.java:232)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.applyOnIndex(RuleApplicator.java:77)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.apply(RuleApplicator.java:55)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:158)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.processSource(PmdRunnable.java:140)
	at net.sourceforge.pmd.lang.impl.PmdRunnable.run(PmdRunnable.java:80)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidNonExistentAnnotationsRule.checkForNonExistentAnnotation(AvoidNonExistentAnnotationsRule.java:62)
	at net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidNonExistentAnnotationsRule.visit(AvoidNonExistentAnnotationsRule.java:58)
	at net.sourceforge.pmd.lang.apex.ast.ASTField.acceptApexVisitor(ASTField.java:42)
	at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.acceptVisitor(AbstractApexNode.java:127)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitNode(ApexParserVisitor.java:17)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visit(ApexParserVisitor.java:24)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitApexNode(ApexParserVisitor.java:29)
	at net.sourceforge.pmd.lang.apex.ast.ApexVisitor.visit(ApexVisitor.java:352)
	at net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidNonExistentAnnotationsRule.visit(AvoidNonExistentAnnotationsRule.java:42)
	at net.sourceforge.pmd.lang.apex.ast.ASTUserEnum.acceptApexVisitor(ASTUserEnum.java:18)
	at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.acceptVisitor(AbstractApexNode.java:127)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitNode(ApexParserVisitor.java:17)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visit(ApexParserVisitor.java:24)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitApexNode(ApexParserVisitor.java:29)
	at net.sourceforge.pmd.lang.apex.ast.ApexVisitor.visit(ApexVisitor.java:344)
	at net.sourceforge.pmd.lang.apex.rule.errorprone.AvoidNonExistentAnnotationsRule.visit(AvoidNonExistentAnnotationsRule.java:30)
	at net.sourceforge.pmd.lang.apex.ast.ASTUserClass.acceptApexVisitor(ASTUserClass.java:21)
	at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.acceptVisitor(AbstractApexNode.java:127)
	at net.sourceforge.pmd.lang.apex.ast.ApexParserVisitor.visitNode(ApexParserVisitor.java:17)
	at net.sourceforge.pmd.lang.apex.ast.ApexVisitor.visit(ApexVisitor.java:20)
	at net.sourceforge.pmd.lang.apex.ast.ASTApexFile.acceptApexVisitor(ASTApexFile.java:61)
	at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.acceptVisitor(AbstractApexNode.java:127)
	at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:17)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:232)
	at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.applyOnIndex(RuleApplicator.java:75)
	... 9 more
</pre>
</details>

* Rule Changes
  * ✅ EmptyStatementBlock - now finds empty catch blocks. Is this correct behavior or a false positive?
    * https://github.com/SalesforceLabs/Schedul-o-matic-9000/tree/6b1229ba43b38931fbbab5924bc9b9611d19a786/force-app/main/default/classes/Scheduler.cls#L124
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_QueryFactoryTest.cls#L270
    * ➡️ This is a new false positive. Empty catch blocks are the duty of the rule "EmptyCatchBlock" and should not be reported by EmptyStatementBlock
   * ✅ AvoidDeeplyNestedIfs - now finds more cases. Is this correct behavior or a false positive?
     * https://github.com/SalesforceLabs/Schedul-o-matic-9000/tree/6b1229ba43b38931fbbab5924bc9b9611d19a786/force-app/main/default/classes/Scheduler.cls#L305
     * https://github.com/SalesforceLabs/Schedul-o-matic-9000/tree/6b1229ba43b38931fbbab5924bc9b9611d19a786/force-app/main/default/classes/Scheduler.cls#L336
     * ➡️ This is actually now correct behavior: Previously two AvoidDeeplyNestedIfStmts were reported on the same line, because the else-if block as incorrect line numbers in the jorje parser variant of PMD. The line numbers are now correct with the experimental parser.
   * ✅ ApexDoc - doesn't find missing apexdoc comment - potential introduced false negative
     * looks like a problem with interfaces...
     * https://github.com/nawforce/apex-link/tree/v2.3.0/samples/synthetic/test-classes/force-app/main/default/classes/API.cls#L2
     * https://github.com/nawforce/apex-link/tree/v2.3.0/samples/synthetic/test-classes/force-app/main/default/classes/Service.cls#L3
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_IDomain.cls#L28
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_IDomain.cls#L29
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_IDomainConstructor.cls#L28
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectDomain.cls#L346
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectDomain.cls#L354
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectUnitOfWork.cls#L84
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectUnitOfWork.cls#L89
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectUnitOfWork.cls#L90
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectUnitOfWork.cls#L91
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectUnitOfWork.cls#L92
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectUnitOfWork.cls#L93
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectUnitOfWork.cls#L846
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectUnitOfWork.cls#L899
     * ➡️ Problem was, that methods defined in interfaces didn't have the implicit modifier attributes (public and abstract), so these methods weren't identified as public methods which need documentation. When determining the modifiers for a ASTMethod, now it is also checked whether this method is part of a interface, and if so, the modifiers are added.
   * ✅ New ApexDoc violation - Missing ApexDoc @description - for static init block. Is this correct or is this a false positive?
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectDomain.cls#L107
     * ➡️ The formal comments were not always added to the correct nodes. In this case, a formal comment on a field was added to the static block (which is in the AST actually the method `<clinit>`). In the Jorje variant, we didn't support formal comments for fields in AST, now we do. So, this is a overall improvement. Note: The rule ApexDoc doesn't consider fields.
   * ✅ FieldDeclarationShouldBeAtStart is reporting wrong line number (it reports the initialization instead of the declaration)
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls#L476 - line 475 should be reported instead
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls#L483 - line 482 should be reported instead
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls#L491 - line 490 should be reported instead
     * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls#L498 - line 497 should be reported instead
     * ➡️ this is corrected by reporting on FieldDeclaration nodes instead of Field nodes.
  * ✅ FieldNamingConventions is reporting wrong line number, similar to FieldDeclarationShouldBeAtStart
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls#L476 - line 475 should be reported instead
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls#L483 - line 482 should be reported instead
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls#L491 - line 490 should be reported instead
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls#L498 - line 497 should be reported instead
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/test/classes/fflib_SObjectUnitOfWorkTest.cls#L32 - line 31 should be reported instead
    * ➡️ this is corrected by reporting on FieldDeclaration nodes instead of Field nodes.
  * ✅ CognitiveComplexity / CyclomaticComplexity - message is different
    * when reporting the method descriptor, generic types are maybe missing? or use a different casing (sobject vs. SObject)
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectDomain.cls#L402
    * see also https://github.com/pmd/pmd-regression-tester/issues/121
    * ➡️ The difference is, that now an additional space is added when there are multiple generic type params, e.g. instead of `Map<Id,SObject>` now it is `Map<Id, SObject>`. I like it this way better, so we keep it and expect slight changes in the violation messages.

**Comment by adangel** [comment]
Remaining differences compared to master (jorje) (see PR #4739):

* :white_check_mark: no new errors
* 3 new violations:
  * AvoidDeeplyNestedIfStmts: https://github.com/SalesforceLabs/Schedul-o-matic-9000/tree/6b1229ba43b38931fbbab5924bc9b9611d19a786/force-app/main/default/classes/Scheduler.cls#L305
    * :arrow_right: This is ok, now else-ifs are flagged correctly
  * AvoidDeeplyNestedIfStmts: https://github.com/SalesforceLabs/Schedul-o-matic-9000/tree/6b1229ba43b38931fbbab5924bc9b9611d19a786/force-app/main/default/classes/Scheduler.cls#L336
    * :arrow_right: This is ok, now else-ifs are flagged correctly
  * Cyclomatic Complexity: https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjects.cls#L26
    * :question: This class is now detected with complexity of 40. Is this correct?
* 3 removed violations - all are ApexDoc
  * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_QueryFactory.cls#L87
  * This is a private method at this line, so I assume this is correct. Seems like we have fixed now a false positive?
  * The messages indicate, that we wrongly detected in the master branch a formal comment for this method (there is clearly now formal comment) - probably we attached the formal comment of a different node to this method 
* 3 violations with changed messages
  * two are caused by the now additional space when reporting the generic types list of method paremeter (`Map<Id,SObject>` vs. `Map<Id, SObject>`), so are ok
  * the other one is calculating a different value for cyclomatic complexity: 79 instead of 78
    * https://github.com/apex-enterprise-patterns/fflib-apex-common/tree/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_SObjectDomain.cls#L41
    * :question: What cyclomatic complexity does this class have? is 79 now correct?

**Comment by adangel** [comment]
Fixed by https://github.com/pmd/pmd/pull/4739
