### ISSUE TITLE
[core] Using Maven, the xmlresolver jar dependency being pulled is incorrect

### ISSUE THREAD

**Issue by jjamieson-va** [pmd/pmd#4986]
**Affects PMD Version:** 7.1

**Description:** When pulling the latest version of PMD out of the maven repository (we pull pmd-core, pmd-java, pmd-ant) it grabs a dependency xmlresolver-5.2.2-data.jar. However, the correct dependency needed is xmlresolver-5.2.2.jar. When downloading the latest distributable of PMD the lib directory has both xmlresolver-5.2.2-data.jar and xmlresolver-5.2.2.jar. 

**Exception Stacktrace:**

Error when running our PMD task through Ant

```
 java.lang.NoClassDefFoundError: org/xmlresolver/Resolver
        at net.sf.saxon.lib.CatalogResourceResolver.<init>(CatalogResourceResolver.java:46)
        at net.sf.saxon.Configuration.init(Configuration.java:386)
        at net.sf.saxon.Configuration.<init>(Configuration.java:233)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at net.sf.saxon.Configuration.newConfiguration(Configuration.java:249)
        at net.sourceforge.pmd.lang.rule.xpath.internal.SaxonXPathRuleQuery.initialize(SaxonXPathRuleQuery.java:190)
        at net.sourceforge.pmd.lang.rule.xpath.internal.SaxonXPathRuleQuery.<init>(SaxonXPathRuleQuery.java:97)
        at net.sourceforge.pmd.lang.rule.xpath.XPathRule.initialize(XPathRule.java:140)
        at net.sourceforge.pmd.lang.rule.RuleReference.initialize(RuleReference.java:405)
        at net.sourceforge.pmd.lang.rule.internal.RuleSets.initializeRules(RuleSets.java:70)
        at net.sourceforge.pmd.lang.impl.BatchLanguageProcessor.launchAnalysis(BatchLanguageProcessor.java:66)
        at net.sourceforge.pmd.PmdAnalysis.performAnalysisImpl(PmdAnalysis.java:441)
        at net.sourceforge.pmd.PmdAnalysis.performAnalysisImpl(PmdAnalysis.java:379)
        at net.sourceforge.pmd.PmdAnalysis.performAnalysis(PmdAnalysis.java:359)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:144)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:248)
        at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:79)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.lang.ClassNotFoundException: org.xmlresolver.Resolver
        at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1402)
        at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1357)
        at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1112)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 39 more
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

Using ivy the following dependency is setup and pulls the incorrect xmlresolver-5.2.2-data.jar:
``
<dependency org="net.sourceforge.pmd" name="pmd-core" rev="7.1.0" conf="codeQuality->default" />
``

I had to update to the following to ensure the correct xmlresolver-5.2.2.jar was pulled. Once this done PMD 7.1 runs without issue:

``
<dependency org="net.sourceforge.pmd" name="pmd-core" rev="7.1.0" conf="codeQuality->default" >
	<exclude module="xmlresolver"/>
</dependency>
<dependency org="org.xmlresolver" name="xmlresolver" rev="5.2.2" conf="codeQuality->default" />
``

**Running PMD through:** Ant to build with Ivy to pull dependencies, JDK 17

**Comment by jsotuyod** [comment]
These are transitive dependencies we get from Saxon. Saxon correctly propagates both, as seen on our own repo doing `./mvn dependency:tree`

```
[INFO] |  +- net.sf.saxon:Saxon-HE:jar:12.4:compile
[INFO] |  |  +- org.xmlresolver:xmlresolver:jar:5.2.2:compile
[INFO] |  |  |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.1.3:runtime
[INFO] |  |  |  |  +- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.1.3:runtime
[INFO] |  |  |  |  \- commons-codec:commons-codec:jar:1.15:runtime
[INFO] |  |  |  \- org.apache.httpcomponents.core5:httpcore5:jar:5.1.3:runtime
[INFO] |  |  \- org.xmlresolver:xmlresolver:jar:data:5.2.2:compile
```

This is definitely not an issue on PMD.

The `data` is a classifier… Ivy has a long history of not understanding classifiers properly.  Even the very latest release from last August (2.5.2) include in it's changelog:

> FIX: reading POMs may loose dependencies when multiple Maven dependencies only differ in classifier ([IVY-1642](https://issues.apache.org/jira/browse/IVY-1642)). Note, if you have resolved dependencies with version of Ivy prior to 2.5.2 you may need to remove your Ivy cache for this fix to have any effect.

So, my advice is:
1. Update to 2.5.2 if not already using it, clear the cache and try again
2. If not, report the issue to Ivy, and in the meantime manually adding the dependencies is a possible workaround
