### ISSUE TITLE
[java] java.lang.StackOverflowError at TypeOps$RecursionStop.recurseIfNotDone

### ISSUE THREAD

**Issue by jochenberger** [pmd/pmd#5044]
**Affects PMD Version:** 

7.1.0, 7.0.0
6.55.0 does not produce the error

**Description:**

I'm getting a StackOverflowError running PMD 7.1.0 on my sources. Unfortunately, I haven't been able to isolate the file that causes the error yet, enabling DEBUG level logging did not provide any clues. Any suggestions?

**Exception Stacktrace:**

```
java.lang.StackOverflowError
        at net.sourceforge.pmd.lang.java.types.TypeOps$RecursionStop.recurseIfNotDone(TypeOps.java:1082)
        at net.sourceforge.pmd.lang.java.types.TypeOps$ProjectionVisitor.visitClass(TypeOps.java:1146)
        at net.sourceforge.pmd.lang.java.types.TypeOps$ProjectionVisitor.visitClass(TypeOps.java:1108)
        at net.sourceforge.pmd.lang.java.types.JClassType.acceptVisitor(JClassType.java:312)
        at net.sourceforge.pmd.lang.java.types.TypeOps$1.visitTypeVar(TypeOps.java:996)
        at net.sourceforge.pmd.lang.java.types.TypeOps$1.visitTypeVar(TypeOps.java:991)
        at net.sourceforge.pmd.lang.java.types.JTypeVar.acceptVisitor(JTypeVar.java:103)
        at net.sourceforge.pmd.lang.java.types.TypeOps$ProjectionVisitor.lambda$visitClass$0(TypeOps.java:1146)
        at net.sourceforge.pmd.lang.java.types.TypeOps$RecursionStop.recurseIfNotDone(TypeOps.java:1077)
        at net.sourceforge.pmd.lang.java.types.TypeOps$ProjectionVisitor.visitClass(TypeOps.java:1146)
        at net.sourceforge.pmd.lang.java.types.TypeOps$ProjectionVisitor.visitClass(TypeOps.java:1108)
        at net.sourceforge.pmd.lang.java.types.JClassType.acceptVisitor(JClassType.java:312)
        at net.sourceforge.pmd.lang.java.types.TypeOps$1.visitTypeVar(TypeOps.java:996)
        at net.sourceforge.pmd.lang.java.types.TypeOps$1.visitTypeVar(TypeOps.java:991)
        at net.sourceforge.pmd.lang.java.types.JTypeVar.acceptVisitor(JTypeVar.java:103)
---

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle

**Comment by jochenberger** [comment]
Oh, I just found #5029. Sorry for the noise.
