### ISSUE TITLE
[java] NPE in MethodTypeResolution for static methods

### ISSUE THREAD

**Issue by deki** [pmd/pmd#534]
There is an NPE in MethodTypeResolution in master branch that doesn't occur using latest release. Seems to happen for static methods.

@WinterGrascph could you please take a look?

**Description:**
```
Caused by: java.lang.NullPointerException
        at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.isSubtypeable(MethodTypeResolution.java:488)
        at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.isSubtypeable(MethodTypeResolution.java:479)
        at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.selectMethodsFirstPhase(MethodTypeResolution.java:111)
        at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.getBestMethodReturnType(MethodTypeResolution.java:228)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:454)
        at net.sourceforge.pmd.lang.java.ast.ASTName.jjtAccept(ASTName.java:35)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:314)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:998)
        at net.sourceforge.pmd.lang.java.ast.ASTPrimaryPrefix.jjtAccept(ASTPrimaryPrefix.java:42)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:841)
        at net.sourceforge.pmd.lang.java.ast.ASTPrimaryExpression.jjtAccept(ASTPrimaryExpression.java:21)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Maven

**Comment by WinterGrascph** [comment]
Hey, thanks for reporting the issue!

Could you please elaborate on when do you get this error?

**Comment by WinterGrascph** [comment]
The NPE is probably caused by an argument having no type (because the code to resolve it is missing or flawed), but please provide a code example that produces the error.

**Comment by deki** [comment]
Reproducing should be easy, in my simplest case the NPE occurs for this auto-generated `toString()` method:

```
   @Override
   public String toString() {
      final StringBuilder sb = new StringBuilder("TestClass{");
      sb.append("portId='").append(portId).append('\'');
      sb.append(", providerId='").append(providerId).append('\'');
      sb.append(", providerName='").append(providerName).append('\'');
      sb.append('}');
      return sb.toString();
   }
```

![debugger](https://user-images.githubusercontent.com/858827/28909702-ce72d63a-7829-11e7-93c3-8e1c7fd1552f.png)

**Comment by adangel** [comment]
Might be part of #653 , at least, I've seen this stacktrace already

**Comment by adangel** [comment]
I've added a null-check here: https://github.com/pmd/pmd/pull/653/files#diff-8d9049b8b2d522b7ab5128df5ef94423R627

So, this NPE doesn't appear anymore, but the type information being null means, we don't get all types yet.
