### ISSUE TITLE
[java] NPE in TypeInferenceResolver 

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#609]
**Rule Set:** Any

**Description:** NPE in typeres when processing RuleSetReference.java. Stack trace:

```
Error while processing file: /home/clifrr/Documents/Git/pmd/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetReference.java
net.sourceforge.pmd.PMDException: Error while processing /home/clifrr/Documents/Git/pmd/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetReference.java
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:103)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:52)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:93)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at net.sourceforge.pmd.lang.java.typeresolution.typeinference.TypeInferenceResolver.getMinimalErasedCandidateSet(TypeInferenceResolver.java:180)
	at net.sourceforge.pmd.lang.java.typeresolution.typeinference.TypeInferenceResolver.lub(TypeInferenceResolver.java:77)
	at net.sourceforge.pmd.lang.java.typeresolution.typeinference.TypeInferenceResolver.resolveVariables(TypeInferenceResolver.java:227)
	at net.sourceforge.pmd.lang.java.typeresolution.typeinference.TypeInferenceResolver.inferTypes(TypeInferenceResolver.java:56)
	at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.parameterizeInvocation(MethodTypeResolution.java:174)
	at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.selectMethodsFirstPhase(MethodTypeResolution.java:138)
	at net.sourceforge.pmd.lang.java.typeresolution.MethodTypeResolution.getBestMethodReturnType(MethodTypeResolution.java:354)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:466)
	at net.sourceforge.pmd.lang.java.ast.ASTName.jjtAccept(ASTName.java:35)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
	at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
	at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:314)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:1017)
```

**Code Sample demonstrating the issue:** Seems to be the first constructor:

```
public class RuleSetReference {
    private final String ruleSetFileName;
    private final boolean allRules;
    private final Set<String> excludes;

    public RuleSetReference(final String theFilename, final boolean allRules, final Set<String> excludes) {
        ruleSetFileName = theFilename;
        this.allRules = allRules;
        this.excludes = Collections.unmodifiableSet(new LinkedHashSet<>(excludes));
    }

    /* ... */
}

```

**Running PMD through:** CLI

**Comment by jsotuyod** [comment]
This one should be fixed by #653
