### ISSUE TITLE
[java] The PMD  hangs when processing reports

### ISSUE THREAD

**Issue by dreaminplus** [pmd/pmd#673]
Hi, 
 When scanning one specific project(About 1600+ java files), it costs too much time...
After my debugging, I found it hangs and its details are described below:

**
"main" #1 prio=5 os_prio=0 tid=0x00007f561c008800 nid=0x8a0b waiting on condition [0x00007f562029f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006cb0ec080> (a java.util.concurrent.FutureTask)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at net.sourceforge.pmd.processor.MultiThreadProcessor.processReports(MultiThreadProcessor.java:69)
        at net.sourceforge.pmd.processor.MultiThreadProcessor.processFiles(MultiThreadProcessor.java:56)
        at net.sourceforge.pmd.PMD.processFiles(PMD.java:352)
        at net.sourceforge.pmd.PMD.doPMD(PMD.java:251)
        at net.sourceforge.pmd.PMD.run(PMD.java:459)
**

How could this happen? Any suspicious causes yield this?

**Comment by jsotuyod** [comment]
@dreaminplus thanks for the report! I'm most interested on your issue, having personally worked a lot on PMD's performance over the last year. I fear however I'm missing some very important information to be able to take a deeper look into this.

1. what PMD version are you using?
2. how are you running it? CLI? Ant? Gradle? Maven?
3. what parameters / configuration are you using on your tool? (that is, besides rulesets / source dirs, I'm interested on any other configuration parameters on how PMD runs)

Thanks in advanced

**Comment by jsotuyod** [comment]
@dreaminplus any chance you can get back on us with this info?

**Comment by jsotuyod** [comment]
@dreaminplus could you check this? I'm still very intrigued by this report. PMD itself is over 1600 files and is processed flawlessly each time.

**Comment by jsotuyod** [comment]
Closing this due to lack of feedback.
