### ISSUE TITLE
[java] NPE in PMD 5.8.1 InvalidSlf4jMessageFormat

### ISSUE THREAD

**Issue by huxi** [pmd/pmd#721]
**Rule Set:**
`<rule ref="rulesets/java/logging-java.xml/InvalidSlf4jMessageFormat"/>`

**Description:**
The following error is printed:
```
Exception applying rule InvalidSlf4jMessageFormat on file [...]/LoggerHelper.java, continuing with next rule
java.lang.NullPointerException
	at net.sourceforge.pmd.lang.java.rule.logging.InvalidSlf4jMessageFormatRule.expectedArguments(InvalidSlf4jMessageFormatRule.java:161)
	at net.sourceforge.pmd.lang.java.rule.logging.InvalidSlf4jMessageFormatRule.visit(InvalidSlf4jMessageFormatRule.java:76)
	at net.sourceforge.pmd.lang.java.ast.ASTName.jjtAccept(ASTName.java:35)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:75)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:380)
	at net.sourceforge.pmd.lang.java.ast.ASTPrimaryPrefix.jjtAccept(ASTPrimaryPrefix.java:42)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:75)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:376)
	at net.sourceforge.pmd.lang.java.ast.ASTPrimaryExpression.jjtAccept(ASTPrimaryExpression.java:21)
```

**Code Sample demonstrating the issue:**

```java
public class LoggerHelper {
    public LoggerHelper(int entriesCount, long sleepingInterval, String loggerName, String message) {
        Logger logger = LoggerFactory.getLogger(loggerName);

        for (int i = 0; i < entriesCount; i++) {
            logger.info(message);

            try {
                Thread.sleep(sleepingInterval);
            }
            catch(InterruptedException e) {
                // nothing to do here!
            }
        }
    }

    public static void main(String[] args) {
        if (args.length != 4) {
            System.err.println("Invalid command line parameters ...");
            System.out.println("USAGE: LoggerHelper <count of log entries> <sleeping interval> <logger-name> <message>");
            System.exit(-1);
        }

        int entriesCount = Integer.parseInt(args[0]);
        long sleepingInterval = Long.parseLong(args[1]);
        String loggerName = args[2];
        String logMessage = args[3];

        new LoggerHelper(entriesCount, sleepingInterval, loggerName, logMessage);
    }
}
```

**Running PMD through:** *Gradle*

**Comment by jsotuyod** [comment]
@huxi very interesting! Thanks for the report, we will try to address this ASAP.
