### ISSUE TITLE
[xml] IllegalAccessException when accessing attribute using Saxon on JRE 9

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#739]
Trying to use **Saxon and jre 9** to execute *any* xml xpath rule that accesses an attribute causes an IllegalAccessException. The attribute value is [defaulted to null](https://github.com/pmd/pmd/blob/ab80d18ff61d28bafdf8bece762d9385f0a6183b/pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java#L49).

```
java.lang.IllegalAccessException: class net.sourceforge.pmd.lang.ast.xpath.Attribute cannot access class com.sun.proxy.jdk.proxy2.$Proxy10 (in module jdk.proxy2) because module jdk.proxy2 does not export com.sun.proxy.jdk.proxy2 to unnamed module @59e84876
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at net.sourceforge.pmd.lang.ast.xpath.Attribute.getValue(Attribute.java:43)
	at net.sourceforge.pmd.lang.ast.xpath.saxon.AttributeNode.atomize(AttributeNode.java:50)
	at net.sf.saxon.om.AxisIteratorImpl.atomize(AxisIteratorImpl.java:74)
	at net.sf.saxon.expr.AxisAtomizingIterator.next(AxisAtomizingIterator.java:43)
	at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:39)
	at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:39)
	at net.sf.saxon.expr.CardinalityChecker.evaluateItem(CardinalityChecker.java:262)
	at net.sf.saxon.functions.Contains.evaluateItem(Contains.java:42)
	at net.sf.saxon.expr.Expression.iterate(Expression.java:370)
	at net.sf.saxon.expr.Expression.effectiveBooleanValue(Expression.java:421)
	at net.sf.saxon.functions.BooleanFn.effectiveBooleanValue(BooleanFn.java:179)
	at net.sf.saxon.expr.FilterIterator$NonNumeric.matches(FilterIterator.java:182)
	at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:65)
	at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:44)
	at net.sf.saxon.value.SequenceExtent.<init>(SequenceExtent.java:98)
	at net.sf.saxon.sort.DocumentOrderIterator.<init>(DocumentOrderIterator.java:30)
	at net.sf.saxon.sort.DocumentSorter.iterate(DocumentSorter.java:85)
	at net.sf.saxon.sxpath.XPathExpression.evaluate(XPathExpression.java:98)
	at net.sourceforge.pmd.lang.rule.xpath.SaxonXPathRuleQuery.evaluate(SaxonXPathRuleQuery.java:116)
	at net.sourceforge.pmd.lang.rule.XPathRule.evaluate(XPathRule.java:93)
	at net.sourceforge.pmd.lang.rule.XPathRule.apply(XPathRule.java:78)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:473)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:181)
```

After some digging I found [this relevant resource](https://docs.oracle.com/javase/9/docs/api/java/lang/reflect/Proxy.html#membership). I think we may be in case 2.a : [the proxy](https://github.com/pmd/pmd/blob/ab80d18ff61d28bafdf8bece762d9385f0a6183b/pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java#L87) we use lives in a dynamic module, (here named jdk.proxy2) which makes it inaccessible to the unnamed package (in which the code of pmd currently lives I guess).

**Comment by adangel** [comment]
This might be a Java9 incompatibility. If this holds true, then maybe no XPath rule can be executed, if PMD runs under Java9?

**Comment by jsotuyod** [comment]
Maybe it's time to drop Saxon and just stick to Jaxen?

**Comment by oowekyala** [comment]
I'd like more to update the saxon version to see if this is resolved. The version we use came out a decade ago, it's certainly not built for Java 9. But the latest version came out last month. Jaxen, in comparison, has been undeveloped since 2012. Why would we want to stick with only Jaxen?

**Comment by oowekyala** [comment]
I've fiddled with the Saxon version, just upgrading doesn't solve the problem. 

But we can stop using a synthesized proxy and write our own proxy class, which implements ast.Node and wraps an org.w3c.Node. It would replace XmlNodeInvocationHandler (with some added boilerplate).

**Comment by jsotuyod** [comment]
@oowekyala last time I checked upgrading Saxon was a daring and painful task. Saxon is a heavyweight library, which provides lots of functionality we don't really use nor need. I know Jaxen is not perfect, but neither is Saxon for that matter.

**Comment by oowekyala** [comment]
@jsotuyod For what it's worth, commit oowekyala/pmd@581b307d updates the version to Saxon HE 9.8.0. The adapter classes (ElementNode, DocumentNode, AttributeNode) could benefit from a deeper cleanup, using [AbstractNodeWrapper](https://www.saxonica.com/html/documentation9.6/javadoc/net/sf/saxon/tree/wrapper/AbstractNodeWrapper.html) as a base. The major difference from Saxon B (the current version) is the absence of an XPath 1.0 compatibility mode. The commit doesn't clean that up
