### ISSUE TITLE
[java] UnsupportedClassVersionError is failure instead of a warning

### ISSUE THREAD

**Issue by ben-manes** [pmd/pmd#814]
In 5.8.1, if a dependency was for a newer Java version then this produced a warning that did not fail the build. In 6.0.0 it fails the task.

This is useful when the project is built on one JVM version, but may allow additions when compiled with a newer version. In this case, a JDK9 library may be enabled to run in an comparative analysis but the project is still JDK8 otherwise. It should only fail at runtime if enabled and run on JDK8.

```
Caused by: java.lang.UnsupportedClassVersionError: systems/comodal/collision/cache/CollisionCache has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at net.sourceforge.pmd.util.ClasspathClassLoader.loadClass(ClasspathClassLoader.java:103)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredField(Class.java:2068)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.getFieldType(ClassTypeResolver.java:569)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:918)
        at net.sourceforge.pmd.lang.java.ast.ASTPrimaryExpression.jjtAccept(ASTPrimaryExpression.java:21)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:230)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:712)
```

**Comment by jsotuyod** [comment]
@ben-manes this is an interesting scenario...

PMD should certainly not break upon this (which I'll fix), but you should still run PMD using the latest JRE you intend to support. Otherwise, PMD's analysis of these files / constructs will be incomplete, and therefore, we can't guarantee quality.

**Comment by ben-manes** [comment]
Oh definitely. I run the CI build against JDK8 and JDK9, but a 9-only release is a ways off. I updated the build to disable the PMD analysis on the failing project (a cache simulator) so that this isn't a bother.
