### ISSUE TITLE
[java] Error Stack Trace when reading file

### ISSUE THREAD

**Issue by JJengility** [pmd/pmd#852]
Please, prefix the report title with the language it applies to within brackets, such as [java] or [apex].
If not specific to a language, you can use [core].

**Affects PMD Version:**  6.0.0

**Rule:**

**Description:** Unable to read files  

<error filename="C:\9pts\PTSDEV\src\com\hpti\pts\dao\IPtsEntityManager.java" msg="Error while processing C:\9pts\PTSDEV\src\com\hpti\pts\dao\IPtsEntityManager.java">
<![CDATA[net.sourceforge.pmd.PMDException: Error while processing C:\9pts\PTSDEV\src\com\hpti\pts\dao\IPtsEntityManager.java
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:101)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:50)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:75)
	at net.sourceforge.pmd.processor.MonoThreadProcessor.runAnalysis(MonoThreadProcessor.java:29)
	at net.sourceforge.pmd.processor.AbstractPMDProcessor.processFiles(AbstractPMDProcessor.java:111)
	at net.sourceforge.pmd.PMD.processFiles(PMD.java:315)
	at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:192)
	at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:276)
	at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:49)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at net.sourceforge.pmd.lang.java.typeresolution.visitors.PMDASMVisitor.<init>(PMDASMVisitor.java:40)
	at net.sourceforge.pmd.lang.java.typeresolution.PMDASMClassLoader.getImportedClasses(PMDASMClassLoader.java:108)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.populateClassName(ClassTypeResolver.java:1434)
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:205)
	at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:41)
	at net.sourceforge.pmd.lang.java.typeresolution.TypeResolutionFacade.initializeWith(TypeResolutionFacade.java:18)
	at net.sourceforge.pmd.lang.java.AbstractJavaHandler$5.start(AbstractJavaHandler.java:97)
	at net.sourceforge.pmd.SourceCodeProcessor.usesTypeResolution(SourceCodeProcessor.java:149)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:177)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:95)
	... 24 more
]]>
</error>

**Code Sample demonstrating the issue:**

```
package com.hpti.pts.dao;

import java.util.Collection;
import java.util.Map;

/**
 * This interface was taken from https://www.hibernate.org/328.html and modified to match an EntityManager
 * 
 * @author kwinter
 */
public interface IPtsEntityManager {



	/**
	 * Persists the object.
	 * 
	 * @param entity the entity
	 * 
	 * @throws PtsPersistenceException the pts persistence exception
	 */
	void persist(Object entity) throws PtsPersistenceException;

	/**
	 * Synchronize the persistence context to the underlying database.
	 * 
	 * @throws PtsPersistenceException the pts persistence exception
	 */
	void flush() throws PtsPersistenceException;

	/**
	 * Find by example.
	 * 
	 * @param entityClass the entity class
	 * @param properties the properties
	 * 
	 * @return the collection< t>
	 * 
	 * @throws PtsPersistenceException the pts persistence exception
	 */
	<T> Collection<T> findByExample(Class<T> entityClass, Map<String, Object> properties)
		throws PtsPersistenceException;

	/**
	 * The Class PtsPersistenceException.
	 */
	@SuppressWarnings("serial")
	class PtsPersistenceException extends RuntimeException {

		/**
		 * Instantiates a new pts persistence exception.
		 * 
		 * @param message the message
		 */
		public PtsPersistenceException(String message) {
			super(message);
		}

		/**
		 * Instantiates a new pts persistence exception.
		 */
		public PtsPersistenceException() {
			super();
		}

		/**
		 * Instantiates a new pts persistence exception.
		 * 
		 * @param message the message
		 * @param cause the cause
		 */
		public PtsPersistenceException(String message, Throwable cause) {
			super(message, cause);
		}

		/**
		 * Instantiates a new pts persistence exception.
		 * 
		 * @param cause the cause
		 */
		public PtsPersistenceException(Throwable cause) {
			super(cause);
		}
	}
}

```

**Running PMD through:**  Ant

**Comment by jsotuyod** [comment]
@JJengility this looks like you are trying to analyze bytecode that is compiled against a version of Java not supported. This is weird, as ASM 6 (shipped in PM 6.0.0) supports Java 9.

I'd therefore like to:

1. make sure you are referencing the proper asm-6.0.jar in the PMD task classpath (and not the old 5.x)
2. indicate which version of Java you are setting as compile target
3. which version of Java you are currently using
