### ISSUE TITLE
[plsql] ParseException for CREATE TABLE

### ISSUE THREAD

**Issue by dvdtknsn** [pmd/pmd#980]
Please, prefix the report title with the language it applies to within brackets, such as [java] or [apex].
If not specific to a language, you can use [core].

**Affects PMD Version:** 
6.1.0
**Rule:**
Issue parsing a .sql file that has a CREATE TABLE definition
**Description:**
net.sourceforge.pmd.PMDException: Error while parsing D:\flOraGithubRepo\HR_WF\Database\HR\Tables\CUSTOMERS.sql
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:98)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:50)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:75)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:23)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: net.sourceforge.pmd.lang.plsql.ast.ParseException: Encountered "  "PRIMARY "" at line 5, column 27.
Was expecting one of:
    "@" ...
    "." ...
    "," ...
    ")" ...
    "%" ...
    "DEFAULT" ...
    "NOT" ...
    "NULL" ...
    
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.generateParseException(PLSQLParser.java:40789)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.jj_consume_token(PLSQLParser.java:40643)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Table(PLSQLParser.java:22556)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Input(PLSQLParser.java:180)
	at net.sourceforge.pmd.lang.plsql.PLSQLParser.parse(PLSQLParser.java:48)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:110)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:173)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:95)
**Code Sample demonstrating the issue:**
-- this is the customers.sql file:
CREATE TABLE customers
( customer_id number(10) NOT NULL,
  customer_name varchar2(50) NOT NULL,
  city varchar2(50),
  CONSTRAINT customers_pk PRIMARY KEY (customer_id)
);

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Windows command line:
call Tools\pmd\bin\pmd -d "Database\HR" -l plsql -R pmd_ruleset.xml -f summaryhtml -r Artifacts\static_analysis_report.html

**Comment by dvdtknsn** [comment]
Just found https://sourceforge.net/p/pmd/discussion/188194/thread/a677f39b/ that possibly implies that this isn't supported. Either way, I'd expect it to skip what it can't understand rather than throwing an exception.

**Comment by jsotuyod** [comment]
@dvdtknsn definitely. The parser shouldn't throw when processing valid PL/SQL.
