### ISSUE TITLE
[core] FileNotFoundException for missing classes directory with analysis cache enabled

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#988]
**Affects PMD Version:** 6.1.0

**Description:**

Original issue: https://issues.apache.org/jira/browse/MPMD-255

While trying to determine the checksum for the auxclasspath, we might encounter a `FileNotFoundException`, if one of the directories of the auxclasspath doesn't exist.

I think, we need to take care of this in PMD itself, to make it more safe.
But the m-pmd-p provides the auxclasspath and it obviously provides a "theoretical" classpath, even if the directory doesn't exist.
This might happen if the project really has no  `src/main/java` (e.g. just tests) or m-pmd-p is executed directly without compiling the project first.

Stacktrace:

```
Caused by: java.io.FileNotFoundException: my-project\target\classes (The system cannot find the file specified)
    at java.io.FileInputStream.open0 (Native Method)
    at java.io.FileInputStream.open (FileInputStream.java:195)
    at java.io.FileInputStream.<init> (FileInputStream.java:138)
    at java.io.FileInputStream.<init> (FileInputStream.java:93)
    at sun.net.www.protocol.file.FileURLConnection.connect (FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream (FileURLConnection.java:188)
    at java.net.URL.openStream (URL.java:1045)
    at net.sourceforge.pmd.cache.AbstractAnalysisCache.computeClassPathHash (AbstractAnalysisCache.java:182)
    at net.sourceforge.pmd.cache.AbstractAnalysisCache.checkValidity (AbstractAnalysisCache.java:113)
    at net.sourceforge.pmd.processor.AbstractPMDProcessor.processFiles (AbstractPMDProcessor.java:105)
    at net.sourceforge.pmd.PMD.processFiles (PMD.java:311)
    at org.apache.maven.plugins.pmd.PmdReport.processFilesWithPMD (PmdReport.java:503)
    at org.apache.maven.plugins.pmd.PmdReport.executePmd (PmdReport.java:432)
    at org.apache.maven.plugins.pmd.PmdReport.executePmdWithClassloader (PmdReport.java:331)
    at org.apache.maven.plugins.pmd.PmdReport.canGenerateReport (PmdReport.java:305)
```

**Running PMD through:** Maven

**Comment by jsotuyod** [comment]
@adangel definitely on PMD's end. Thanks for bringing this here.

**Comment by blindpirate** [comment]
I also encountered this issue. I was trying to add incremental analysis to Gradle, but encountered this issue if I enabled incremental analysis and passed an `auxclasspath` containing an inexistent file:

```
Using auxclasspath: /Users/zhb/Projects/tmp/codeQuality/build/classes/java/main:/Users/zhb/Projects/tmp/codeQuality/build/classes/groovy/main:/Users/zhb/Projects/tmp/codeQuality/build/resources/main
```

What's worse, it's followed by a NPE:

```
Caused by: java.lang.NullPointerException
        at net.sourceforge.pmd.util.StringUtil.appendXmlEscaped(StringUtil.java:214)
        at net.sourceforge.pmd.renderers.XMLRenderer.end(XMLRenderer.java:132)
        at net.sourceforge.pmd.ant.Formatter.end(Formatter.java:117)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:202)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:276)
        at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:49)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        ... 60 more
```

Seems `pe.getFile()` is `null` in this line: https://github.com/pmd/pmd/blob/d25fbcf8c0b52b5e97dca3ea169f0eed5ca53ecd/pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java#L124

**Comment by sebastianhaberey** [comment]
First, thanks for fixing this! One small "but" though: for those of us that try to keep their maven build log warning-free, it would be nice to have a way around the warning.

Our specific case is a multi-module project where the maven-pmd-plugin is configured in the pom-only parent project. During the build, maven will run PMD on the parent project and all its subprojects. Since the parent project never contains source code, but PMD has to be configured there, we will always have this warning in our log.

I can see how this may be a maven-pmd-plugin issue rather than a pmd issue, though.

**Comment by Fernal73** [comment]
So how do I turn off this warning? Is there any way of specifying an empty auxclasspath to the maven PMD plugin?

**Comment by adangel** [comment]
@Fernal73 Could you create a reproduction case please? This issue is now 2 years old and I don't know, whether the problem still exists (and what the problem actually is...). If this problem still is present, then we need to open a *new* issue - since this issue is closed and this ship has long sailed (almost exactly 2 years now...).
According to the linked issues, this has been fixed with PMD 6.3.0 and maven-pmd-plugin 3.10.0.
you'll need to test with the latest versions 6.24.0 and maven-pmd-plugin 3.13.0.
Thanks!

**Comment by Fernal73** [comment]
What exactly do I need to test?
As far as I understand, the auxclasspath is garnered from the compile and test dependencies.

I am still receiving the warning about the auxclasspath file not existing as it simply points to the target/.../classes directory stating that this file does not exist.

How do I not receive this warning in my build process?

The pom file is located at:

https://github.com/Fernal73/DSAlgos/blob/master/pom.xml

**Comment by Fernal73** [comment]
```
  6.24.0     WӀ   M{w    ) K/data/data/com.termux/files/home/DSAlgos/src/main/java/ds/package-info.java     X 	     H/data/data/com.termux/files/home/DSAlgos/src/main/java/ds/HighArray.java    PKꍀ    Q/data/data/com.termux/files/home/DSAlgos/src/test/java/ds/tests/package-info.java    @R j     B/data/data/com.termux/files/home/DSAlgos/src/main/java/ds/App.java    7 mx     L/data/data/com.termux/files/home/DSAlgos/src/test/java/ds/tests/AppTest.java    m۹     
```

The above is the contents of my pmd.cache file. I don't see any reference to any classpaths or auxclasspath.

**Comment by bobtiernay-okta** [comment]
If this really bothers folks, you can put this in your `.mvn/jvm.config` file as a workaround:
``
-Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd.cache=error
```
